Merge changes from current as of 20200406

diff --git a/distrib/common/bootimage/Makefile.bootimage b/distrib/common/bootimage/Makefile.bootimage
--- a/distrib/common/bootimage/Makefile.bootimage
+++ b/distrib/common/bootimage/Makefile.bootimage
@@ -1,4 +1,4 @@
-#	$NetBSD: Makefile.bootimage,v 1.17.12.1 2019/06/10 21:42:20 christos Exp $
+#	$NetBSD: Makefile.bootimage,v 1.17.12.2 2020/04/08 14:03:44 martin Exp $
 #
 # Copyright (c) 2009, 2010, 2011 Izumi Tsutsui.  All rights reserved.
 #
@@ -37,6 +37,9 @@
 #	USE_MBR
 #		set yes if target disk image requires MBR partition
 #		(default: no)
+#	USE_GPT
+#		set yes if target disk image requires GPT partition
+#		(default: no)
 #	MBR_BOOTCODE
 #		optional MBR bootcode which should be installed by fdisk(8)
 #		(default: empty)
@@ -57,6 +60,12 @@
 #	SWAPMB
 #		swap size in target image in MB
 #		(default: 128)
+#	EFIMB
+#		EFI partition size in target image in MB
+#		(default: 128)
+#	FATMB
+#		FAT partition size in target image in MB
+#		(default: 0)
 #	KERN_SET
 #		kernel set name which should be extracted into image
 #		(default: kern-GENERIC)
@@ -114,9 +123,18 @@
 #		template file of disklabel -R
 #		(default: ${DISTRIBDIR}/common/bootimage/diskproto.in
 #		       or ${DISTRIBDIR}/common/bootimage/diskproto.mbr.in)
-#	OMIT_SWAPIMG
-#		no need to put swap partition into image (for USB stick)
-#		(default: no)
+#	EFIBOOT
+#		EFI bootloader
+#		(default: empty)
+#	MBRFAT
+#		MBR partition type value for FAT
+#		(default: 6 ("16-bit FAT, more than 32M"))
+#	FATMAKEFSOPTIONS
+#		options passed to makefs(8) to create a FAT partition
+#		(default: -o fat_type=16)
+#	FATFILES
+#		list of additional files to be copied into FAT partition
+#		(default: empty)
 #
 
 .include <bsd.own.mk> 		#
@@ -126,6 +144,7 @@
 
 .if ${MKREPRO_TIMESTAMP:Uno} != "no"
 MAKEFS_TIMESTAMP=-T "${MKREPRO_TIMESTAMP}"
+GPT_TIMESTAMP=-T "${MKREPRO_TIMESTAMP}"
 PAX_TIMESTAMP=--timestamp "${MKREPRO_TIMESTAMP}"
 .endif
 
@@ -146,6 +165,7 @@ RM?=		rm
 # common definitions for image
 #
 USE_MBR?=	no
+USE_GPT?=	no
 USE_SUNLABEL?=	no
 INSTALLBOOT_AFTER_DISKLABEL?=	no
 
@@ -154,12 +174,22 @@ INSTALLBOOT_AFTER_DISKLABEL?=	no
 #
 IMAGEMB?=	2048		# 2048MB
 SWAPMB?=	128		# 128MB
+.if ${USE_GPT} == "no"
+EFIMB?=		0
+GPTSECTORS=	0
+.else
+EFIMB?=		128		# 128MB
+GPTSECTORS=	2048
+.endif
+FATMB?=		0
 
 # XXX: SWAPMB could be zero and expr(1) returns exit status 1 in that case
 IMAGESECTORS!=	expr ${IMAGEMB} \* 1024 \* 1024 / 512
 SWAPSECTORS!=	expr ${SWAPMB} \* 1024 \* 1024 / 512 || true
+EFISECTORS!=	expr ${EFIMB} \* 1024 \* 1024 / 512 || true
+FATSECTORS!=	expr ${FATMB} \* 1024 \* 1024 / 512 || true
 
-.if ${USE_MBR} == "no"
+.if ${USE_MBR} == "no" && ${USE_GPT} == "no"
 LABELSECTORS?=	0
 .else
 #LABELSECTORS?=	63	# historical
@@ -167,7 +197,8 @@ LABELSECTORS?=	0
 LABELSECTORS?=	2048	# 1MB aligned for modern flash devices
 .endif
 
-FSSECTORS!=	expr ${IMAGESECTORS} - ${SWAPSECTORS} - ${LABELSECTORS}
+FSSECTORS!=	expr ${IMAGESECTORS} - ${SWAPSECTORS} - ${LABELSECTORS} \
+		    - ${EFISECTORS} - ${GPTSECTORS} - ${FATSECTORS}
 FSSIZE!=	expr ${FSSECTORS} \* 512
 
 # parameters for disklabel and MBR
@@ -179,15 +210,23 @@ MBRHEADS=	255
 MBRSECTORS=	63
 MBRCYLINDERS!=	expr ${IMAGESECTORS} / \( ${MBRHEADS} \* ${MBRSECTORS} \)
 MBRNETBSD=	169
+MBRFAT?=	6	# 16-bit FAT, more than 32M
 
-BSDPARTSECTORS!= expr ${IMAGESECTORS} - ${LABELSECTORS}
-FSOFFSET=	${LABELSECTORS}
-SWAPOFFSET!=	expr ${LABELSECTORS} + ${FSSECTORS}
+BSDPARTSECTORS!= expr ${IMAGESECTORS} - ${LABELSECTORS} \
+		    - ${EFISECTORS} - ${GPTSECTORS} - ${FATSECTORS}
+FSOFFSET!=	expr ${LABELSECTORS} + ${EFISECTORS} + ${FATSECTORS}
+SWAPOFFSET!=	expr ${LABELSECTORS} + ${FSSECTORS} \
+		    + ${EFISECTORS} + ${FATSECTORS}
+FATOFFSET=	${LABELSECTORS}
 
 # parameters for sunlabel
 FSCYLINDERS!=	expr ${FSSECTORS} / \( ${HEADS} \* ${SECTORS} \)
 SWAPCYLINDERS!=	expr ${SWAPSECTORS} / \( ${HEADS} \* ${SECTORS} \) || true
 
+.if ${USE_GPT} != "no"
+BOOTDISK_UUID=`${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKMBR} show -i 2 | ${TOOL_AWK} '/^GUID/ {print $$2}'`
+SWAPDISK_UUID=`${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKMBR} show -i 3 | ${TOOL_AWK} '/^GUID/ {print $$2}'`
+.endif
 
 #
 # definitions to create root fs
@@ -206,6 +245,7 @@ FSTAB_IN?=	${DISTRIBDIR}/common/bootimage/fstab.in
 SPEC_IN?=	${DISTRIBDIR}/common/bootimage/spec.in
 
 IMGMAKEFSOPTIONS?=	-o bsize=16384,fsize=2048,density=8192
+FATMAKEFSOPTIONS?=	-o fat_type=16
 
 WORKDIR?=       work
 WORKSPEC?=      work.spec
@@ -220,9 +260,67 @@ CLEANFILES+=	${WORKSPEC} ${WORKFSTAB} ${WORKRCCONF} ${WORKFS}
 CLEANFILES+=	${TARGETFS}
 
 #
+# definitions to create image
+#
+.if ${SWAPSECTORS} == 0
+.  if ${USE_MBR} != "no"
+DISKPROTO_IN?=	${DISTRIBDIR}/common/bootimage/diskproto.noswap.mbr.in
+.  else
+DISKPROTO_IN?=	${DISTRIBDIR}/common/bootimage/diskproto.noswap.in
+.  endif
+.else
+.  if ${USE_MBR} != "no"
+DISKPROTO_IN?=	${DISTRIBDIR}/common/bootimage/diskproto.mbr.in
+.  else
+DISKPROTO_IN?=	${DISTRIBDIR}/common/bootimage/diskproto.in
+.  endif
+.endif
+
+MBR_DEFAULT_BOOTCODE?=	mbr
+
+WORKMBR?=	work.mbr
+WORKMBRTRUNC?=	work.mbr.truncated
+WORKSWAP?=	work.swap
+WORKEFI?=	work.efi
+WORKGPT?=	work.gpt
+WORKLABEL?=	work.diskproto
+WORKIMG?=	work.img
+EFIWORKDIR?=	work.efidir
+WORKFAT?=	work.fat
+WORKFATDIR?=	work.fatdir
+
+.if ${USE_GPT} != "no"
+${WORKFSTAB}: ${WORKMBR}
+.endif
+
+${WORKFSTAB}:
+	@echo Preparing /etc/fstab ...
+.if ${USE_GPT} != "no"
+.  if ${SWAPSECTORS} != 0
+	${TOOL_SED}							\
+	    -e "s/ROOT.a/NAME=${BOOTDISK_UUID}/"			\
+	    -e "s/ROOT.b/NAME=${SWAPDISK_UUID}/"			\
+	    < ${FSTAB_IN} > ${WORKFSTAB}
+.  else
+	${TOOL_SED}							\
+	    -e "s/ROOT.a/NAME=${BOOTDISK_UUID}/"			\
+	    -e "/ROOT.b/d"						\
+	    < ${FSTAB_IN} > ${WORKFSTAB}
+.  endif
+.else
+.  if ${SWAPSECTORS} != 0
+	${TOOL_SED} < ${FSTAB_IN} > ${WORKFSTAB}
+.  else
+	${TOOL_SED}							\
+	    -e "/ROOT.b/d"						\
+	    < ${FSTAB_IN} > ${WORKFSTAB}
+.  endif
+.endif
+
+#
 # create root file system for the image
 #
-${TARGETFS}: prepare_md_post
+${TARGETFS}: prepare_md_post ${WORKFSTAB}
 	@if [ ! -d ${RELEASEDIR}/${RELEASEMACHINEDIR} ]; then 		\
 		echo "Missing ${RELEASEDIR}/${RELEASEMACHINEDIR}, aborting"; \
 		false; 							\
@@ -242,8 +340,6 @@ ${TARGETFS}: prepare_md_post
 	@echo Copying secondary boot...
 	${INSTALL} ${COPY} -m 0444 ${WORKDIR}/usr/mdec/${SECONDARY_BOOT} ${WORKDIR}
 .endif
-	@echo Preparing /etc/fstab ...
-	${TOOL_SED} < ${FSTAB_IN} > ${WORKFSTAB}
 	${INSTALL} ${COPY} -m 0644 ${WORKFSTAB} ${WORKDIR}/etc/fstab
 	@echo Setting rc_configured=YES in /etc/rc.conf ...
 	${TOOL_SED} "s/rc_configured=NO/rc_configured=YES/"		\
@@ -306,27 +402,39 @@ ${TARGETFS}: prepare_md_post
 	@echo done.
 	mv ${WORKFS} ${.TARGET}
 
-#
-# definitions to create image
-#
-.if ${USE_MBR} != "no"
-DISKPROTO_IN?=	${DISTRIBDIR}/common/bootimage/diskproto.mbr.in
-.else
-DISKPROTO_IN?=	${DISTRIBDIR}/common/bootimage/diskproto.in
+TARGET_BLOCKS=
+.if ${USE_MBR} != "no" || ${USE_GPT} != "no"
+TARGET_BLOCKS+=	${WORKMBRTRUNC}
+.endif
+.if ${USE_GPT} != "no"
+TARGET_BLOCKS+=	${WORKEFI}
+.endif
+.if ${FATSECTORS} != 0
+TARGET_BLOCKS+=	${WORKFAT}
+.endif
+TARGET_BLOCKS+=	 ${TARGETFS}
+.if ${SWAPSECTORS} != 0
+TARGET_BLOCKS+=	${WORKSWAP}
+.endif
+.if ${USE_GPT} != "no"
+TARGET_BLOCKS+=	${WORKGPT}
 .endif
 
-MBR_DEFAULT_BOOTCODE?=	mbr
-
-OMIT_SWAPIMG?=	no
-
-WORKMBR?=	work.mbr
-WORKSWAP?=	work.swap
-WORKLABEL?=	work.diskproto
-WORKIMG?=	work.img
-
-CLEANFILES+=	${WORKMBR} ${WORKSWAP}
+CLEANFILES+=	${WORKMBR} ${WORKMBRTRUNC} ${WORKSWAP}
+CLEANFILES+=	${WORKEFI} ${WORKGPT}
+CLEANFILES+=	${WORKFAT}
 CLEANFILES+=	${WORKLABEL}.tmp ${WORKLABEL}
 CLEANFILES+=	${WORKIMG} ${IMGBASE}.img
+
+${WORKSWAP}:
+.if ${SWAPSECTORS} == 0
+	printf "" > ${WORKSWAP}
+.else
+	${DD} if=/dev/zero of=${WORKSWAP} seek=$$((${SWAPSECTORS} - 1)) count=1
+.endif
+
+${WORKMBRTRUNC}: ${WORKMBR}
+	${DD} if=${WORKMBR} count=${LABELSECTORS} of=${WORKMBRTRUNC}
 
 ${WORKLABEL}:
 	${TOOL_SED}							\
@@ -340,18 +448,77 @@ ${WORKLABEL}:
 	    -e "s/@@SWAPSECTORS@@/${SWAPSECTORS}/"			\
 	    -e "s/@@SWAPOFFSET@@/${SWAPOFFSET}/"			\
 	    -e "s/@@BSDPARTSECTORS@@/${BSDPARTSECTORS}/"		\
+	    -e "s/@@FATSECTORS@@/${FATSECTORS}/"			\
+	    -e "s/@@FATOFFSET@@/${FATOFFSET}/"				\
 	    < ${DISKPROTO_IN} > ${WORKLABEL}.tmp
 	mv ${WORKLABEL}.tmp ${WORKLABEL}
 
-${IMGBASE}.img:	${TARGETFS} ${WORKLABEL}
-.if ${USE_MBR} != "no"
+${WORKEFI}: ${TARGETFS}
+	@echo create EFI system partition...
+	@${MKDIR} ${MKDIRPERM} ${EFIWORKDIR}/EFI/boot
+.for f in ${EFIBOOT}
+	${INSTALL} ${COPY} -m 0644 ${f} ${EFIWORKDIR}/EFI/boot/`basename ${f}`
+.endfor
+	${RM} -f ${WORKEFI}
+	${TOOL_MAKEFS} -M ${EFIMB}m -m ${EFIMB}m			\
+	    -B ${TARGET_ENDIANNESS}					\
+	    ${MAKEFS_TIMESTAMP}						\
+	    -t msdos -o F=32,c=1					\
+	    ${WORKEFI} ${EFIWORKDIR}
+
+${WORKFAT}: ${TARGETFS} ${FATFILES}
+	@echo create FAT partition for bootstrap files...
+	@${MKDIR} ${MKDIRPERM} ${WORKFATDIR}
+.if defined(FATFILES)
+	@echo Copying files for FAT partition...
+.for f in ${FATFILES}
+	@if [ ! -f ${f} ]; then 					\
+		echo "${f} in FATFILES not found, aborting";		\
+		false; 							\
+	fi
+	${INSTALL} ${COPY} -m 0644 ${f} ${WORKFATDIR}
+.endfor
+.endif
+	${RM} -f ${WORKFAT}
+	${TOOL_MAKEFS} -M ${FATMB}m -m ${FATMB}m			\
+	    ${MAKEFS_TIMESTAMP}						\
+	    -t msdos							\
+	    ${FATMAKEFSOPTIONS}						\
+	    ${WORKFAT} ${WORKFATDIR}
+
+${WORKMBR}:
+.if ${USE_GPT} != "no"
+	@echo creating GPT header and partition entries...
+	${RM} -f ${WORKMBR}
+	${DD} if=/dev/zero of=${WORKMBR} seek=$$((${IMAGESECTORS} - 1)) count=1
+	${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKMBR} create
+	${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKMBR} add -a 1m -s ${EFISECTORS} -t efi -l "EFI system"
+	${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKMBR} add -a 1m -s ${FSSECTORS} -t ffs
+.  if ${SWAPSECTORS} != 0
+	${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKMBR} add -a 1m -s ${SWAPSECTORS} -t swap
+.  endif
+.elif ${USE_MBR} != "no"
 	@echo creating MBR labels...
 	${DD} if=/dev/zero of=${WORKMBR} seek=$$((${IMAGESECTORS} - 1)) count=1
+.  if ${FATSECTORS} != 0
+	# create BSD partition
+	${TOOL_FDISK} -f -i -u \
+	    -b ${MBRCYLINDERS}/${MBRHEADS}/${MBRSECTORS}		\
+	    -1 -a -s ${MBRNETBSD}/${FSOFFSET}/${BSDPARTSECTORS}		\
+	    -F ${WORKMBR}
+	# create FAT partition
+	${TOOL_FDISK} -f -u \
+	    -b ${MBRCYLINDERS}/${MBRHEADS}/${MBRSECTORS}		\
+	    -0 -s ${MBRFAT}/${FATOFFSET}/${FATSECTORS}			\
+	    -F ${WORKMBR}
+.  else
+	# create BSD partition
 	${TOOL_FDISK} -f -i -u \
 	    -b ${MBRCYLINDERS}/${MBRHEADS}/${MBRSECTORS}		\
 	    -0 -a -s ${MBRNETBSD}/${FSOFFSET}/${BSDPARTSECTORS}		\
 	    -F ${WORKMBR}
-.if empty(MBR_BOOTCODE)
+.  endif
+.  if empty(MBR_BOOTCODE)
 	@if [ -f ${WORKDIR}/usr/mdec/${MBR_DEFAULT_BOOTCODE} ]; then 	\
 		echo ${TOOL_FDISK} -f					\
 		    -i -c ${WORKDIR}/usr/mdec/${MBR_DEFAULT_BOOTCODE}	\
@@ -360,23 +527,32 @@ ${IMGBASE}.img:	${TARGETFS} ${WORKLABEL}
 		    -i -c ${WORKDIR}/usr/mdec/${MBR_DEFAULT_BOOTCODE}	\
 		    -F ${WORKMBR};					\
 	fi
-.else
+.  else
 	@if [ ! -f ${WORKDIR}/usr/mdec/${MBR_BOOTCODE} ]; then 		\
 		echo "${MBR_BOOTCODE} is not found in DESTDIR/usr/mdec, aborting"; \
 		false; 							\
 	fi
 	${TOOL_FDISK} -f -i -c ${WORKDIR}/usr/mdec/${MBR_BOOTCODE}	\
 	    -F ${WORKMBR}
+.  endif
 .endif
-	${DD} if=${WORKMBR} count=${LABELSECTORS} |			\
-	    ${CAT} - ${TARGETFS} > ${WORKIMG}
-.else	# USE_MBR == "no"
-	${INSTALL} ${COPY} -m 0644 ${TARGETFS} ${WORKIMG}
-.endif	# USE_MBR != "no"
-.if ${OMIT_SWAPIMG} == "no"
-	${DD} if=/dev/zero of=${WORKSWAP} seek=$$((${SWAPSECTORS} - 1)) count=1
-	${CAT} ${WORKSWAP} >> ${WORKIMG}
+
+${WORKGPT}: ${WORKMBR}
+	@echo create GPT image...
+	${DD} if=${WORKMBR} of=${WORKGPT} skip=$$((${IMAGESECTORS} - 2048)) \
+	    count=2048
+
+.if ${USE_GPT} == "no"
+${IMGBASE}.img:	${WORKLABEL}
 .endif
+
+${IMGBASE}.img:	${TARGET_BLOCKS}
+	${CAT} ${TARGET_BLOCKS} > ${WORKIMG}
+.if ${USE_GPT} != "no"
+	${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKIMG} biosboot -i 2		\
+	    -c ${.OBJDIR}/${WORKDIR}/usr/mdec/gptmbr.bin
+	${TOOL_GPT} ${GPT_TIMESSTAMP} ${WORKIMG} set -a bootme -i 2
+.endif	# USE_GPT != "no"
 .if ${USE_SUNLABEL} != "no"
 	@echo Creating sun disklabel...
 	printf 'V ncyl %d\nV nhead %d\nV nsect %d\na %d %d/0/0\nb %d %d/0/0\nW\n' \
@@ -384,13 +560,14 @@ ${IMGBASE}.img:	${TARGETFS} ${WORKLABEL}
 	    ${FSOFFSET} ${FSCYLINDERS} ${FSCYLINDERS} ${SWAPCYLINDERS} | \
 	    ${TOOL_SUNLABEL} -nq ${WORKIMG}
 .endif
+.if ${USE_GPT} == "no"
 	${TOOL_DISKLABEL} -R -F ${WORKIMG} ${WORKLABEL}
 .if !empty(PRIMARY_BOOT) && ${INSTALLBOOT_AFTER_DISKLABEL} != "no"
 	${TOOL_INSTALLBOOT} -v -m ${MACHINE} ${INSTALLBOOTOPTIONS} ${WORKIMG} \
 	    ${WORKDIR}/usr/mdec/${PRIMARY_BOOT}
 .endif
+.endif
 	mv ${WORKIMG} ${.TARGET}
-
 
 CLEANFILES+=	${IMGBASE}.img.gz ${IMGBASE}.img.gz.tmp
 
@@ -403,6 +580,8 @@ clean:
 		${CHMOD} +r ${WORKDIR}/var/spool/ftp/hidden;		\
 	fi	# XXX
 	${RM} -fr ${WORKDIR}
+	${RM} -fr ${EFIWORKDIR}
+	${RM} -fr ${WORKFATDIR}
 
 prepare_md_post: .PHONY
 image_md_post: .PHONY
diff --git a/external/ibm-public/postfix/dist/conf/postfix-script b/external/ibm-public/postfix/dist/conf/postfix-script
--- a/external/ibm-public/postfix/dist/conf/postfix-script
+++ b/external/ibm-public/postfix/dist/conf/postfix-script
@@ -1,5 +1,5 @@
 #!/bin/sh
-#	$NetBSD: postfix-script,v 1.2 2017/02/14 01:16:43 christos Exp $
+#	$NetBSD: postfix-script,v 1.2.12.1 2020/04/08 14:06:49 martin Exp $
 #
 
 #++
@@ -25,6 +25,11 @@
 #	IBM T.J. Watson Research
 #	P.O. Box 704
 #	Yorktown Heights, NY 10598, USA
+#
+#	Wietse Venema
+#	Google, Inc.
+#	111 8th Avenue
+#	New York, NY 10011, USA
 #--
 
 # Avoid POSIX death due to SIGHUP when some parent process exits.
@@ -119,7 +124,7 @@ stop_msg)
 	echo "Stop postfix"
 	;;
 
-start)
+start|start-fg)
 
 	$daemon_directory/master -t 2>/dev/null || {
 		$FATAL the Postfix mail system is already running
@@ -136,12 +141,34 @@ start)
 		# Foreground this so it can be stopped. All inodes are cached.
 		$daemon_directory/postfix-script check-warn
 	fi
-	$INFO starting the Postfix mail system
-	# NOTE: wait in foreground process to get the initialization status.
-	$daemon_directory/master -w || {
-	    $FATAL "mail system startup failed"
-	    exit 1
-	}
+	$INFO starting the Postfix mail system || exit 1
+	case $1 in
+	start)
+	    # NOTE: wait in foreground process to get the initialization status.
+	    $daemon_directory/master -w || {
+		$FATAL "mail system startup failed"
+		exit 1
+	    }
+	    ;;
+	start-fg)
+	    # Foreground start-up is incompatible with multi-instance mode.
+	    # Use "exec $daemon_directory/master" only if PID == 1.
+	    # Otherwise, doing so would break process group management,
+	    # and "postfix stop" would kill too many processes.
+	    case $instances in
+	    "") case $$ in
+		 1) exec $daemon_directory/master -i
+		    $FATAL "cannot start-fg the master daemon"
+		    exit 1;;
+		 *) $daemon_directory/master -s;;
+		esac
+		;;
+	     *) $FATAL "start-fg does not support multi_instance_directories"
+		exit 1
+		;;
+	    esac
+	    ;;
+	esac
 	;;
 
 drain)
@@ -241,6 +268,18 @@ check-fatal)
 	test -f $config_directory/master.cf || {
 		$FATAL no $config_directory/master.cf file found
 		exit 1
+	}
+
+	maillog_file=`$command_directory/postconf -h maillog_file` || {
+		$FATAL cannot execute $command_directory/postconf!
+		exit 1
+	}
+	test -n "$maillog_file" && {
+		$command_directory/postconf -M postlog/unix-dgram 2>/dev/null \
+		    | grep . >/dev/null || {
+			$FATAL "missing 'postlog' service in master.cf - run 'postfix upgrade-configuration'"
+			exit 1
+		}
 	}
 
 	# See if all queue files are in the right place. This is slow.
@@ -368,9 +407,41 @@ tls)
 	"$@"
 	;;
 
+logrotate)
+	case $# in
+	1) ;;
+	*) $FATAL "usage postfix $1 (no arguments)"; exit 1;;
+	esac
+	for name in maillog_file maillog_file_compressor \
+	   maillog_file_rotate_suffix
+	do
+	    value="`$command_directory/postconf -h $name`"
+	    case "$value" in
+	    "") $FATAL "empty '$name' parameter value - logfile rotation failed"
+		exit 1;;
+	    esac
+	    eval $name='"$value"';
+	done
+
+	case "$maillog_file" in
+	/dev/*) $FATAL "not rotating '$maillog_file'"; exit 1;;
+	esac
+
+	errors=`(
+	    suffix="\`date +$maillog_file_rotate_suffix\`" || exit 1
+	    mv "$maillog_file" "$maillog_file.$suffix" || exit 1
+	    $daemon_directory/master -t 2>/dev/null ||
+		kill -HUP \`sed 1q pid/master.pid\` || exit 1
+	    sleep 1
+	    "$maillog_file_compressor" "$maillog_file.$suffix" || exit 1
+	) 2>&1` || {
+	    $FATAL "logfile '$maillog_file' rotation failed: $errors"
+	    exit 1
+	}
+	;;
+
 *)
-	$ERROR "unknown command: '$1'"
-	$FATAL "usage: postfix start (or stop, reload, abort, flush, check, status, set-permissions, upgrade-configuration)"
+	$FATAL "unknown command: '$1'. Usage: postfix start (or stop, reload, abort, flush, check, status, set-permissions, upgrade-configuration, logrotate)"
 	exit 1
 	;;
 
