GNU mpfr 4.1.0.  main changes from 4.0:
Changed __float128 to the type _Float128 specified in ISO/IEC TS 18661.
__float128 is used as a fallback if _Float128 is not supported.
New function mpfr_get_str_ndigits about conversion to a string of digits.
New function mpfr_dot for the dot product (incomplete, experimental).
New functions mpfr_get_decimal128 and mpfr_set_decimal128 (available
only when MPFR has been built with decimal float support).
New function mpfr_cmpabs_ui.
New function mpfr_total_order_p for the IEEE 754 totalOrder predicate.
The mpfr_out_str function now accepts bases from -2 to -36, in order to
follow mpfr_get_str and GMP's mpf_out_str functions (these cases gave an
assertion failure, as with other invalid bases).
Shared caches: cleanup; really detect lock failures (abort in this case).
Improved mpfr_add and mpfr_sub when all operands have a precision
equal to twice the number of bits per word, e.g., 128 bits on a 64-bit
platform.
Optimized the tuning parameters for various architectures.

diff --git a/external/lgpl3/mpfr/dist/tests/Makefile.am b/external/lgpl3/mpfr/dist/tests/Makefile.am
--- a/external/lgpl3/mpfr/dist/tests/Makefile.am
+++ b/external/lgpl3/mpfr/dist/tests/Makefile.am
@@ -1,4 +1,4 @@
-# Copyright 2000-2018 Free Software Foundation, Inc.
+# Copyright 2000-2020 Free Software Foundation, Inc.
 # This Makefile.am is free software; the Free Software Foundation
 # gives unlimited permission to copy and/or distribute it,
 # with or without modifications, as long as this notice is preserved.
@@ -9,9 +9,25 @@
 # PARTICULAR PURPOSE.
 
 
+# Since we do not require GNU "make", let's select the POSIX behavior to
+# uniformize the behavior a bit more with various "make" implementations
+# and ease maintenance. This target should be removed only if one day,
+# we need to require GNU "make".
+.POSIX:
+
 AUTOMAKE_OPTIONS = 1.6 gnu
 
-check_PROGRAMS = tversion tabort_prec_max tassert tabort_defalloc1	\
+output_info = { \
+  if [ -d $(top_srcdir)/.svn ]; then \
+    output=`svnversion $(top_srcdir) 2> /dev/null`; \
+    if [ -n "$$output" ]; then \
+      echo "[svnversion] $$output"; \
+    fi; \
+  fi; \
+  grep -v '^\(PASS\|FAIL\) ' tversion.log 2> /dev/null || true; \
+}
+
+TESTS_NO_TVERSION = tabort_prec_max tassert tabort_defalloc1		\
      tabort_defalloc2 talloc tinternals tinits tisqrt tsgn tcheck	\
      tisnan texceptions tset_exp tset mpf_compat mpfr_compat reuse	\
      tabs tacos tacosh tadd tadd1sp tadd_d tadd_ui tagm tai		\
@@ -19,34 +35,41 @@ check_PROGRAMS = tversion tabort_prec_max tassert tabort_defalloc1	\
      tcan_round tcbrt tcmp tcmp2 tcmp_d tcmp_ld tcmp_ui tcmpabs		\
      tcomparisons tconst_catalan tconst_euler tconst_log2 tconst_pi	\
      tcopysign tcos tcosh tcot tcoth tcsc tcsch td_div td_sub tdigamma	\
-     tdim tdiv tdiv_d tdiv_ui teint teq terandom terandom_chisq terf	\
-     texp texp10 texp2 texpm1 tfactorial tfits tfma tfmma tfmod tfms	\
-     tfpif tfprintf tfrac tfrexp tgamma tgamma_inc tget_d tget_d_2exp	\
-     tget_f tget_flt tget_ld_2exp tget_q tget_set_d64 tget_sj		\
-     tget_str tget_z tgmpop tgrandom thyperbolic thypot tinp_str	\
+     tdim tdiv tdiv_d tdiv_ui tdot teint teq terandom terandom_chisq    \
+     terf texp texp10 texp2 texpm1 tfactorial tfits tfma tfmma tfmod    \
+     tfms tfpif tfprintf tfrac tfrexp tgamma tgamma_inc tget_d          \
+     tget_d_2exp tget_f tget_flt tget_ld_2exp tget_q tget_set_d64       \
+     tget_set_d128 tget_sj tget_str tget_z tgmpop tgrandom thyperbolic  \
+     thypot tinp_str							\
      tj0 tj1 tjn tl2b tlgamma tli2 tlngamma tlog tlog10 tlog1p tlog2	\
      tlog_ui tmin_prec tminmax tmodf tmul tmul_2exp tmul_d tmul_ui	\
      tnext tnrandom tnrandom_chisq tout_str toutimpl tpow tpow3		\
-     tpow_all tpow_z tprintf trandom trandom_deviate trec_sqrt		\
-     tremquo trint trndna troot trootn_ui tround_prec tsec tsech	\
+     tpow_all tpow_z tprec_round tprintf trandom trandom_deviate	\
+     trec_sqrt tremquo trint trndna troot trootn_ui tsec tsech		\
      tset_d tset_f tset_float128 tset_ld tset_q tset_si tset_sj		\
      tset_str tset_z tset_z_exp tsi_op tsin tsin_cos tsinh tsinh_cosh	\
      tsprintf tsqr tsqrt tsqrt_ui tstckintc tstdint tstrtofr		\
      tsub tsub1sp tsub_d tsub_ui tsubnormal tsum tswap ttan ttanh	\
-     ttrunc tui_div tui_pow tui_sub turandom tvalist ty0 ty1 tyn	\
-     tzeta tzeta_ui
+     ttotal_order ttrunc tui_div tui_pow tui_sub turandom tvalist	\
+     ty0 ty1 tyn tzeta tzeta_ui
+
+check_PROGRAMS = tversion $(TESTS_NO_TVERSION)
+
+LOGS_NO_TVERSION = $(TESTS_NO_TVERSION:%=%.log)
 
 # Before Automake 1.13, we ran tversion at the beginning and at the end
 # of the tests, and output from tversion appeared at the same place as
 # the tests results (make output). With Automake 1.13+, the tests are
 # parallelized by default and their output is sent to log files instead
 # of the make output, so that the user could no longer see information
-# from tversion. To mimic the old behavior, we now output the contents
-# of the tversion log file if this file exists (i.e. if the Makefile
-# has been generated with Automake 1.13+); but this is done only when
-# no tests fail.
+# from tversion. To mimic the old behavior, we now run tversion at the
+# beginning and output the contents. Also output the contents after the
+# tests, but when a test fails, they will not be shown.
+tversion_special: tversion.log
+	@$(output_info)
+$(LOGS_NO_TVERSION): tversion_special
 check:
-	cat tversion.log 2> /dev/null || true
+	@$(output_info)
 
 AM_CPPFLAGS = -DSRCDIR='"$(srcdir)"'
 
@@ -77,17 +100,29 @@ $(top_builddir)/src/libmpfr.la:
 
 TESTS = $(check_PROGRAMS)
 
+# Set DISPLAY='' as it is not needed and it can yield error messages when
+# running the tests with LOG_COMPILER=wine (for builds with MinGW). See:
+#   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914822
+#   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914949
 # $(VALGRIND) is still there to be able to use a wrapper such as valgrind
 # in case old Automake. With Automake 1.13+, where a parallel test harness
 # is generated, use LOG_COMPILER instead. For additional information, see:
-# http://www.gnu.org/software/automake/manual/automake.html#Parallel-Test-Harness
-TESTS_ENVIRONMENT = MPFR_QUIET=1 $(VALGRIND)
+# https://www.gnu.org/software/automake/manual/automake.html#Parallel-Test-Harness
+#
+# Note: We do not use "env -u DISPLAY" as the -u option is a GNU extension
+# and not supported by NetBSD. Setting DISPLAY='' is not equivalent, but
+# it also avoids the bogus "Invalid MIT-MAGIC-COOKIE-1 key" error message
+# that can make the parsing of the output fail.
+TESTS_ENVIRONMENT = env DISPLAY='' MPFR_QUIET=1 $(VALGRIND)
 
 # The -no-install option prevents libtool from generating wrapper scripts
 # for the tests.
-# This is useful to easily run the test scripts under valgrind or gdb.
-# See discussion http://thread.gmane.org/gmane.comp.lib.gnulib.bugs/28033
-# http://article.gmane.org/gmane.comp.lib.gnulib.bugs/28140 in particular.
+# This is useful to easily run individual test scripts under valgrind or gdb.
+# See discussion
+#   https://lists.gnu.org/archive/html/bug-gnulib/2011-08/msg00247.html
+# and
+#   https://lists.gnu.org/archive/html/bug-gnulib/2011-09/msg00081.html
+# in particular.
 #
 # The -L$(top_builddir)/src/.libs option is necessary for some platforms,
 # such as HP-UX, when --with-gmp or --with-gmp-lib is used and an old MPFR
@@ -105,3 +140,5 @@ TESTS_ENVIRONMENT = MPFR_QUIET=1 $(VALGRIND)
 #   http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18662
 #
 AM_LDFLAGS = -no-install -L$(top_builddir)/src/.libs
+
+.PHONY: tversion_special
