postfix 1.1.11 check following for list of changes: ftp://ftp.porcupine.org/mirrors/postfix-release/official/postfix-1.1.11.RELEASE_NOTES

diff --git a/gnu/dist/postfix/postfix-install b/gnu/dist/postfix/postfix-install
--- a/gnu/dist/postfix/postfix-install
+++ b/gnu/dist/postfix/postfix-install
@@ -174,7 +174,7 @@ do
     case $arg in
       *=*) IFS= eval $arg; IFS="$BACKUP_IFS";;
 -non-int*) non_interactive=1;;
-        *) echo $0: Error: $USAGE 1>&2; exit 1;;
+        *) echo "$0: Error: $USAGE" 1>&2; exit 1;;
     esac
     shift
 done
