Pull up following revision(s) (requested by riz in ticket #10704): 	etc/rc.d/fsck: revision 1.6 Trap SIGINT so that if fsck is interrupted by ^C, we drop into single-user mode.  Fixes misc/29822 from der Mouse, fix from Arnaud Lacombe with comment rework by me.

diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: fsck,v 1.4 2003/10/20 15:02:15 christos Exp $
+# $NetBSD: fsck,v 1.4.4.1 2006/10/08 11:24:44 bouyer Exp $
 #
 
 # PROVIDE: fsck
@@ -28,8 +28,8 @@ fsck_start()
 	if [ -e /fastboot ]; then
 		echo "Fast boot: skipping disk checks."
 	else
-					# During fsck ignore SIGQUIT
-		trap : 3
+		trap : 2		# Ignore SIGINT, SIGQUIT, so we
+		trap : 3		# enter single-user mode on failure.
 
 		echo "Starting file system checks:"
 		fsck $fsck_flags
