- fix typo; the first ipsec_start() should be ipsec_prestart() - if ipsec.conf isn't readable and the system is booting directly to multiuser,   send SIGTERM to the parent (/etc/rc) so that init(8) aborts the boot.

diff --git a/etc/rc.d/ipsec b/etc/rc.d/ipsec
--- a/etc/rc.d/ipsec
+++ b/etc/rc.d/ipsec
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: ipsec,v 1.4 2000/07/17 13:10:54 lukem Exp $
+# $NetBSD: ipsec,v 1.5 2000/07/21 01:16:07 lukem Exp $
 #
 
 # PROVIDE: ipsec
@@ -19,13 +19,22 @@ reload_precmd="$stop_precmd"
 reload_cmd="ipsec_reload"
 extra_commands="reload"
 
-ipsec_start()
+ipsec_prestart()
 {
 	if ! checkyesno ipsec; then
 		return 1
 	fi
 	if [ ! -f /etc/ipsec.conf ]; then
 		warn "/etc/ipsec.conf not readable; ipsec start aborted."
+			#
+			# If booting directly to multiuser, send SIGTERM to
+			# the parent (/etc/rc) to abort the boot
+			#
+		if [ "$autoboot" = yes ]; then
+			echo "ERROR: ABORTING BOOT (sending SIGTERM to parent)!"
+			kill -TERM $$
+			exit 1
+		fi
 		return 1
 	fi
 	return 0
