Improve on the migration bit. Check if files are different, and if not, remove the source and leave a symlink behind. Otherwise, let the user know.

diff --git a/etc/rc.d/named b/etc/rc.d/named
--- a/etc/rc.d/named
+++ b/etc/rc.d/named
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: named,v 1.16 2005/07/17 16:30:57 christos Exp $
+# $NetBSD: named,v 1.17 2005/07/17 21:28:45 christos Exp $
 #
 
 # PROVIDE: named
@@ -17,6 +17,44 @@ pidfile="/var/run/${name}.pid"
 start_precmd="named_precmd"
 extra_commands="reload"
 required_dirs="$named_chrootdir"	# if it is set, it must exist
+
+named_migrate()
+{
+	local src=$1
+	local dst=$2$1
+	echo "Migrating $src to $dst"
+(
+	diff=false
+	cd $src
+	for f in $(find . -type f)
+	do
+		f=${f##./}
+		case $f in
+		*/*)
+			d=$dst$(dirname $f)
+			;;
+		*)	d=$dst
+			;;
+		esac
+		mkdir -p $d
+		if [ -r "$dst$f" ]
+		then
+			if ! cmp $f $dst$f; then
+				diff=true
+			fi
+		else
+			cp -p $f $dst$f
+		fi
+	done
+	if $diff; then
+		echo "Cannot complete migration because files are different"
+		echo "Run 'diff -r $src $dst' resolve the differences"
+	else
+		rm -fr $src
+		ln -s $dst $src
+	fi
+)
+}
 
 named_precmd()
 {
@@ -58,13 +96,8 @@ named_precmd()
 		fi
 	done
 
-	if [ -d /etc/namedb ]; then
-		(cd /etc/namedb && for i in *; do
-			j=${named_chrootdir}/etc/namedb/$i
-			if [ ! -r $j ]; then
-				cp -rp $i $j
-			fi
-		done)
+	if [ ! -h /etc/namedb ]; then
+		named_migrate /etc/namedb ${named_chrootdir}
 	fi
 	if [ \( ! -r ${named_chrootdir}/etc/named.conf \) -a \
 	    \( -r ${named_chrootdir}/etc/namedb/named.conf \) ]; then
