Adapt /etc/rc.d/swap1 and swap2 scripts to the new meaning of exit status 2 from swapctl(8).

diff --git a/etc/rc.d/swap1 b/etc/rc.d/swap1
--- a/etc/rc.d/swap1
+++ b/etc/rc.d/swap1
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: swap1,v 1.10 2009/04/21 16:08:57 joerg Exp $
+# $NetBSD: swap1,v 1.11 2009/09/24 16:45:48 apb Exp $
 #
 
 # PROVIDE: localswap
@@ -18,8 +18,11 @@ stop_cmd="swap1_stop"
 #
 swap1_start()
 {
+	# Treat exit status 2 from swapctl(8) as successful; it means
+	# "no error, but no suitable swap devices were configured".
+	#
 	if ! checkyesno no_swap; then
-		swapctl -A -t blk
+		swapctl -A -t blk || [ $? = 2 ]
 	fi
 }
 
@@ -29,7 +32,7 @@ swap1_stop()
 {
 	if checkyesno swapoff || [ -n "$rc_force" ]; then
 		echo "Removing block-type swap devices"
-		swapctl -U -t blk
+		swapctl -U -t blk || [ $? = 2 ]
 	fi
 }
 
