Ensure that (almost) all shell variables in distrib/sets/* scripts are used with curly braces and quotes, as in "${var}".
Also ensure that command substitution is quoted, as in "$(command)", and
convert `command` to $(command).

Reviewed by agc

diff --git a/distrib/sets/checkflist b/distrib/sets/checkflist
--- a/distrib/sets/checkflist
+++ b/distrib/sets/checkflist
@@ -1,28 +1,28 @@
 #! /bin/sh --
 #
-#	$NetBSD: checkflist,v 1.28 2006/01/03 16:40:16 apb Exp $
+#	$NetBSD: checkflist,v 1.29 2006/01/03 18:31:09 apb Exp $
 #
-# Verify output of makeflist against contents of $DESTDIR.
+# Verify output of makeflist against contents of ${DESTDIR}.
 
-if [ -z "$DESTDIR" ]; then
+if [ -z "${DESTDIR}" ]; then
 	echo "DESTDIR must be set"
 	exit 1
 fi
 
-prog=${0##*/}
+prog="${0##*/}"
 rundir="$(dirname "$0")" # ${0%/*} isn't good enough when there's no "/"
 . "${rundir}/sets.subr"
 
-SDIR=$(${MKTEMP} -d /tmp/${prog}.XXXXXX)
+SDIR="$(${MKTEMP} -d "/tmp/${prog}.XXXXXX")"
 
 es=0
 cleanup()
 {
-	/bin/rm -rf $SDIR
-	if [ $es -gt 255 ] ; then
+	/bin/rm -rf "${SDIR}"
+	if [ ${es} -gt 255 ] ; then
 		es=255
 	fi
-	exit $es
+	exit ${es}
 }
 trap cleanup 0 2 3 13		# EXIT INT QUIT PIPE
 
@@ -45,7 +45,7 @@ while getopts xbM:em ch; do
 		xargs="-b"
 		;;
 	M)
-		metalog=${OPTARG}
+		metalog="${OPTARG}"
 		;;
 	e)
 		allowextra=true
@@ -68,12 +68,12 @@ USAGE
 done
 shift $((${OPTIND} - 1))
 
-if [ -n "$metalog" ]; then
-	case "$metalog" in
-	${DESTDIR}/*)
+if [ -n "${metalog}" ]; then
+	case "${metalog}" in
+	"${DESTDIR}"/*)
 		# Metalog would be noticed, so make sure it gets
 		# ignored.
-		metalog="./${metalog#${DESTDIR}/}"
+		metalog="./${metalog#"${DESTDIR}"/}"
 		;;
 	*)
 		metalog=""
@@ -81,28 +81,28 @@ if [ -n "$metalog" ]; then
 fi
 
 
-${HOST_SH} ./makeflist $xargs $dargs > $SDIR/flist
+${HOST_SH} ./makeflist ${xargs} ${dargs} > "${SDIR}/flist"
 
 (
-	cd $DESTDIR
-	${FIND} $origin \( -type d -o -type f -o -type l \) -print
+	cd "${DESTDIR}"
+	${FIND} ${origin} \( -type d -o -type f -o -type l \) -print
 ) | (
 	while read line; do
-		case "$line" in
-		$metalog)
+		case "${line}" in
+		"${metalog}")
 			;;
 		*)
-			echo $line
+			echo "${line}"
 			;;
 		esac
 	done
-) | ${SORT} > $SDIR/files
+) | ${SORT} > "${SDIR}/files"
 
-${COMM} -23 $SDIR/flist $SDIR/files > $SDIR/missing
-${COMM} -13 $SDIR/flist $SDIR/files > $SDIR/extra
+${COMM} -23 "${SDIR}/flist}" "${SDIR}/files}" > "${SDIR}/missing}"
+${COMM} -13 "${SDIR}/flist}" "${SDIR}/files}" > "${SDIR}/extra}"
 
-if [ -s $SDIR/extra ]; then
-	count=$(${AWK} 'END {print NR}' $SDIR/extra)
+if [ -s "${SDIR}/extra" ]; then
+	count="$(${AWK} 'END {print NR}' "${SDIR}/extra")"
 	echo ""
 	echo "============  ${count} extra files  ==============="
 	echo "Files in DESTDIR but missing from flist."
@@ -113,13 +113,13 @@ if [ -s $SDIR/extra ]; then
 		es=1
 	fi
 	echo "------------------------------------------"
-	cat $SDIR/extra
+	cat "${SDIR}/extra"
 	echo "=========  end of ${count} extra files  ==========="
 	echo ""
 fi
 
-if [ -s $SDIR/missing ]; then
-	count=$(${AWK} 'END {print NR}' $SDIR/missing)
+if [ -s "${SDIR}/missing" ]; then
+	count="$(${AWK} 'END {print NR}' "${SDIR}/missing")"
 	echo ""
 	echo "===========  ${count} missing files  =============="
 	echo "Files in flist but missing from DESTDIR."
@@ -130,9 +130,9 @@ if [ -s $SDIR/missing ]; then
 		es=1
 	fi
 	echo "------------------------------------------"
-	cat $SDIR/missing
+	cat "${SDIR}/missing"
 	echo "========  end of ${count} missing files  =========="
 	echo ""
 fi
 
-exit 0		# cleanup will exit with $es
+exit 0		# cleanup will exit with ${es}
