Clearly the error message was supposed to print $metalog, not $METALOG.

diff --git a/distrib/sets/maketars b/distrib/sets/maketars
--- a/distrib/sets/maketars
+++ b/distrib/sets/maketars
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: maketars,v 1.51 2004/02/06 11:38:57 lukem Exp $
+# $NetBSD: maketars,v 1.52 2004/02/19 02:54:51 dyoung Exp $
 #
 # Make release tar files for some or all lists.  Usage:
 # maketars [-b] [-x] [-i installdir] [-a arch] [-m machine] [-s setsdir]
@@ -139,7 +139,7 @@ if [ -n "$metalog" ]; then
 	) | ${MTREE} -C -k all -N ${etcdir} > $SDIR/metalog
 	rv=$?
 	if [ $rv -ne 0 ]; then
-		echo 1>&2 "${prog}: mtree parse of ${METALOG} failed"
+		echo 1>&2 "${prog}: mtree parse of ${metalog} failed"
 		exit $rv
 	fi
 fi
