Apply patch (requested by jmc in ticket #5912): Allow autobuild to create source sets with builds.

diff --git a/distrib/sets/makesrctars b/distrib/sets/makesrctars
--- a/distrib/sets/makesrctars
+++ b/distrib/sets/makesrctars
@@ -1,71 +1,130 @@
 #! /bin/sh
 #
-#	$NetBSD: makesrctars,v 1.14 2002/04/12 07:08:37 lukem Exp $
+#	$NetBSD: makesrctars,v 1.14.2.1 2005/10/21 17:49:23 riz Exp $
 #
-# Make source code tarballs.
+# makesrctars srcdir setdir
+#	Create source tarballs in setdir from the source under srcdir.
+#
 
-: ${CKSUM=cksum}
+prog=${0##*/}
+
+# set defaults
+: ${CKSUM:=cksum}
+: ${MTREE:=/usr/sbin/mtree}
+: ${PAX:=pax}
+
+xsrcdir=
 
 GZIP=-9
 export GZIP
 
-if [ -z "$SRCDIR" ]; then
-	echo SRCDIR must be set
+usage()
+{
+	cat 1>&2 <<USAGE
+Usage: ${prog} [-N password/group dir] [-x xsrcdir] srcdir setdir
+	-N dir		location which contains master.passwd and group files
+			(defaults to \${srcdir}/etc)
+	-x xsrcdir	build xsrc.tgz from xsrcdir
+	srcdir		location of sources
+	setdir		where to write the .tgz files to
+USAGE
+	exit 1
+}
+
+# handle args
+while getopts N:x: ch; do
+	case ${ch} in
+	x)
+		xsrcdir=${OPTARG}
+		;;
+	N)
+		PASSWD=${OPTARG}
+		;;
+	*)
+		usage
+		;;
+	esac
+done
+shift $((${OPTIND} - 1))
+
+if [ $# -ne 2 ]; then
+	usage
+fi
+srcdir=$1
+setdir=$2
+: ${PASSWD:=${srcdir}/etc}
+
+if [ ! -d "${setdir}" ]; then
+	echo "${setdir} is not a directory"
 	exit 1
 fi
 
-if [ -z "$DESTDIR" ]; then
-	echo DESTDIR must be set
+makeset()
+{(
+	set=$1.tgz
+	shift
+	dir=$1
+	shift
+	echo "Creating ${set}"
+	if [ "${dir}" != "." ]; then
+		cd $dir
+		srcprefix="${srcprefix}/${dir}"
+	fi
+	# Gets rid of any obj dirs and things below it 
+	echo "obj" > /tmp/in$$
+	egrep=$*
+	if [ "$egrep" = "" ]; then
+		egrep='.'
+	fi
+	set -f
+	${MTREE} -c -X /tmp/in$$ | ${MTREE} -C -k type | \
+		egrep -v 'type=link' | egrep $egrep | \
+		sed -e 's:type=file:& mode=0664:' \
+			-e 's:type=dir:& mode=0775:' \
+			-e 's:$: uname=root gname=wsrc:' | \
+		${PAX} -M -N ${PASSWD} -w -d -s'|^\.|'${srcprefix}'|' | \
+		gzip > "${setdir}/${set}"
+	rm -f /tmp/in$$
+)}
+
+
+# create (base)src sets
+#
+
+if ! cd "${srcdir}"; then
+	echo "Can't chdir to ${srcdir}"
 	exit 1
 fi
 
-if [ -d ${DESTDIR} ]; then
-	echo "DESTDIR exists."
-#	exit 1
+srcprefix=usr/src
+export setdir MTREE PAX CKSUM GZIP PASSWD srcprefix
+
+makeset src . -v '^\.\/gnu|^\.\/share|^\.\/sys|^\.\/usr\.sbin\/config'
+
+makeset gnusrc gnu
+
+makeset syssrc . -e '^\..type=dir|^\.\/sys|^\.\/usr\.sbin.type=dir|^\.\/usr\.sbin\/config'
+
+makeset sharesrc share
+
+
+# create xsrc sets
+#
+if [ -n "${xsrcdir}" ]; then
+	if ! cd "${xsrcdir}"; then
+		echo "Can't chdir to ${xsrcdir}"
+		exit 1
+	fi
+	srcprefix=usr/xsrc
+	makeset xsrc .
 fi
 
-cd $SRCDIR
 
-mkdir ${DESTDIR}
-
-mkdir ${DESTDIR}/sets
-
-find -s . \
-    \! \( \( -path ./gnu -o -path ./share \) -prune \) \
-    \! \( -path ./sys -prune \) \
-    \! \( -path ./usr.sbin/config -prune \) \
-    \! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	pax -w -d -s'|^\.|usr/src|' | gzip \
-	> ${DESTDIR}/sets/src.tgz
-
-find -s gnu \
-    \! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	pax -w -d -s'|^|usr/src/|' | gzip \
-	> ${DESTDIR}/sets/gnusrc.tgz
-
-find -s sys usr.sbin/config \
-    \( \
-	-path 'sys/arch/*/compile/CVS' -o \
-	-name .keep_me -o \
-	! \( -path 'sys/arch/*/compile/*' -prune \) \
-    \) \
-    ! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	pax -w -d -s'|^|usr/src/|' | gzip \
-	> ${DESTDIR}/sets/syssrc.tgz
-
-find -s share \
-    \! \( \( -type l -o -type d \) \( -name obj -o -name 'obj.*' \) \) \
-	-print | \
-	pax -w -d -s'|^|usr/src/|' | gzip \
-	> ${DESTDIR}/sets/sharesrc.tgz
-
-(cd ${DESTDIR}/sets
+echo "Creating checksum files"
+(cd ${setdir}
 	${CKSUM} -o1 *.tgz > BSDSUM
 	${CKSUM}     *.tgz > CKSUM
 	${CKSUM} -m  *.tgz > MD5
 	${CKSUM} -o2 *.tgz > SYSVSUM
 )
-chmod 444 ${DESTDIR}/sets/*
+exit 0
