When printing messages to stderr, always use echo >&2 "${prog}: ..."
Approved by christos

diff --git a/distrib/sets/regpkg b/distrib/sets/regpkg
--- a/distrib/sets/regpkg
+++ b/distrib/sets/regpkg
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# $NetBSD: regpkg,v 1.9 2006/01/04 14:14:35 apb Exp $
+# $NetBSD: regpkg,v 1.10 2006/01/08 10:10:03 apb Exp $
 #
 # Copyright (c) 2003 Alistair G. Crooks.  All rights reserved.
 #
@@ -93,7 +93,7 @@ ERRWARNNOTE="${ERROR}"	# may be changed by "-u" (update) command line flag
 #
 SCRATCH="$( ${MKTEMP} -d "/var/tmp/${0##*/}.XXXXXX" )"
 if [ $? -ne 0 -o \! -d "${SCRATCH}" ]; then
-	echo >&2 "Could not create scratch directory."
+	echo >&2 "${prog}: Could not create scratch directory."
 	bomb
 fi
 
@@ -605,7 +605,7 @@ EOF
 	# "@name" line and a lot of "@comment MD5:" lines.
 	#
 	{
-		rcsid='$NetBSD: regpkg,v 1.9 2006/01/04 14:14:35 apb Exp $'
+		rcsid='$NetBSD: regpkg,v 1.10 2006/01/08 10:10:03 apb Exp $'
 		utcdate="$( ${ENV_CMD} TZ=UTC LOCALE=C \
 			${DATE} '+%Y-%m-%d %H:%M' )"
 		user="${USER:-root}"
diff --git a/distrib/sets/syspkgdeps b/distrib/sets/syspkgdeps
--- a/distrib/sets/syspkgdeps
+++ b/distrib/sets/syspkgdeps
@@ -65,14 +65,17 @@ esac
 # TBD clean up
 SCRATCH="$(${MKTEMP} -d "/var/tmp/${prog}.XXXXXX")"
 
-[ $? -ne 0 ] && { echo "Could not create scratch directory." 1>&2 ; exit 1 ; }
+if [ $? -ne 0 ]; then
+	echo >&2 "${prog}: Could not create scratch directory."
+	exit 1
+fi
 
 PATH_MEMBERSHIP="${SCRATCH}/path-membership"
 PATH_TO_PKGNAME="${SCRATCH}/pathpkg.db"
 PARENT_PKGNAMES="${SCRATCH}/parent-pkgnames"
 PARENT_PATHNAMES="${SCRATCH}/parent-pathnames"
 
-echo "indexing packages by pathnames" 1>&2
+echo >&2 "${prog}: indexing packages by pathnames"
 
 list_set_files ${sets} | ${SED} 's/^\.\///' | \
 ${ENV_CMD} PREFIX="${prefix}" ${AWK} '{
@@ -83,10 +86,14 @@ ${ENV_CMD} PREFIX="${prefix}" ${AWK} '{
 	}
 }' | ${SORT} -k 1 -u > "${PATH_MEMBERSHIP}"
 
-${DB} -q -w -f - btree "${PATH_TO_PKGNAME}" < "${PATH_MEMBERSHIP}" || \
-	echo "shit" 1>&2
+${DB} -q -w -f - btree "${PATH_TO_PKGNAME}" < "${PATH_MEMBERSHIP}"
 
-echo "computing parent pathnames" 1>&2
+if [ $? -ne 0 ]; then
+	echo >&2 "${prog}: error creating database, aborting"
+	exit 1
+fi
+
+echo >&2 "${prog}: computing parent pathnames"
 
 while read pathname pkgname; do
 	# print parent pathname.
@@ -94,7 +101,7 @@ while read pathname pkgname; do
 	dirname "${pathname}"
 done < "${PATH_MEMBERSHIP}" > "${PARENT_PATHNAMES}"
 
-echo "selecting parent packages using parent pathnames" 1>&2
+echo >&2 "${prog}: selecting parent packages using parent pathnames"
 
 ${DB} -q -f - btree "${PATH_TO_PKGNAME}" < "${PARENT_PATHNAMES}" | \
 	${PASTE} "${PATH_MEMBERSHIP}" - | \
@@ -103,6 +110,6 @@ ${DB} -q -f - btree "${PATH_TO_PKGNAME}" < "${PARENT_PATHNAMES}" | \
 	${HOST_SH} "${rundir}/culldeps"
 
 if [ $? -ne 0 ]; then
-	echo "error in parent-directory lookup, aborting" 1>&2
+	echo >&2 "${prog}: error in parent-directory lookup, aborting"
 	exit 1
 fi
