Detect cyclic dependencies, and abort if any exist.
Approved by christos

diff --git a/distrib/sets/syspkgdeps b/distrib/sets/syspkgdeps
--- a/distrib/sets/syspkgdeps
+++ b/distrib/sets/syspkgdeps
@@ -109,10 +109,31 @@ echo >&2 "${prog}: selecting parent packages using parent pathnames"
 ${DB} -q -f - btree "${PATH_TO_PKGNAME}" < "${PARENT_PATHNAMES}" | \
 	${PASTE} "${PATH_MEMBERSHIP}" - | \
 	${AWK} '{ if ($2 != $4) print $2 " " $4; }' | \
-	${SORT} -u | \
-	${HOST_SH} "${rundir}/culldeps"
+	${SORT} -u > "${SCRATCH}/alldeps"
 
 if [ $? -ne 0 ]; then
 	echo >&2 "${prog}: error in parent-directory lookup, aborting"
+	exit 1
+fi
+
+echo "checking for cyclic dependencies" 1>&2
+
+tsort_errors="$( ${TSORT} < "${SCRATCH}/alldeps" 2>&1 >/dev/null )"
+
+if [ -n "${tsort_errors}" ]; then
+	# Errors from tsort are usually to do with cyclic dependencies.
+	# The most likely underlying cause is that /foo and /foo/bar/baz
+	# are in syspkg A, but /foo/bar is in syspkg B.
+	echo "${tsort_errors}" 1>&2
+	echo "Above messages probably indicate an error in the lists" 1>&2
+	exit 1
+fi
+
+echo "removing redundant dependencies" 1>&2
+
+${HOST_SH} "${rundir}/culldeps" < "${SCRATCH}/alldeps"
+
+if [ $? -ne 0 ]; then
+	echo "error in culldeps, aborting" 1>&2
 	exit 1
 fi
