Import IPFilter 4.1.1

diff --git a/dist/ipf/SunOS5/ipfboot b/dist/ipf/SunOS5/ipfboot
--- a/dist/ipf/SunOS5/ipfboot
+++ b/dist/ipf/SunOS5/ipfboot
@@ -1,17 +1,64 @@
 #!/bin/sh
 #
-PIDFILE=/etc/opt/ipf/ipmon.pid
+IPFBASE=/etc/opt/ipf
 
-id=`/usr/sbin/modinfo 2>&1 | awk '/ipf/ { print $1 } ' - 2>/dev/null`
-if [ -f $PIDFILE ] ; then
-	pid=`cat $PIDFILE 2>/dev/null`
+PATH=/bin:/sbin:/usr/sbin:${PATH}:/opt/ipf/bin
+IPFILCONF=${IPFBASE}/ipf.conf
+IP6FILCONF=${IPFBASE}/ipf6.conf
+IPNATCONF=${IPFBASE}/ipnat.conf
+IPPOOLCONF=${IPFBASE}/ippool.conf
+PFILCHECKED=no
+if [ -d /var/run ] ; then
+	PIDFILE=/var/run/ipmon.pid
 else
-	pid=`/bin/ps -e 2>&1 | awk '/ipmon/ { print $1 } ' - 2>/dev/null`
+	PIDFILE=${IPFBASE}/ipmon.pid
 fi
-PATH=${PATH}:/sbin:/opt/ipf/bin
-IPFILCONF=/etc/opt/ipf/ipf.conf
-IP6FILCONF=/etc/opt/ipf/ipf6.conf
-IPNATCONF=/etc/opt/ipf/ipnat.conf
+
+
+logmsg()
+{
+	logger -p local0.emerg -t ipfilter "$1"
+	echo "$1" >&2
+}
+
+
+checkpfil()
+{
+	if [ $PFILCHECKED = yes ] ; then
+		return
+	fi
+	if [ -z "`ndd /dev/pfil qif_status 2>/dev/null`" ] ; then
+		logmsg "pfil not available to support ipfilter"
+		exit 1
+	fi
+	if [ `uname -r|cut -d. -f2` -gt 7 ] ; then
+		realnic=`/sbin/ifconfig -a modlist 2>/dev/null | grep -c pfil`
+	else
+		for i in `ifconfig -a | cut -d: -f1 | egrep -v '[ 	]|^lo'`
+		do
+			if strconf -m pfil < /dev/$i >/dev/null 2>&1 ; then
+				realnic=1;
+				break;
+			fi
+		done
+	fi
+	if [ $realnic -eq 0 ] ; then
+		logmsg "pfil not configured for firewall/NAT operation"
+	fi
+	PFILCHECKED=yes
+}
+
+
+getids()
+{
+	id=`modinfo 2>&1 | awk '/ipf/ { print $1 } ' - 2>/dev/null`
+	if [ -f $PIDFILE ] ; then
+		pid=`cat $PIDFILE 2>/dev/null`
+	else
+		pid=`pgrep ipmon`
+	fi
+}
+
 
 block_default_workaround() {
 	ipf -F a
@@ -22,7 +69,7 @@ block_default_workaround() {
 		return
 	fi
 	for NS in $NAMESERVERS ; do
-		IF_TO_NS=`/usr/sbin/route -n get $NS  2>/dev/null| \
+		IF_TO_NS=`route -n get $NS  2>/dev/null| \
 			  nawk '$1 == "interface:" { print $NF ; exit }' \
 			  2>/dev/null`
 		if [ -z "$IF_TO_NS" ] ; then
@@ -42,7 +89,8 @@ block_default_workaround() {
 load_ipf_config() {
 	bad=0
 	if [ -r ${IPFILCONF} ]; then
-		if `/sbin/ipf -V | \
+		checkpfil
+		if `ipf -V | \
 		      nawk '$1 == "Default:" && $2 == "pass" { exit 1 }'` ; then
 			block_default_workaround
 		fi
@@ -53,6 +101,7 @@ load_ipf_config() {
 		fi
 	fi
 	if [ -r ${IP6FILCONF} ]; then
+		checkpfil
 		ipf -6IFa -f ${IP6FILCONF}
 		if [ $? != 0 ]; then
 			echo "$0: load of ${IPFILCONF} into alternate set failed"
@@ -69,6 +118,7 @@ load_ipf_config() {
 
 load_ipnat_config() {
 	if [ -r ${IPNATCONF} ]; then
+		checkpfil
 		ipnat -CF -f ${IPNATCONF}
 		if [ $? != 0 ]; then
 			echo "$0: load of ${IPNATCONF} failed"
@@ -79,30 +129,65 @@ load_ipnat_config() {
 }
 
 
+load_ippool_config() {
+	if [ -r ${IPPOOLCONF} ]; then
+		checkpfil
+		ippool -F
+		ippool -f ${IPPOOLCONF}
+		if [ $? != 0 ]; then
+			echo "$0: load of ${IPPOOLCONF} failed"
+		fi
+	fi
+}
+
+
 case "$1" in
 	start)
-		if [ x"$pid" != x ] ; then
-			kill -TERM $pid 2>/dev/null
-		fi
-		if [ x$id != x ] ; then
-			modunload -i $id 2>/dev/null
-		fi
+		getids
+		[ -n "$pid" ] && kill -TERM $pid 2>/dev/null
+		[ -n "$id" ] && modunload -i $id 2>/dev/null
 		modload /usr/kernel/drv/ipf
+		load_ippool_config
 		load_ipf_config
 		load_ipnat_config
 		ipmon -Ds
 		;;
 
 	stop)
-		if [ x"$pid" != x ] ; then
-			kill -TERM $pid
-		fi
-		if [ x$id != x ] ; then
-			modunload -i $id
+		getids
+		[ -n "$pid" ] && kill -TERM $pid
+		/bin/rm -f $PIDFILE
+		[ -n "$id" ] && modunload -i $id
+		;;
+
+	pause)
+		getids
+		ipfs -l
+		ipfs -NS -w
+		ipf -D
+		if [ -f $PIDFILE ] ; then
+			if kill -0 $pid; then
+				kill -TERM $pid
+			else    
+				cp /dev/null $PIDFILE
+			fi
+		fi      
+		;;
+
+	resume)
+		getids
+		ipf -E
+		ipfs -R
+		load_ippool_config
+		load_ipf_config
+		load_ipnat_config
+		if [ -f $PIDFILE -a x$pid != x ] ; then
+			ipmon -Ds
 		fi
 		;;
 
 	reload)
+		load_ippool_config
 		load_ipf_config
 		load_ipnat_config
 		;;
@@ -110,11 +195,13 @@ case "$1" in
 	reipf)
 		load_ipf_config
 		;;
+
 	reipnat)
 		load_ipnat_config
 		;;
+
 	*)
-		echo "Usage: $0 (start|stop|reload|reipf|reipnat)" >&2
+		echo "Usage: $0 (start|stop|reload|reipf|reipnat|pause|resume)" >&2
 		exit 1
 		;;
 
