punctuation

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,5 +1,5 @@
 #	@(#)rc	5.27 (Berkeley) 6/5/91
-#	$Id: rc,v 1.37 1994/03/17 23:22:40 cgd Exp $
+#	$Id: rc,v 1.38 1994/03/18 00:58:20 cgd Exp $
 
 # System startup script run by init on autoboot
 # or after single-user.
@@ -19,10 +19,10 @@ export PATH
 
 if [ -e /fastboot ]
 then
-	echo "Fast boot; skipping disk checks."
+	echo "Fast boot: skipping disk checks."
 elif [ $1x = autobootx ]
 then
-	echo "Automatic boot in progress..."
+	echo "Automatic boot in progress: starting file system checks."
 	fsck -p
 	case $? in
 	0)
@@ -33,15 +33,15 @@ then
 	4)
 		echo "Rebooting..."
 		reboot
-		echo "reboot failed... help!"
+		echo "Reboot failed; help!"
 		exit 1
 		;;
 	8)
-		echo "Automatic file system check failed... help!"
+		echo "Automatic file system check failed; help!"
 		exit 1
 		;;
 	12)
-		echo "Boot interrupted"
+		echo "Boot interrupted."
 		exit 1
 		;;
 	130)
@@ -49,13 +49,13 @@ then
 		exit 1
 		;;
 	*)
-		echo "Unknown error in reboot"
+		echo "Unknown error; help!"
 		exit 1
 		;;
 	esac
 fi
 
-trap "echo 'Boot interrupted'; exit 1" 3
+trap "echo 'Boot interrupted.'; exit 1" 3
 
 swapon -a
 
