Split rc.conf variables for starting programs into two: an on/off switch and a set of flags. Get rid of DEFAULT flags entirely. Print warnings if on/off switches are not set, or are set incorrectly. Add a shell function to simplify this on/off switch testing.

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,4 +1,4 @@
-#	$NetBSD: rc,v 1.88 1997/08/26 19:35:33 thorpej Exp $
+#	$NetBSD: rc,v 1.89 1997/08/29 02:24:05 cjs Exp $
 #	originally from: @(#)rc	8.2 (Berkeley) 3/17/94
 
 # System startup script run by init on autoboot
@@ -67,8 +67,20 @@ umount -a >/dev/null 2>&1
 mount /
 rm -f /fastboot		# XXX (root now writeable)
 
+if [ -f /etc/rc.func ]; then
+	. /etc/rc.func
+else
+	echo "Can't read /etc/rc.func; aborting."
+	exit 1;
+fi
+
 if [ -f /etc/rc.conf ]; then
 	. /etc/rc.conf
+fi
+
+if [ "$rc_configured" != YES ]; then
+	echo "/etc/rc.conf is not configured. Multiuser boot aborted."
+	exit 1
 fi
 
 # set flags on ttys.  (do early, in case they use tty for SLIP in netstart)
@@ -110,10 +122,7 @@ rm -f /var/spool/uucp/STST/*
 # are logged, then start savecore to get a dump on low memory systems
 # and then start the name server.
 
-if [ "$syslogd_flags" != NO ]; then
-	if [ "$syslogd_flags" = DEFAULT ]; then
-		syslogd_flags=""
-	fi
+if checkyesno syslogd; then
 	echo 'starting system logger'
 	rm -f /dev/log
 	syslogd $syslogd_flags
@@ -121,63 +130,70 @@ fi
 
 # /var/crash should be a directory or a symbolic link
 # to the crash directory if core dumps are to be saved.
-if [ "$savecore_flags" != NO ] && [ -d /var/crash ]; then
-	if [ "$savecore_flags" = DEFAULT ]; then
-		savecore_flags=""
+if checkyesno savecore; then
+	if [ -d /var/crash ]; then
+		echo checking for core dump...
+		savecore $savecore_flags /var/crash
+	else
+		logger -s "WARNING: no /var/crash directory; savecore not run."
 	fi
-	echo checking for core dump...
-	savecore $savecore_flags /var/crash
 fi
 
-if [ "$named_flags" != NO ]; then
-	if [ "$named_flags" = DEFAULT ]; then
-		named_flags=""
-	fi
+if checkyesno named; then
 	echo 'starting name server';	named $named_flags
+fi
+
+# set time, if requested
+if checkyesno ntpdate; then
+	if [ "$ntpdate_hosts" = DEFAULT ]; then
+		ntpdate_hosts=`awk '/^server/ {print $2}' </etc/ntp.conf`
+	fi
+	if [ -n "$ntpdate_hosts"  ]; then
+		echo 'Setting date via ntp.'
+		ntpdate -b $ntpdate_hosts
+	fi
 fi
 
 # now start the rpc servers, for YP server/client.
 echo -n 'starting rpc daemons:'
 
 # note that portmap is generally required for all other rpc services.
-if [ "$portmap" != NO ]; then
+if checkyesno portmap; then
 	echo -n ' portmap';             portmap
 fi
 
-if [ "$ypserv_flags" != NO ]; then
-	if [ "$ypserv_flags" = DEFAULT ]; then
-		ypserv_flags="-d"
-	fi
+if checkyesno ypserv; then
         echo -n ' ypserv';              ypserv $ypserv_flags
 fi
 
-if [ "$ypbind_flags" != NO ]; then
-	if [ "$ypbind_flags" = DEFAULT ]; then
-		ypbind_flags=""
-	fi
+if checkyesno ypbind; then
         echo -n ' ypbind';              ypbind $ypbind_flags
 fi
 
-if [ "$yppasswdd_flags" != NO ]; then
-	if [ "$yppasswdd_flags" = DEFAULT ]; then
-		yppasswdd_flags=""
-	fi
+if checkyesno yppasswdd; then
         echo -n ' rpc.yppasswdd';       rpc.yppasswdd $yppasswdd_flags
 fi
 
-if [ "$bootparamd_flags" != NO ] && [ -r /etc/bootparams ]; then
-	if [ "$bootparamd_flags" = DEFAULT ]; then
-		bootparamd_flags=""
+if checkyesno bootparamd; then
+	if [ -r /etc/bootparams ]; then
+		echo -n ' rpc.bootparamd'; rpc.bootparamd $bootparamd_flags
+	else
+		echo
+		logger -s "WARNING: /etc/bootparams not found. " \
+		    "bootparamd not started."
 	fi
-        echo -n ' rpc.bootparamd';      rpc.bootparamd $bootparamd_flags
 fi
 
 echo '.'
 
 # load kernel modules specified in /etc/lkm.conf
-if [ "$lkm_init" != NO ] && [ -f /etc/rc.lkm ]; then
-	lkmstage=BEFOREMOUNT
-	. /etc/rc.lkm
+if checkyesno lkm; then
+	if [ -r /etc/rc.lkm ]; then
+		lkmstage=BEFOREMOUNT
+		. /etc/rc.lkm
+	else
+		logger -s "WARNING: /etc/rc.lkm not found; LKMs not loaded."
+	fi
 fi
 
 mount -a
@@ -187,50 +203,50 @@ echo -n 'starting nfs-rpc daemons:'
 
 nfs_locking=NO
 
-if [ "$nfs_server" = YES ] && [ -r /etc/exports ]; then
-	if [ "$mountd_flags" = DEFAULT ]; then
-		mountd_flags=""
+if checkyesno nfs_server; then
+	if [ -r /etc/exports ]; then
+		rm -f /var/db/mountdtab
+		echo -n > /var/db/mountdtab
+		echo -n ' mountd';              mountd $mountd_flags
+		echo -n ' nfsd';                nfsd $nfsd_flags
+		nfs_locking=MAYBE
+	else
+		echo
+		logger -s "WARNING: /etc/exports not readable; " \
+		    "NFS server not started."
 	fi
-        rm -f /var/db/mountdtab
-        echo -n > /var/db/mountdtab
-        echo -n ' mountd';              mountd $mountd_flags
-	if [ "$nfsd_flags" = DEFAULT ]; then
-		nfsd_flags="-tun 4"
-	fi
-        echo -n ' nfsd';                nfsd $nfsd_flags
-	nfs_locking=MAYBE
 fi
 
-if [ "$nfs_client" = YES ]; then
-	if [ "$nfsiod_flags" = DEFAULT ]; then
-		nfsiod_flags="-n 4"
-	fi
+if checkyesno nfs_client; then
         echo -n ' nfsiod';              nfsiod $nfsiod_flags
 	nfs_locking=MAYBE
 fi
 
 if [ "$nfs_locking" != NO ]; then
-	if [ "$statd_flags" != NO ]; then
-		if [ "$statd_flags" = DEFAULT ]; then
-			statd_flags=""
-		fi
+	if checkyesno statd; then
 		echo -n ' rpc.statd';		rpc.statd $statd_flags
 	fi
-
-	if [ "$lockd_flags" != NO ]; then
-		if [ "$lockd_flags" = DEFAULT ]; then
-			lockd_flags=""
-		fi
+	if checkyesno lockd; then
 		echo -n ' rpc.lockd';		rpc.lockd $lockd_flags
 	fi
 fi
 
-if [ "$amd_flags" != NO ] && [ -d "$amd_dir" -a -r "$amd_master" ]; then
-	if [ "$amd_flags" = DEFAULT ]; then
-		amd_flags="-l syslog -x error,noinfo,nostats"
+if checkyesno amd; then
+	if [ -d "$amd_dir" ]; then
+		if [ -r "$amd_master" ]; then
+			echo -n ' amd'
+			amd $amd_flags -p -a $amd_dir `cat $amd_master` \
+			    > /var/run/amd.pid
+		else
+			echo
+			logger -s "WARNING: \$amd_master ($amd_master)not " \
+			    "readable; amd not started."
+		fi
+	else
+		echo
+		logger -s "WARNING: \$amd_dir ($amd_dir) not a directory; " \
+		    "amd not started."
 	fi
-        echo -n ' amd'
-        amd $amd_flags -p -a $amd_dir `cat $amd_master` > /var/run/amd.pid
 fi
 
 echo '.'
@@ -241,14 +257,12 @@ if [ -f /sbin/ldconfig ]; then
 fi 
 
 # load kernel modules specified in /etc/lkm.conf
-if [ "$lkm_init" != NO ] && [ -f /etc/rc.lkm ]; then
+if checkyesno lkm && [ -f /etc/rc.lkm ]; then
 	lkmstage=AFTERMOUNT
 	. /etc/rc.lkm
 fi
 
-				echo -n 'checking quotas:'
-quotacheck -a
-				echo ' done.'
+echo -n 'checking quotas:'; quotacheck -a; echo ' done.'
 quotaon -a
 
 # build ps databases
@@ -284,7 +298,7 @@ echo clearing /tmp
 # Update kernel info in /etc/motd
 # Must be done *before* interactive logins are possible to prevent
 # possible race conditions.
-if [ "$update_motd" != NO ]; then
+if checkyesno update_motd; then
 	echo 'updating motd.'
 	if [ ! -f /etc/motd ]; then
 		install -c -o root -g wheel -m 664 /dev/null /etc/motd
@@ -303,127 +317,117 @@ if [ -f /var/account/acct ]; then
 fi
 
 echo -n standard daemons:
-if [ "$update_flags" != NO ]; then
-	if [ "$update_flags" = DEFAULT ]; then
-		update_flags="30"
-	fi
+if checkyesno update; then
 	echo -n ' update';		update $update_flags
 fi
 echo -n ' cron';		cron
 echo '.'
 
-# set time, if requested
-if [ "$ntpdate_hosts" != NO ]; then
-	if [ "$ntpdate_hosts" = DEFAULT ]; then
-		ntpdate_hosts=`awk '/^server/ {print $2}' </etc/ntp.conf`
-	fi
-	if [ -n "$ntpdate_hosts"  ]; then
-		echo 'Setting date via ntp.'
-		ntpdate -b $ntpdate_hosts
-	fi
-fi
-
 # now start all the other daemons
 echo -n starting network daemons:
 
-if [ "$gated_flags" != NO ] && [ -r /etc/gated.conf ]; then
-	if [ "$gated_flags" = DEFAULT ]; then
-		gated_flags=""
+if checkyesno gated && checkyesno routed; then
+	echo
+	logger -s "WARNING: gated and routed both requested to be run: " \
+	    "running only gated."
+	routed=NO
+fi
+
+if checkyesno gated; then
+	if [ -r /etc/gated.conf ]; then
+		echo -n ' gated';		gated $gated_flags
+	else
+		logger -s "WARNING: no /etc/gated.conf; gated not started."
 	fi
-	echo -n ' gated';		gated $gated_flags
-elif [ "$routed_flags" != NO ]; then
-	if [ "$routed_flags" = DEFAULT ]; then
-		routed_flags="-q"
-	fi
+fi
+
+if checkyesno routed; then
 	echo -n ' routed';		routed $routed_flags
 fi
 
-if [ "$mrouted_flags" != NO ]; then
-	if [ "$mrouted_flags" = DEFAULT ]; then
-		mrouted_flags=""
-	fi
+if checkyesno mrouted; then
 	echo -n ' mrouted';		mrouted $mrouted_flags
 fi
 
-if [ "$timed_flags" != NO ]; then
-	if [ "$timed_flags" = DEFAULT ]; then
-		timed_flags=""
-	fi
+if checkyesno timed; then
 	echo -n ' timed'; 		timed $timed_flags
 fi
 
-if [ "$xntpd_flags" != NO ]; then
-	if [ "$xntpd_flags" = DEFAULT ]; then
-		xntpd_flags="-p /var/run/xntpd.pid"
-	fi
+if checkyesno xntpd; then
 	echo -n ' xntpd';		xntpd $xntpd_flags
 fi
 
-if [ "$dhcpd_flags" != NO ] && [ -r /etc/dhcpd.conf ]; then
-	if [ "$dhcpd_flags" = DEFAULT ]; then
-		dhcpd_flags=""
+if checkyesno dhcpd; then
+	if [ -r /etc/dhcpd.conf ]; then
+		echo -n ' dhcpd';		dhcpd $dhcpd_flags
+	else
+		echo
+		logger -s "WARNING: /etc/dhcpd.conf not readable; " \
+		    "dhcpd not started."
 	fi
-	echo -n ' dhcpd';		dhcpd $dhcpd_flags
 fi
 
-if [ "$rwhod" = YES ]; then
+if checkyesno rwhod; then
 	echo -n ' rwhod';		rwhod
 fi
 
-if [ "$lpd_flags" != NO ]; then
-	if [ "$lpd_flags" = DEFAULT ]; then
-		lpd_flags=""
-	fi
-	echo -n ' printer';		lpd $lpd_flags
+if checkyesno lpd; then
+	echo -n ' lpd';			lpd $lpd_flags
 fi
 
 # We call sendmail with a full path so that SIGHUP works.
-if [ "$sendmail_flags" != NO ] && [ -r /etc/sendmail.cf ]; then
-	if [ "$sendmail_flags" = DEFAULT ]; then
-		sendmail_flags="-bd -q30m"
+if checkyesno sendmail; then
+	if [ -r /etc/sendmail.cf ]; then
+		echo -n ' sendmail';	/usr/sbin/sendmail $sendmail_flags
+	else
+		echo
+		logger -s "WARNING: /etc/sendmail.cf not readable; " \
+		    "sendmail not started."
 	fi
-	echo -n ' sendmail';		/usr/sbin/sendmail $sendmail_flags
 fi
 
-if [ "$rarpd_flags" != NO ] && [ -r /etc/ethers ]; then
-	if [ "$rarpd_flags" = DEFAULT ]; then
-		rarpd_flags="-a"
+if checkyesno rarpd; then
+	if [ -r /etc/ethers ]; then
+		echo -n ' rarpd';	rarpd $rarpd_flags
+	else
+		echo
+		logger -s "WARNING: /etc/ethers not readable; " \
+		    "rarpd not started."
 	fi
-	echo -n ' rarpd';		rarpd $rarpd_flags
 fi
 
-if [ "$rbootd_flags" != NO ] && [ -r /etc/rbootd.conf ]; then
-	if [ "$rbootd_flags" = DEFAULT ]; then
-		rbootd_flags=""
+if checkyesno rbootd; then
+	if [ -r /etc/rbootd.conf ]; then
+		echo -n ' rbootd';	rbootd $rbootd_flags
+	else
+		echo
+		logger -s "WARNING: /etc/rbootd.conf not readable; " \
+		    "rarpd not started."
 	fi
-	echo -n ' rbootd';		rbootd $rbootd_flags
 fi
 
-if [ "$mopd_flags" != NO ]; then
-	if [ "$mopd_flags" = DEFAULT ]; then
-		mopd_flags="-a"
-	fi
+if checkyesno mopd; then
 	echo -n ' mopd';		mopd $mopd_flags
 fi
 
-if [ "$apmd_flags" != NO ]; then
-	if [ "$apmd_flags" = DEFAULT ]; then
-		apmd_flags=""
-	fi
+if checkyesno apmd; then
 	echo -n ' apmd';		apmd $apmd_flags
 fi
 
-if [ "$inetd_flags" != NO ] && [ -r /etc/inetd.conf ]; then
-	if [ "$inetd_flags" = DEFAULT ]; then
-		inetd_flags=""
+if checkyesno inetd; then
+	if [ -r /etc/inetd.conf ]; then
+		echo -n ' inetd';	inetd $inetd_flags
+	else
+		echo
+		logger -s "WARNING: /etc/inetd.conf not readable; " \
+		    "inetd not started."
 	fi
-	echo -n ' inetd';		inetd $inetd_flags
 fi
 
 echo '.'
 
 # Kerberos runs ONLY on the Kerberos server machine
-if [ "$kerberos_server" = YES ]; then
+if checkyesno kerberos; then
 	echo -n 'starting kerberos daemons:'
 	echo -n ' kerberos';	kerberos >> /var/log/kerberos.log &
 	echo -n ' kadmind';	kadmind -n >> /var/log/kadmind.log &
