include rc.subr and use appropriately

diff --git a/etc/security b/etc/security
--- a/etc/security
+++ b/etc/security
@@ -1,10 +1,17 @@
 #!/bin/sh -
 #
-#	$NetBSD: security,v 1.30 1997/10/08 16:13:44 mycroft Exp $
+#	$NetBSD: security,v 1.31 1998/01/26 12:02:55 lukem Exp $
 #	from: @(#)security	8.1 (Berkeley) 6/9/93
 #
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
+
+if [ -f /etc/rc.subr ]; then
+	. /etc/rc.subr
+else
+	echo "Can't read /etc/rc.subr; aborting."
+	exit 1;
+fi
 
 umask 077
 
@@ -40,7 +47,7 @@ awk -F: '{ print $1 " " $3 }' $MP | sort -k2n > $MPBYUID
 awk -F: '{ print $1 " " $9 }' $MP | sort -k2 > $MPBYPATH
 
 # Check the master password file syntax.
-if [ "$check_passwd" = YES ]; then
+if checkyesno check_passwd; then
 	awk '
 	BEGIN {
 		while ( getline < "/etc/shells" > 0 ) {
@@ -118,7 +125,7 @@ else
 fi
 
 # Check the group file syntax.
-if [ "$check_group" = YES ]; then
+if checkyesno check_group; then
 	GRP=/etc/group
 	awk -F: '{
 		if ($0 ~ /^[	 ]*$/) {
@@ -151,7 +158,7 @@ fi
 # The check for the root paths is problematical -- it's likely to fail
 # in other environments.  Once the shells have been modified to warn
 # of '.' in the path, the path tests should go away.
-if [ "$check_rootdotfiles" = YES ]; then
+if checkyesno check_rootdotfiles; then
 	> $OUTPUT
 	rhome=`csh -fc "echo ~root"`
 	umaskset=no
@@ -247,7 +254,7 @@ end-of-sh
 fi
 
 # Root and uucp should both be in /etc/ftpusers.
-if [ "$check_ftpusers" = YES ]; then
+if checkyesno check_ftpusers; then
 	> $OUTPUT
 	list="uucp "`awk '$2 == 0 { print $1 }' $MPBYUID`
 	for i in $list; do
@@ -262,14 +269,14 @@ if [ "$check_ftpusers" = YES ]; then
 fi
 
 # Uudecode should not be in the /etc/aliases file.
-if [ "$check_aliases" = YES ]; then
+if checkyesno check_aliases; then
 	if egrep '^[^#]*(uudecode|decode).*\|' /etc/aliases; then
 		printf "\nEntry for uudecode in /etc/aliases file.\n"
 	fi
 fi
 
 # Files that should not have + signs.
-if [ "$check_rhosts" = YES ]; then
+if checkyesno check_rhosts; then
 	list="/etc/hosts.equiv /etc/hosts.lpd"
 	for f in $list ; do
 		if [ -f $f ] && egrep '\+' $f > /dev/null ; then
@@ -308,7 +315,7 @@ fi
 
 # Check home directories.  Directories should not be owned by someone else
 # or writeable.
-if [ "$check_homes" = YES ]; then
+if checkyesno check_homes; then
 	while read uid homedir; do
 		if [ -d ${homedir}/ ] ; then
 			file=`ls -ldgT ${homedir}`
@@ -376,7 +383,7 @@ if [ "$check_homes" = YES ]; then
 fi
 
 # Mailboxes should be owned by user and unreadable.
-if [ "$check_varmail" = YES ]; then
+if checkyesno check_varmail; then
 	ls -l /var/mail | sed 1d | \
 	awk '$3 != $9 \
 		{ print "user " $9 " mailbox is owned by " $3 }
@@ -388,7 +395,7 @@ if [ "$check_varmail" = YES ]; then
 	fi
 fi
 
-if [ "$check_nfs" = YES ]; then
+if checkyesno check_nfs; then
 	if [ -f /etc/exports ]; then
 	    # File systems should not be globally exported.
 	    awk '{
@@ -416,7 +423,7 @@ if [ "$check_nfs" = YES ]; then
 fi
 
 # Display any changes in setuid files and devices.
-if [ "$check_devices" = YES ]; then
+if checkyesno check_devices; then
 	> $ERR
 	(find / \( ! -fstype local -o -fstype fdesc -o -fstype kernfs \
 			-o -fstype procfs \) -a -prune -o \
@@ -571,7 +578,7 @@ fi
 # the hacker can modify the tree specification to match the replaced binary.
 # For details on really protecting yourself against modified binaries, see
 # the mtree(8) manual page.
-if [ "$check_mtree" = YES ]; then
+if checkyesno check_mtree; then
 	mtree -e -p / -f /etc/mtree/special > $OUTPUT
 	if [ -s $OUTPUT ]; then
 		printf "\nChecking special files and directories.\n"
@@ -597,7 +604,7 @@ fi
 # List of files that get backed up and checked for any modifications.  Each
 # file is expected to have two backups, /var/backups/file.{current,backup}.
 # Any changes cause the files to rotate.
-if [ "$check_changelist" = YES ] && [ -s /etc/changelist ] ; then
+if checkyesno check_changelist && [ -s /etc/changelist ] ; then
 	for file in `egrep -v "^#|$MP" /etc/changelist`; do
 		CUR=/var/backups/`basename $file`.current
 		BACK=/var/backups/`basename $file`.backup
