sync with head

diff --git a/usr.sbin/postinstall/postinstall b/usr.sbin/postinstall/postinstall
--- a/usr.sbin/postinstall/postinstall
+++ b/usr.sbin/postinstall/postinstall
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: postinstall,v 1.126.2.1 2012/04/17 00:09:51 yamt Exp $
+# $NetBSD: postinstall,v 1.126.2.2 2012/10/30 19:00:49 yamt Exp $
 #
 # Copyright (c) 2002-2008 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -54,11 +54,11 @@
 # environment to override the locations of some tools.
 : ${AWK:=awk}
 : ${DB:=db}
-: ${EGREP:=egrep}
-: ${FGREP:=fgrep}
 : ${GREP:=grep}
+: ${HOST_SH:=sh}
 : ${MAKE:=make}
 : ${PWD_MKDB:=/usr/sbin/pwd_mkdb}
+: ${STAT:=stat}
 
 #
 #	helper functions
@@ -411,31 +411,6 @@ find_file_in_dirlist()
 	return 1
 }
 
-# stat op format target value
-#	Call stat(1) on the given target according to the given format,
-#	if stat(1) is available (it is presumed to live in /usr/bin).
-#	If it is not available, this routine will always succeed, otherwise
-#	it returns 0 or 1, depending on whether or not the output from
-#	stat(1) matches the expected value.
-#
-stat()
-{
-	_stop="$1"
-	_stfmt="$2"
-	_sttgt="$3"
-	_stval="$4"
-
-	if [ ! -x /usr/bin/stat ]; then
-		msg \
-    "(/usr/bin/stat not available; skipping ${_stop} on ${_sttgt})"
-		return 0
-	fi
-
-	_stres="$(/usr/bin/stat -q -f "${_stfmt}" "${_sttgt}")"
-	[ "${_stres}" = "${_stval}" ]
-	return $?
-}
-
 # file_exists_exact path
 #	Returns true if a file exists in the ${DEST_DIR} whose name
 #	is exactly ${path}, interpreted in a case-sensitive way
@@ -454,7 +429,7 @@ file_exists_exact()
 		_dirname="$(dirname "${_path}" 2>/dev/null)"
 		_basename="$(basename "${_path}" 2>/dev/null)"
 		ls -fa "${DEST_DIR}${_dirname}" 2> /dev/null \
-			| ${FGREP} -x "${_basename}" >/dev/null \
+			| ${GREP} -F -x "${_basename}" >/dev/null \
 			|| return 1
 		_path="${_dirname}"
 	done
@@ -880,7 +855,7 @@ do_gid()
 
 	check_ids "$1" groups "${DEST_DIR}/etc/group" \
 	    named ntpd sshd authpf _pflogd _rwhod _proxy _timedc \
-	    _sdpd _httpd _mdnsd _tests _tcpdump
+	    _sdpd _httpd _mdnsd _tests _tcpdump _tss
 }
 
 #
@@ -1183,7 +1158,7 @@ do_rc()
 		identd ifwatchd inetd ipfilter ipfs ipmon ipnat ipsec \
 		irdaattach iscsi_target isdnd isibootd \
 		kdc \
-		ldconfig local lpd lvm\
+		ldconfig ldpd local lpd lvm\
 		makemandb mdnsd mixerctl mopd motd mountall mountcritlocal \
 		mountcritremote mountd moused mrouted \
 		named ndbootd network newsyslog nfsd nfslocking npf \
@@ -1518,7 +1493,7 @@ ${pcpath} was a directory, should be a file.
 	# then it will not be deleted.
 	( [ -f "${DEST_DIR}"/var/db/obsolete/xbase ] \
 	    &&  sort -ru "${DEST_DIR}"/var/db/obsolete/xbase \
-	    | ${EGREP} "^\\.?${pcpath}/" ;
+	    | ${GREP} -E "^\\.?${pcpath}/" ;
 	    echo "${pcpath}" ) \
 	| obsolete_paths "${op}"
 	failed=$(( ${failed} + $? ))
@@ -1556,7 +1531,7 @@ do_uid()
 
 	check_ids "$1" users "${DEST_DIR}/etc/master.passwd" \
 	    named ntpd postfix sshd _pflogd _rwhod _proxy _timedc \
-	    _sdpd _httpd _mdnsd _tests _tcpdump
+	    _sdpd _httpd _mdnsd _tests _tcpdump _tss
 }
 
 
@@ -1750,6 +1725,91 @@ do_obsolete()
 
 
 #
+#	ptyfsoldnodes
+#
+additem ptyfsoldnodes "remove legacy device nodes when using ptyfs"
+do_ptyfsoldnodes()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_ptyfsoldnodes  fix|check"
+	_ptyfs_op="$1"
+
+	# Check whether ptyfs is in use
+	failed=0;
+	if ! ${GREP} -E "^ptyfs" "${DEST_DIR}/etc/fstab" > /dev/null; then
+		msg "ptyfs is not in use"
+		return 0
+	fi
+
+	# Find the device major numbers for the pty master and slave
+	# devices, by parsing the output from "MAKEDEV -s pty0".
+	#
+	# Output from MAKEDEV looks like this:
+	# ./ttyp0 type=char device=netbsd,5,0 mode=666 gid=0 uid=0
+	# ./ptyp0 type=char device=netbsd,6,0 mode=666 gid=0 uid=0
+	#
+	# Output from awk, used in the eval statement, looks like this:
+	# maj_ptym=6; maj_ptys=5;
+	#
+	eval "$(
+	    ${HOST_SH} "${DEST_DIR}/dev/MAKEDEV" -s pty0 2>/dev/null \
+	    | ${AWK} '\
+	    BEGIN { before_re = ".*device=[a-zA-Z]*,"; after_re = ",.*"; }
+	    /ptyp0/ { maj_ptym = gensub(before_re, "", 1, $0);
+		      maj_ptym = gensub(after_re, "", 1, maj_ptym); }
+	    /ttyp0/ { maj_ptys = gensub(before_re, "", 1, $0);
+		      maj_ptys = gensub(after_re, "", 1, maj_ptys); }
+	    END { print "maj_ptym=" maj_ptym "; maj_ptys=" maj_ptys ";"; }
+	    '
+	    )"
+	#msg "Major numbers are maj_ptym=${maj_ptym} maj_ptys=${maj_ptys}"
+	if [ -z "$maj_ptym" ] || [ -z "$maj_ptys" ]; then
+		msg "Cannot find device major numbers for pty master and slave"
+		return 1
+	fi
+
+	# look for /dev/[pt]ty[p-zP-T][0-9a-zA-Z], and check that they
+	# have the expected device major numbers.  ttyv* is typically not a
+	# pty device, but we check it anyway.
+	#
+	# The "for d1" loop is intended to avoid overflowing ARG_MAX;
+	# otherwise we could have used a single glob pattern.
+	#
+	# If there are no files that match a particular pattern,
+	# then stat prints something like:
+	#    stat: /dev/[pt]tyx?: lstat: No such file or directory
+	# and we ignore it.  XXX: We also ignore other error messages.
+	#
+	_ptyfs_tmp="$(mktemp /tmp/postinstall.ptyfs.XXXXXXXX)"
+	for d1 in p q r s t u v w x y z P Q R S T; do
+		${STAT} -f "%Hr %N" "${DEST_DIR}/dev/"[pt]ty${d1}? 2>&1
+	done \
+	| while read -r major node ; do
+		case "$major" in
+		${maj_ptym}|${maj_ptys}) echo "$node" ;;
+		esac
+	done >"${_ptyfs_tmp}"
+
+	_desc="legacy device node"
+	while read node; do
+		if [ "${_ptyfs_op}" = "check" ]; then
+			msg "Remove ${_desc} ${node}"
+			failed=1
+		else # "fix"
+			if rm "${node}"; then
+				msg "Removed ${_desc} ${node}"
+			else
+				warn "Failed to remove ${_desc} ${node}"
+				failed=1
+			fi
+		fi
+	done < "${_ptyfs_tmp}"
+	rm "${_ptyfs_tmp}"
+
+	return ${failed}
+}
+
+
+#
 #	end of items
 #	------------
 #
@@ -1848,19 +1908,6 @@ main()
 				if [ -f "${OPTARG}/etc/Makefile" ]; then
 					SOURCEMODE=true
 				fi
-			elif [ -f "${OPTARG%%:*}" -a -f "${OPTARG##*:}" \
-			       -a ! -f "${OPTARG}" ]
-			then
-				# Backward compatibility: allow arg to refer
-				# to a colon-separated list of tgz files.
-				# Remove this after NetBSD-5.0 is released.
-				cat >&2 <<EOF
-*** WARNING: The "-s tgzfile1:tgzfile2" option is deprecated.  Please use
-             "-s tgzfile1 -s tgzfile2" in future.
-EOF
-				TGZMODE=true
-				TGZLIST="${TGZLIST}${TGZLIST:+ }$( \
-					IFS=: eval shell_quote \${OPTARG} )"
 			else
 				err 2 "Invalid argument for -s option"
 			fi
@@ -2022,7 +2069,7 @@ EOF
 			[ "$MACHINE" = "$(uname -m)" ] && m= || m=" -m $MACHINE"
 			cat <<_Fix_me_
 To fix, run:
-    ${0} ${SRC_ARGLIST} -d ${DEST_DIR:-/}$m fix${items_failed}
+    ${HOST_SH} ${0} ${SRC_ARGLIST} -d ${DEST_DIR:-/}$m fix${items_failed}
 Note that this may overwrite local changes.
 _Fix_me_
 		    fi
