Import dhcpcd-7.2.3 with the following changes:   *  BSD: Check RTM lengths incase of kernel issues   *  DHCP6: Don't stop even when last router goes away   *  DHCP6: Fix inform from RA   *  hostname: Fix short hostname check

diff --git a/external/bsd/dhcpcd/dist/configure b/external/bsd/dhcpcd/dist/configure
--- a/external/bsd/dhcpcd/dist/configure
+++ b/external/bsd/dhcpcd/dist/configure
@@ -1368,7 +1368,7 @@ EOF
 elif [ "$DEV" != no -a "$UDEV" != no ]; then
 	echo "no"
 	if [ -n "$UDEV" ]; then
-		echo "udev has been explicity requested ... aborting" >&2
+		echo "udev has been explicitly requested ... aborting" >&2
 		exit 1
 	fi
 fi
