Import dhcpcd-7.1.0 with the following changes:
* NetBSD: sets SO_RERROR on to detect receive socket overflow
* BSD: route improvements to avoid listening for own changes
* IP6: implement IP6 address sharing
* BSD: catch UP/DOWN events when interfaces does support media changes
* IPv4LL: remember old address when carrier is lost

diff --git a/external/bsd/dhcpcd/dist/configure b/external/bsd/dhcpcd/dist/configure
--- a/external/bsd/dhcpcd/dist/configure
+++ b/external/bsd/dhcpcd/dist/configure
@@ -91,6 +91,7 @@ for x do
 	--without-sha256) SHA2=no;;
 	--without-hmac) HMAC=no;;
 	--without-dev) DEV=no;;
+	--with-udev) DEV=yes; UDEV=yes;;
 	--without-udev) UDEV=no;;
 	--with-poll) POLL="$var";;
 	--serviceexists) SERVICEEXISTS=$var;;
@@ -98,7 +99,7 @@ for x do
 	--servicestatus) SERVICESTATUS=$var;;
 	--small) SMALL=yes;;
 	--statusarg) STATUSARG=$var;;
-	--infodir|--includedir) ;; # ignore autotools
+	--infodir) ;; # ignore autotools
 	--disable-maintainer-mode|--disable-dependency-tracking) ;;
 	--disable-silent-rules) ;;
 	-V|--version)
@@ -1344,6 +1345,10 @@ EOF
 	rm -f _udev.c _udev
 elif [ "$DEV" != no -a "$UDEV" != no ]; then
 	echo "no"
+	if [ -n "$UDEV" ]; then
+		echo "udev has been explicity requested ... aborting" >&2
+		exit 1
+	fi
 fi
 
 if [ "$DEV" = yes ]; then
