sync with head.
for a reference, the tree before this commit was tagged
as yamt-pagecache-tag8.

this commit was splitted into small chunks to avoid
a limitation of cvs.  ("Protocol error: too many arguments")

diff --git a/external/bsd/dhcpcd/dist/dhcpcd-run-hooks.in b/external/bsd/dhcpcd/dist/dhcpcd-run-hooks.in
--- a/external/bsd/dhcpcd/dist/dhcpcd-run-hooks.in
+++ b/external/bsd/dhcpcd/dist/dhcpcd-run-hooks.in
@@ -1,12 +1,17 @@
 #!/bin/sh
+# $NetBSD: dhcpcd-run-hooks.in,v 1.1.1.8.4.3 2014/05/22 15:44:40 yamt Exp $
+
 # dhcpcd client configuration script 
 
 # Handy variables and functions for our hooks to use
-if [ "$reason" = ROUTERADVERT ]; then
-	ifsuffix=":ra"
-else
-	ifsuffix=
-fi
+case "$reason" in
+	ROUTERADVERT)
+		ifsuffix=":ra";;
+	INFORM6|BOUND6|RENEW6|REBIND6|REBOOT6|EXPIRE6|RELEASE6|STOP6)
+		ifsuffix=":dhcp6";;
+	*)
+		ifsuffix=;;
+esac
 ifname="$interface$ifsuffix"
 
 from=from
@@ -14,7 +19,8 @@ signature_base="# Generated by dhcpcd"
 signature="$signature_base $from $ifname"
 signature_base_end="# End of dhcpcd"
 signature_end="$signature_base_end $from $ifname"
-state_dir=/var/run/dhcpcd
+state_dir=@RUNDIR@/dhcpcd
+_detected_init=false
 
 : ${if_up:=false}
 : ${if_down:=false}
@@ -53,6 +59,21 @@ list_interfaces()
 		[ -n "$x" ] && ifaces="$ifaces${ifaces:+ }${x##*/}"
 	done
 	echo "$ifaces"
+}
+
+# Trim function
+trim()
+{
+	local var="$*"
+
+	var=${var#"${var%%[![:space:]]*}"}
+	var=${var%"${var##*[![:space:]]}"}
+	if [ -z "$var" ]; then
+		# So it seems our shell doesn't support wctype(3) patterns
+		# Fall back to sed
+		var=$(echo "$*" | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//')
+	fi
+	printf %s "$var"
 }
 
 # We normally use sed to extract values using a key from a list of files
@@ -163,7 +184,9 @@ valid_domainname()
 		[ -z "$label" -o ${#label} -gt 63 ] && return 1
 		case "$label" in
 		-*|_*|*-|*_)		return 1;;
-		*[![:alnum:]-_]*)	return 1;;
+		# some sh require - as the first or last character in the class
+		# when matching it
+		*[![:alnum:]_-]*)	return 1;;
 		esac
 		[ "$name" = "${name#*.}" ] && break
 		name="${name#*.}"
@@ -190,31 +213,115 @@ valid_path()
 	return 0
 }
 
+# With the advent of alternative init systems, it's possible to have
+# more than one installed. So we need to try and guess what one we're
+# using unless overriden by configure.
+detect_init()
+{
+	_service_exists="@SERVICEEXISTS@"
+	_service_cmd="@SERVICECMD@"
+	_service_status="@SERVICESTATUS@"
+
+	[ -n "$_service_cmd" ] && return 0
+
+	if ${_detected_init}; then
+		[ -n "$_service_cmd" ]
+		return $?
+	fi
+
+	# Detect the running init system.
+	# As systemd and OpenRC can be installed on top of legacy init
+	# systems we try to detect them first.
+	_service_status=
+	if [ -x /bin/systemctl -a -S /run/systemd/private ]; then
+		_service_exists="/bin/systemctl --quiet is-enabled \$1.service"
+		_service_status="/bin/systemctl --quiet is-active \$1.service"
+		_service_cmd="/bin/systemctl \$2 \$1.service"
+	elif [ -x /usr/bin/systemctl -a -S /run/systemd/private ]; then
+		_service_exists="/usr/bin/systemctl --quiet is-enabled \$1.service"
+		_service_status="/usr/bin/systemctl --quiet is-active \$1.service"
+		_service_cmd="/usr/bin/systemctl \$2 \$1.service"
+	elif [ -x /sbin/rc-service -a \
+	    -s /libexec/rc/init.d/softlevel -o -s /run/openrc/softlevel ]
+	then
+		_service_exists="/sbin/rc-service -e \$1"
+		_service_cmd="/sbin/rc-service \$1 -- -D \$2"
+	elif [ -x /usr/sbin/invoke-rc.d ]; then
+		_service_exists="/usr/sbin/invoke-rc.d --query --quiet \$1 start >/dev/null 2>&1 || [ \$? = 104 ]"
+		_service_cmd="/usr/sbin/invoke-rc.d \$1 \$2"
+	elif [ -x /sbin/service ]; then
+		_service_exists="/sbin/service \$1 >/dev/null 2>&1"
+		_service_cmd="/sbin/service \$1 \$2"
+	elif [ -e /etc/slackware-version -a -d /etc/rc.d ]; then
+		_service_exists="[ -x /etc/rc.d/rc.\$1 ]"
+		_service_cmd="/etc/rc.d/rc.\$1 \$2"
+		_service_status="/etc/rc.d/rc.\$1 status 1>/dev/null 2>&1"
+	else
+		for x in /etc/init.d/rc.d /etc/rc.d /etc/init.d; do
+			if [ -d $x ]; then
+				_service_exists="[ -x $x/\$1 ]"
+				_service_cmd="$x/\$1 \$2"
+				break
+			fi
+		done
+		if [ -e /etc/arch-release ]; then
+			_service_status="[ -e /var/run/daemons/\$1 ]"
+		elif [ "$x" = "/etc/rc.d" -a -e /etc/rc.d/rc.subr ]; then
+			_service_status="$x/\$1 check 1>/dev/null 2>&1"
+		fi
+	fi
+
+	_detected_init=true
+	if [ -z "$_service_cmd" ]; then
+		syslog err "could not detect a useable init system"
+		return 1
+	fi
+	return 0
+}
+
 # Check a system service exists 
 service_exists()
 {
-	@SERVICEEXISTS@
+
+	if [ -z "$_service_exists" ]; then
+		detect_init || return 1
+	fi
+	eval $_service_exists
 }
 
 # Send a command to a system service
 service_cmd()
 {
-	@SERVICECMD@
+
+	if [ -z "$_service_cmd" ]; then
+		detect_init || return 1
+	fi
+	eval $_service_cmd
 }
 
 # Send a command to a system service if it is running
 service_status()
 {
-	@SERVICESTATUS@
+
+	if [ -z "$_service_cmd" ]; then
+		detect_init || return 1
+	fi
+	if [ -n "$_service_status" ]; then
+		eval $_service_status
+	else
+		service_command $1 status >/dev/null 2>&1
+	fi
 }
 
 # Handy macros for our hooks
 service_command()
 {
+
 	service_exists $1 && service_cmd $1 $2
 }
 service_condcommand()
 {
+
 	service_exists $1 && service_status $1 && service_cmd $1 $2
 }
 
@@ -229,6 +336,7 @@ for hook in \
 do
 	for skip in $skip_hooks; do
 		case "$hook" in
+			*/*~)				continue 2;;
 			*/"$skip")			continue 2;;
 			*/[0-9][0-9]"-$skip")		continue 2;;
 			*/[0-9][0-9]"-$skip.sh")	continue 2;;
