Import OpenLDAP version 2.4.39. The list of changes since version 2.4.23 is too long to put here (over 650 lines of changelog).

diff --git a/external/bsd/openldap/dist/tests/scripts/all b/external/bsd/openldap/dist/tests/scripts/all
--- a/external/bsd/openldap/dist/tests/scripts/all
+++ b/external/bsd/openldap/dist/tests/scripts/all
@@ -1,8 +1,8 @@
 #! /bin/sh
-# OpenLDAP: pkg/ldap/tests/scripts/all,v 1.26.2.9 2010/04/13 20:23:59 kurt Exp
+# $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2010 The OpenLDAP Foundation.
+## Copyright 1998-2014 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -21,9 +21,15 @@ if test -t 1 ; then
 	TN=`$SHTOOL echo -e "%b" 2>/dev/null`
 fi
 
+FAILCOUNT=0
+SKIPCOUNT=0
 SLEEPTIME=10
 
 echo ">>>>> Executing all LDAP tests for $BACKEND"
+
+if [ -n "$NOEXIT" ]; then
+	echo "Result	Test" > $TESTWD/results
+fi
 
 for CMD in $SRCDIR/scripts/test*; do
 	case "$CMD" in
@@ -51,17 +57,46 @@ for CMD in $SRCDIR/scripts/test*; do
 EOF
 	fi
 
-	echo ">>>>> Starting ${TB}`basename $CMD`${TN} for $BACKEND..."
-	$CMD
-	RC=$?
-	if test $RC -eq 0 ; then
-		echo ">>>>> $CMD completed ${TB}OK${TN} for $BACKEND."
+	if [ -x "$CMD" ]; then
+		BCMD=`basename $CMD`
+		echo ">>>>> Starting ${TB}$BCMD${TN} for $BACKEND..."
+		$CMD
+		RC=$?
+		if test $RC -eq 0 ; then
+			echo ">>>>> $BCMD completed ${TB}OK${TN} for $BACKEND."
+		else
+			echo ">>>>> $BCMD ${TB}failed${TN} for $BACKEND"
+			FAILCOUNT=`expr $FAILCOUNT + 1`
+
+			if [ -n "$NOEXIT" ]; then
+				echo "Continuing."
+			else
+				echo "(exit $RC)"
+				exit $RC
+			fi
+		fi
 	else
-		echo ">>>>> $CMD ${TB}failed${TN} for $BACKEND (exit $RC)"
-		exit $RC
+		echo ">>>>> Skipping ${TB}$BCMD${TN} for $BACKEND."
+		SKIPCOUNT=`expr $SKIPCOUNT + 1`
+		RC="-"
+	fi
+
+	if [ -n "$NOEXIT" ]; then
+		echo "$RC	$BCMD" >> $TESTWD/results
 	fi
 
 #	echo ">>>>> waiting $SLEEPTIME seconds for things to exit"
 #	sleep $SLEEPTIME
 	echo ""
 done
+
+if [ -n "$NOEXIT" ]; then
+	if [ "$FAILCOUNT" -gt 0 ]; then
+		cat $TESTWD/results
+		echo "$FAILCOUNT tests for $BACKEND ${TB}failed${TN}. Please review the test log."
+	else
+		echo "All executed tests for $BACKEND ${TB}succeeded${TN}."
+	fi
+fi
+
+echo "$SKIPCOUNT tests for $BACKEND were ${TB}skipped${TN}."
diff --git a/external/bsd/openldap/dist/tests/scripts/test058-syncrepl-asymmetric b/external/bsd/openldap/dist/tests/scripts/test058-syncrepl-asymmetric
--- a/external/bsd/openldap/dist/tests/scripts/test058-syncrepl-asymmetric
+++ b/external/bsd/openldap/dist/tests/scripts/test058-syncrepl-asymmetric
@@ -1,8 +1,8 @@
 #! /bin/sh
-# OpenLDAP: pkg/ldap/tests/scripts/test058-syncrepl-asymmetric,v 1.1.2.6 2010/04/19 19:14:36 quanah Exp
+# $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2010 The OpenLDAP Foundation.
+## Copyright 1998-2014 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -112,9 +112,12 @@
 # iterations the script should perform.
 
 if test "$BACKEND" = ldif ; then
-	echo "$backend backend does not support access controls, test skipped"
+	echo "$BACKEND backend does not support access controls, test skipped"
 	exit 0
 fi
+
+#echo "Test 058 is currently disabled"
+#exit 0
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
@@ -130,6 +133,8 @@ SM2_DIR=$TESTDIR/sm2
 SS1_DIR=$TESTDIR/ss1
 SS2_DIR=$TESTDIR/ss2
 SSC_DIR=$TESTDIR/ssc
+
+MNUM=1
 
 mkdir -p $TESTDIR
 
@@ -373,7 +378,7 @@ EOF
 dn: cn=module,cn=config
 objectClass: olcModuleList
 cn: module
-olcModulePath: ../../../servers/slapd/back-$BACKEND
+olcModulePath: $TESTWD/../servers/slapd/back-$BACKEND
 olcModuleLoad: back_$BACKEND.la
 EOF
 	RC=$?
@@ -390,7 +395,7 @@ if [ "$SYNCPROV" = syncprovmod ]; then
 dn: cn=module,cn=config
 objectClass: olcModuleList
 cn: module
-olcModulePath: ../../../servers/slapd/overlays
+olcModulePath: $TESTWD/../servers/slapd/overlays
 olcModuleLoad: syncprov.la
 
 EOF
@@ -484,7 +489,7 @@ if [ "$SYNCPROV" = syncprovmod ]; then
 dn: cn=module,cn=config
 objectClass: olcModuleList
 cn: module
-olcModulePath: ../../../servers/slapd/overlays
+olcModulePath: $TESTWD/../servers/slapd/overlays
 olcModuleLoad: syncprov.la
 
 EOF
@@ -557,7 +562,7 @@ if [ "$SYNCPROV" = syncprovmod ]; then
 dn: cn=module,cn=config
 objectClass: olcModuleList
 cn: module
-olcModulePath: ../../../servers/slapd/overlays
+olcModulePath: $TESTWD/../servers/slapd/overlays
 olcModuleLoad: syncprov.la
 
 EOF
@@ -976,6 +981,29 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+# Test for ITS#6716, modify on central master to ensure that the CSN
+# order is "sid2 < sid3 < sid1".  When site1 master starts it is likely
+# to sync with central master before it syncs with site1 master. When
+# central master syncs with site1 master they will share the sid1 and
+# sid3 CSNs, the additonal sid2 CSN hold by site1 master will be the
+# oldest. Central master will not receive the changes made on site1
+# master unless it completely ignores the CSNs presented by central
+# master.
+echo "Using ldapmodify to modify central master..."
+$LDAPMODIFY -D "$MANAGERDN" -H $URI1 -w $PASSWD <<EOF >> $TESTOUT 2>&1
+dn: dc=example,dc=com
+changetype: modify
+add: description
+description: Modify$MNUM
+
+EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 if test -z "$SM1_PID" ; then
 	echo "Restarting site1 master slapd on TCP/IP port $PORT2..."
 	cd $SM1_DIR
@@ -1011,6 +1039,44 @@ for i in 1 2 3 4 5; do
 	RESULT=`$LDAPSEARCH -H $URI1 \
 		-s base -b "ou=sm1ou1,$BASEDN" \
 		'(objectClass=*)' 2>&1 | awk '/^dn:/ {print "OK"}'`
+	if test "x$RESULT$nullOK" = "xOK" ; then
+		RC=0
+		break
+	fi
+	echo "Waiting $i seconds for syncrepl to receive changes..."
+	sleep $i
+done
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Using ldapsearch to check that site1 master received central master update..."
+RC=32
+for i in 1 2 3 4 5; do
+	RESULT=`$LDAPSEARCH -H $URI2 \
+		-s base -b "$BASEDN" \
+		"(description=Modify$MNUM)" 2>&1 | awk '/^dn:/ {print "OK"}'`
+	if test "x$RESULT$nullOK" = "xOK" ; then
+		RC=0
+		break
+	fi
+	echo "Waiting $i seconds for syncrepl to receive changes..."
+	sleep $i
+done
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Using ldapsearch to check that site2 master received central master update..."
+RC=32
+for i in 1 2 3 4 5; do
+	RESULT=`$LDAPSEARCH -H $URI3 \
+		-s base -b "$BASEDN" \
+		"(description=Modify$MNUM)" 2>&1 | awk '/^dn:/ {print "OK"}'`
 	if test "x$RESULT$nullOK" = "xOK" ; then
 		RC=0
 		break
@@ -1515,8 +1581,6 @@ chmod +x $TESTDIR/checkcsn.sh
 
 echo "Checking contextCSN after initial replication..."
 . $TESTDIR/checkcsn.sh
-
-MNUM=1
 
 # TEST:
 # Test that updates to the first backend on central master, which should
@@ -2259,7 +2323,7 @@ fi
 
 # TEST:
 # Run race tests when more than one backend is replicated from the same
-# producer.  This will usually fail long before 100 iterations unless
+# provider.  This will usually fail long before 100 iterations unless
 # syncrepl stores the contextCSN in the suffix of its own database, and
 # that syncprov follows these rules before updating its own CSN when it
 # detects updates from syncrepl:
