Rebase.

diff --git a/external/bsd/openldap/dist/tests/scripts/test020-proxycache b/external/bsd/openldap/dist/tests/scripts/test020-proxycache
--- a/external/bsd/openldap/dist/tests/scripts/test020-proxycache
+++ b/external/bsd/openldap/dist/tests/scripts/test020-proxycache
@@ -1,8 +1,8 @@
 #! /bin/sh
-# OpenLDAP: pkg/ldap/tests/scripts/test020-proxycache,v 1.26.2.13 2010/04/19 19:14:34 quanah Exp
+# $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2010 The OpenLDAP Foundation.
+## Copyright 1998-2014 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -152,7 +152,7 @@ fi
 grep "query template" $LOG2 > /dev/null
 RC=$?
 if test $RC != 0 ; then
-	echo "Debug messages unavailable, test aborted..."
+	echo "Debug messages unavailable, remaining test skipped..."
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS && wait
 	exit 0
 fi
@@ -256,7 +256,7 @@ case $RC in
 0)
 	echo "ldapsearch should have failed!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	exit 1
 	;;
 4)
 	echo "ldapsearch failed ($RC)"
@@ -283,7 +283,7 @@ case $RC in
 0)
 	echo "ldapsearch should have failed!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	exit 1
 	;;
 4)
 	echo "ldapsearch failed ($RC)"
@@ -295,18 +295,32 @@ case $RC in
 	;;
 esac
 
+CNT=`expr $CNT + 1`
+FILTER="(|(cn=All Staff)(sn=All Staff))"
+ATTRS="sn cn title uid undefinedAttr"
+echo "Query $CNT: filter:$FILTER attrs:$ATTRS"  
+echo "# Query $CNT: filter:$FILTER attrs:$ATTRS" >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
+	"$FILTER" $ATTRS >> $SEARCHOUT 2>> $TESTOUT
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 FIRST=$CNT
 
-# queries 2-6,8-9 are cacheable
-CACHEABILITY=011111011
+# queries 2-6,8-10 are cacheable
+CACHEABILITY=0111110111
 grep CACHEABLE $LOG2 | awk '{ 
-		if ($2 == "NOT") 
+		if ($3 == "NOT") 
 			printf "Query %d not cacheable\n",NR
 		else 
 			printf "Query %d cacheable\n",NR
 	}' 
 CACHED=`grep CACHEABLE $LOG2 | awk '{ 
-		if ($2 == "NOT") 
+		if ($3 == "NOT") 
 			printf "0" 
 		else 
 			printf "1" 
@@ -316,6 +330,8 @@ if test "$CACHEABILITY" = "$CACHED" ; then
 	echo "Successfully verified cacheability"
 else 
 	echo "Error in verifying cacheability"
+	echo "$CACHED"
+	echo "$CACHEABILITY"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
@@ -392,7 +408,7 @@ case $RC in
 0)
 	echo "ldapsearch should have failed!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	exit 1
 	;;
 4)
 	echo "ldapsearch failed ($RC)"
@@ -419,7 +435,7 @@ case $RC in
 0)
 	echo "ldapsearch should have failed!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	exit 1
 	;;
 4)
 	echo "ldapsearch failed ($RC)"
@@ -431,14 +447,28 @@ case $RC in
 	;;
 esac
 
-#queries 10-12,15 are answerable, 13-14 are not
-#actually, 12 would be answerable, but since 8 made mail=*example.com
+CNT=`expr $CNT + 1`
+FILTER="(|(cn=All Staff)(sn=All Staff))"
+ATTRS="sn cn title uid undefinedAttr"
+echo "Query $CNT: filter:$FILTER attrs:$ATTRS"  
+echo "# Query $CNT: filter:$FILTER attrs:$ATTRS" >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
+	"$FILTER" $ATTRS >> $SEARCHOUT 2>> $TESTOUT
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+#queries 11-13,16-17 are answerable, 14-15 are not
+#actually, 14 would be answerable, but since 8 made mail=*example.com
 #not answerable because of sizelimit, queries contained in it are no longer
 #answerable as well
-ANSWERABILITY=111001
+ANSWERABILITY=1110011
 grep ANSWERABLE $LOG2 | awk "BEGIN {FIRST=$FIRST}"'{ 
 		if (NR > FIRST) { 
-			if ($2 == "NOT") 
+			if ($3 == "NOT") 
 				printf "Query %d not answerable\n",NR
 			else 
 				printf "Query %d answerable\n",NR 
@@ -446,7 +476,7 @@ grep ANSWERABLE $LOG2 | awk "BEGIN {FIRST=$FIRST}"'{
 	}' 
 ANSWERED=`grep ANSWERABLE $LOG2 | awk "BEGIN {FIRST=$FIRST}"'{ 
 		if (NR > FIRST) { 
-			if ($2 == "NOT") 
+			if ($3 == "NOT") 
 				printf "0" 
 			else 
 				printf "1"
@@ -462,9 +492,9 @@ else
 fi
 
 echo "Filtering ldapsearch results..."
-$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
+$LDIFFILTER -s ldif=a < $SEARCHOUT > $SEARCHFLT
 echo "Filtering original ldif..."
-$LDIFFILTER < $PROXYCACHEOUT > $LDIFFLT
+$LDIFFILTER -s ldif=a < $PROXYCACHEOUT > $LDIFFLT
 echo "Comparing filter output..."
 $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 
@@ -507,7 +537,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-SLEEP=`expr $PCACHETTR + $PCACHE_CCPERIOD`
+SLEEP=`expr $PCACHETTR + $PCACHE_CCPERIOD + 1`
 echo "Waiting $SLEEP seconds for cache to refresh"
 
 sleep $SLEEP
@@ -527,7 +557,7 @@ RC=$?
 if test $RC != 0 ; then
 	echo "Refresh failed"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS && wait
-	exit 0
+	exit 1
 fi
 
 echo ""
@@ -552,7 +582,7 @@ RC=$?
 if test $RC != 0 ; then
 	echo "Refresh failed"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS && wait
-	exit 0
+	exit 1
 fi
 
 CNT=`expr $CNT + 1`
@@ -574,7 +604,7 @@ RC=$?
 if test $RC != 0 ; then
 	echo "Refresh failed"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS && wait
-	exit 0
+	exit 1
 fi
 
 echo ""
@@ -592,7 +622,7 @@ RC=`grep "CACH.* BIND" $LOG2 | wc -l`
 if test $RC != 3 ; then
 	echo "ldappasswd didn't update the cache"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS && wait
-	exit 0
+	exit 1
 fi
 
 CNT=`expr $CNT + 1`
@@ -613,7 +643,7 @@ RC=`grep "CACH.* BIND" $LOG2 | wc -l`
 if test $RC != 4 ; then
 	echo "Bind wasn't answered from cache"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS && wait
-	exit 0
+	exit 1
 fi
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
