OpenLDAP 2.4.50 Release (2020/04/28)     Fixed client benign typos (ITS#8890)     Fixed libldap type cast (ITS#9175)     Fixed libldap retry loop in ldap_int_tls_connect (ITS#8650)     Fixed libldap_r race on Windows mutex initialization (ITS#9181)     Fixed liblunicode memory leak (ITS#9198)     Fixed slapd benign typos (ITS#8890)     Fixed slapd to limit depth of nested filters (ITS#9202)     Fixed slapd-mdb memory leak in dnSuperiorMatch (ITS#9214)     Fixed slapo-pcache database initialization (ITS#9182)     Fixed slapo-ppolicy callback (ITS#9171)     Build 	Fix olcDatabaseDummy initialization for windows (ITS#7074) 	Fix detection for ws2tcpip.h for windows (ITS#8383) 	Fix back-mdb types for windows (ITS#7878)     Contrib 	Update ldapc++ config.guess and config.sub to support newer 	    architectures (ITS#7855) 	Added pw-argon2 module (ITS#9233, ITS#8575, ITS#9203, ITS#9206)     Documentation 	slapd-ldap(5) - Clarify idassert-authzfrom behavior (ITS#9003) 	slapd-meta(5) - Remove client-pr option (ITS#8683) 	slapdinex(8) - Fix truncate option information for back-mdb (ITS#9230)
OpenLDAP 2.4.49 Release (2020/01/30)
    Added slapd-monitor database entry count for slapd-mdb (ITS#9154)
    Fixed client tools to not add controls on cancel/abandon (ITS#9145)
    Fixed client tools SyncInfo message to be LDIF compliant (ITS#8116)
    Fixed libldap to correctly free sb (ITS#9081, ITS#8755)
    Fixed libldap descriptor leak if ldaps fails (ITS#9147)
    Fixed libldap remove unnecessary global mutex for GnuTLS (ITS#9069)
    Fixed slapd syntax evaluation of preferredDeliveryMethod (ITS#9067)
    Fixed slapd to relax domainScope control check (ITS#9100)
    Fixed slapd to have cleaner error handling during connection setup
	 (ITS#9112)
    Fixed slapd data check when processing cancel exop (ITS#9124)
    Fixed slapd attribute description processing (ITS#9128)
    Fixed slapd-ldap to set oldctrls correctly (ITS#9076)
    Fixed slapd-mdb to honor unchecked limit with alias deref (ITS#7657)
    Fixed slapd-mdb missing final commit with slapindex (ITS#9095)
    Fixed slapd-mdb drop attr mappings added in an aborted txn (ITS#9091)
    Fixed slapd-mdb nosync FLAG configuration handling (ITS#9150)
    Fixed slapd-monitor global operation counter reporting (ITS#9119)
    Fixed slapo-ppolicy when used with slapauth (ITS#8629)
    Fixed slapo-ppolicy to add a missed normalised copy of pwdChangedTime
	(ITS#9126)
    Fixed slapo-syncprov fix sessionlog init (ITS#9146)
    Fixed slapo-unique loop termination (ITS#9077)
    Build Environment
	Fix mkdep to honor TMPDIR if set (ITS#9062)
	Remove ICU library detection (ITS#9144)
	Update config.guess and config.sub to support newer architectures
	    (ITS#7855)
	Disable ITS8521 regression test as it is no longer valid (ITS#9015)
    Documentation
	admin24 - Fix inconsistent whitespace in replication section (ITS#9153)
	slapd-config(5)/slapd.conf(5) - Fix missing bold tag for keyword
	    (ITS#9063)
	slapd-ldap(5) - Document "tls none" option (ITS#9071)
	slapo-ppolicy(5) - Correctly document pwdGraceAuthnLimit (ITS#9065)

diff --git a/external/bsd/openldap/dist/tests/scripts/test018-syncreplication-persist b/external/bsd/openldap/dist/tests/scripts/test018-syncreplication-persist
--- a/external/bsd/openldap/dist/tests/scripts/test018-syncreplication-persist
+++ b/external/bsd/openldap/dist/tests/scripts/test018-syncreplication-persist
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2019 The OpenLDAP Foundation.
+## Copyright 1998-2020 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -494,6 +494,14 @@ EOMODS
 	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
 	sleep $SLEEP1
 fi
+
+# Testing a cancel exop (should go in its own testcase)
+$LDAPSEARCH -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
+	-e '!cancel' \
+	'(objectclass=*)' '*' $OPATTRS > $TESTOUT 2>&1
+RC=$?
+# cancelled operation returns -1, so no point of checking return code, either
+# it's cancelled or we get stuck forever
 
 echo "Using ldapsearch to read all the entries from the provider..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
