OpenLDAP 2.4.21.  Numerous fixes, including: * properly handle NUL in CN of SSL certs (CVE-2009-3767)

diff --git a/external/bsd/openldap/dist/tests/scripts/test037-manage b/external/bsd/openldap/dist/tests/scripts/test037-manage
--- a/external/bsd/openldap/dist/tests/scripts/test037-manage
+++ b/external/bsd/openldap/dist/tests/scripts/test037-manage
@@ -1,8 +1,8 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test037-manage,v 1.12.2.5 2008/02/11 23:26:51 kurt Exp $
+# OpenLDAP: pkg/ldap/tests/scripts/test037-manage,v 1.12.2.8 2009/02/22 05:50:54 quanah Exp
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2008 The OpenLDAP Foundation.
+## Copyright 1998-2009 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -17,7 +17,7 @@ echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
 if test $BACKEND = "ldif" ; then 
-	echo "LDIF backend does not support manageDIT control, test skipped"
+	echo "LDIF backend does not support relax control, test skipped"
 	exit 0
 fi 
 
@@ -130,22 +130,9 @@ createTimestamp: 19700101000000Z
 modifiersName: cn=Someone Else
 modifyTimestamp: 19700101000000Z
 entryUUID: badbadef-dbad-1029-92f7-badbadbadbad
-EOMODS
 
-RC=$?
-if test $RC != 0 ; then
-	echo "ldapmodify failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
-echo "Testing modify, add, and delete..."
-$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
-	-e \!relax > \
-	$TESTOUT 2>&1 << EOMODS
-version: 1
 #
-# Non-working tests
+# Tests that did not work until ITS#5792
 #
 
 dn: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,
@@ -154,9 +141,8 @@ dn: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,
 changetype: modify
 replace: objectClass
 objectClass: obsoletePerson
+objectClass: testPerson
 -
-replace: structuralObjectClass
-structuralObjectClass: testPerson
 
 dn: cn=James A Jones 1,ou=Alumni Association,ou=People,dc=example,dc=com
 # update structural object class of entry via objectClass add
@@ -164,8 +150,6 @@ changetype: modify
 add: objectClass
 objectClass: testPerson
 -
-replace: structuralObjectClass
-structuralObjectClass: testPerson
 
 dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 # update structural object class of entry via objectClass delete/add
@@ -176,17 +160,13 @@ objectClass: OpenLDAPperson
 add: objectClass
 objectClass: testPerson
 -
-delete: structuralObjectClass
--
-add: structuralObjectClass
-structuralObjectClass: testPerson
 EOMODS
 
 RC=$?
 if test $RC != 0 ; then
-	echo "ldapmodify failed ($RC)!  IGNORED"
-#	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-#	exit $RC
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
 fi
 
 echo "Using ldapsearch to retrieve all the entries..."
diff --git a/external/bsd/openldap/dist/tests/scripts/test044-dynlist b/external/bsd/openldap/dist/tests/scripts/test044-dynlist
--- a/external/bsd/openldap/dist/tests/scripts/test044-dynlist
+++ b/external/bsd/openldap/dist/tests/scripts/test044-dynlist
@@ -1,7 +1,7 @@
 #! /bin/sh
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2008 The OpenLDAP Foundation.
+## Copyright 1998-2009 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -254,7 +254,118 @@ delete: olcDLattrSet
 olcDLattrSet: {0}
 -
 add: olcDLattrSet
+olcDLattrSet: groupOfURLs memberURL sn:cn mail
+-
+EOMODS
+
+echo "==========================================================" >> $LOG1
+
+echo "Testing attribute mapping"
+
+echo "Testing list search of all (mapped) attrs..."
+echo "# Testing list search of all (mapped) attrs..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$LISTDN" -h $LOCALHOST -p $PORT1 \
+	'(cn=Dynamic List)' '*' \
+	>> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Testing list search of a (mapped) listed attr..."
+echo "# Testing list search of a (mapped) listed attr..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$LISTDN" -h $LOCALHOST -p $PORT1 \
+	'(cn=Dynamic List)' sn \
+	>> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Testing list search of a (n unmapped) listed attr..."
+echo "# Testing list search of a (n unmapped) listed attr..." >> $SEARCHOUT
+$LDAPSEARCH -S "" -b "$LISTDN" -h $LOCALHOST -p $PORT1 \
+	'(cn=Dynamic List)' mail \
+	>> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Testing list compare (mapped attrs) ..."
+echo "# Testing list compare (mapped attrs) ..." >> $SEARCHOUT
+$LDAPCOMPARE -h $LOCALHOST -p $PORT1 \
+	"cn=Dynamic List,$LISTDN" "sn:Bjorn Jensen" \
+	>> $SEARCHOUT 2>&1
+RC=$?
+case $RC in
+5)
+	echo "ldapcompare returned FALSE ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+6)
+	echo "ldapcompare returned TRUE ($RC)"
+	;;
+0)
+	echo "ldapcompare returned success ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+echo "" >> $SEARCHOUT
+
+echo "Testing list compare (mapped attrs; should return FALSE)..."
+echo "# Testing list compare (mapped attrs; should return FALSE)..." >> $SEARCHOUT
+$LDAPCOMPARE -h $LOCALHOST -p $PORT1 \
+	"cn=Dynamic List,$LISTDN" "sn:FALSE" \
+	>> $SEARCHOUT 2>&1
+RC=$?
+case $RC in
+5)
+	echo "ldapcompare returned FALSE ($RC)"
+	;;
+6)
+	echo "ldapcompare returned TRUE ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+0)
+	echo "ldapcompare returned success ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "ldapcompare failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+echo "" >> $SEARCHOUT
+
+echo "Reconfiguring slapd..."
+$LDAPMODIFY -x -D cn=config -h $LOCALHOST -p $PORT1 -y $CONFIGPWF > \
+	$TESTOUT 2>&1 << EOMODS
+version: 1
+dn: olcOverlay={0}dynlist,olcDatabase={2}$BACKEND,cn=config
+changetype: modify
+delete: olcDLattrSet
+olcDLattrSet: {0}
+-
+add: olcDLattrSet
 olcDLattrSet: groupOfURLs memberURL member
+-
 EOMODS
 
 echo "==========================================================" >> $LOG1
