OpenLDAP 2.4.45 Release (2017/06/01) 	Added slapd support for OpenSSL 1.1.0 series (ITS#8353, ITS#8533, ITS#8634) 	Fixed libldap to fail ldap_result if the handle is already bad (ITS#8585) 	Fixed libldap to expose error if user specified CA doesn't exist (ITS#8529) 	Fixed libldap handling of Diffie-Hellman parameters (ITS#7506) 	Fixed libldap GnuTLS use after free (ITS#8385) 	Fixed libldap SASL initialization (ITS#8648) 	Fixed slapd bconfig rDN escape handling (ITS#8574) 	Fixed slapd segfault with invalid hostname (ITS#8631) 	Fixed slapd sasl SEGV rebind in same session (ITS#8568) 	Fixed slapd syncrepl filter handling (ITS#8413) 	Fixed slapd syncrepl infinite looping mods with delta-sync MMR (ITS#8432) 	Fixed slapd callback struct so older modules without writewait should function.                     Custom modules may need to be updated for sc_writewait callback (ITS#8435) 	Fixed slapd-ldap/meta broken LDAP_TAILQ macro (ITS#8576) 	Fixed slapd-mdb so it passes ITS6794 regression test (ITS#6794) 	Fixed slapd-mdb double free with size zero paged result (ITS#8655) 	Fixed slapd-meta uninitialized diagnostic message (ITS#8442) 	Fixed slapo-accesslog to honor pauses during purge for cn=config update (ITS#8423) 	Fixed slapo-accesslog with multiple modifications to the same attribute (ITS#6545) 	Fixed slapo-relay to correctly initialize sc_writewait (ITS#8428) 	Fixed slapo-sssvlv double free (ITS#8592) 	Fixed slapo-unique with empty modifications (ITS#8266) 	Build Environment 		Added test065 for proxyauthz (ITS#8571) 		Fix test008 to be portable (ITS#8414) 		Fix test064 to wait for slapd to start (ITS#8644) 		Fix its4336 regression test (ITS#8534) 		Fix its4337 regression test (ITS#8535) 		Fix regression tests to execute on all backends (ITS#8539) 	Contrib 		Added slapo-autogroup(5) man page (ITS#8569) 		Added passwd missing conversion scripts for apr1 (ITS#6826) 		Fixed contrib modules where the writewait callback was not correctly initialized (ITS#8435) 		Fixed smbk5pwd to build with newer OpenSSL releases (ITS#8525) 	Documentation 		admin24 fixed tls_cipher_suite bindconf option (ITS#8099) 		admin24 fixed typo cn=config to be slapd.d (ITS#8449) 		admin24 fixed slapo-syncprov information to be curent (ITS#8253) 		admin24 fixed typo in access control docs (ITS#7341, ITS#8391) 		admin24 fixed minor typo in tuning guide (ITS#8499) 		admin24 fixed information about the limits option (ITS#7700) 		admin24 fixed missing options for syncrepl configuration (ITS#7700) 		admin24 fixed accesslog documentation to note it should not be replicated (ITS#8344) 		Fixed ldap.conf(5) missing information on SASL_NOCANON option (ITS#7177) 		Fixed ldapsearch(1) information on the V[V] flag behavior (ITS#7177, ITS#6339) 		Fixed slapd-config(5), slapd.conf(5) clarification on interval keyword for refreshAndPersist (ITS#8538) 		Fixed slapd-config(5), slapd.conf(5) clarify serverID requirements (ITS#8635) 		Fixed slapd-config(5), slapd.conf(5) clarification on loglevel settings (ITS#8123) 		Fixed slapo-ppolicy(5) to clearly note rootdn requirement (ITS#8565) 		Fixed slapo-memberof(5) to note it is not safe to use with replication (ITS#8613) 		Fixed slapo-syncprov(5) documentation to be current (ITS#8253) 		Fixed slapadd(8) manpage to note slapd-mdb (ITS#8215) 		Fixed various minor grammar issues in the man pages (ITS#8544) 		Fixed various typos (ITS#8587)

diff --git a/external/bsd/openldap/dist/tests/scripts/test063-delta-multimaster b/external/bsd/openldap/dist/tests/scripts/test063-delta-multimaster
--- a/external/bsd/openldap/dist/tests/scripts/test063-delta-multimaster
+++ b/external/bsd/openldap/dist/tests/scripts/test063-delta-multimaster
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2016 The OpenLDAP Foundation.
+## Copyright 1998-2017 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -469,6 +469,23 @@ EOF
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed for server 2 database ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+$LDAPMODIFY -D "$MANAGERDN" -H $URI1 -w $PASSWD \
+	>> $TESTOUT 2>&1 << EOF
+dn: $THEDN
+changetype: modify
+replace: sn
+sn: Replaced later
+-
+replace: sn
+sn: Surname
+EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed for server 1 database ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
