Import OpenLDAP 2.6.10 (previous was 2.5.6)
A.1. New Features and Enhancements in 2.6
A.1.1. New features in slapd
slapd now supports logging directly to a file, bypassing syslog.

A.1.2. New features in lloadd
lloadd now supports additional balancing mechansims

A.2. Obsolete Features Removed From 2.6
These features were strongly deprecated in 2.5 and removed in 2.6.

A.2.1. back-ndb
The experimental and incomplete back-ndb backend was removed.

See CHANGES for the complete list of bugfixes.

diff --git a/external/bsd/openldap/dist/tests/scripts/test049-sync-config b/external/bsd/openldap/dist/tests/scripts/test049-sync-config
--- a/external/bsd/openldap/dist/tests/scripts/test049-sync-config
+++ b/external/bsd/openldap/dist/tests/scripts/test049-sync-config
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2021 The OpenLDAP Foundation.
+## Copyright 1998-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -61,6 +61,12 @@ esac
 echo "Starting provider slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND < $DYNAMICCONF > $CONFLDIF
 $SLAPADD -F $CFPRO -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 cd $PRODIR
 $SLAPD -F ./slapd.d -h $URI1 -d $LVL > $LOG1 2>&1 &
 PID=$!
@@ -134,6 +140,13 @@ fi
 
 echo "Starting consumer slapd on TCP/IP port $PORT2..."
 $SLAPADD -F $CFCON -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 cd $CONDIR
 $SLAPD -F ./slapd.d -h $URI2 -d $LVL > $LOG2 2>&1 &
 CONSUMERPID=$!
diff --git a/external/bsd/openldap/dist/tests/scripts/test050-syncrepl-multiprovider b/external/bsd/openldap/dist/tests/scripts/test050-syncrepl-multiprovider
--- a/external/bsd/openldap/dist/tests/scripts/test050-syncrepl-multiprovider
+++ b/external/bsd/openldap/dist/tests/scripts/test050-syncrepl-multiprovider
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2021 The OpenLDAP Foundation.
+## Copyright 1998-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -79,6 +79,11 @@ objectClass: olcDatabaseConfig
 olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 n=`expr $n + 1`
 done
@@ -165,7 +170,7 @@ PORT=`expr $BASEPORT + $n`
 URI="ldap://${LOCALHOST}:$PORT/"
 echo "olcSyncRepl: rid=00$n provider=$URI binddn=\"cn=config\" bindmethod=simple" >> $TMP
 echo "  credentials=$CONFIGPW searchbase=\"cn=config\" type=refreshAndPersist" >> $TMP
-echo "  retry=\"3 10 300 5\" timeout=3" >> $TMP
+echo "  retry=\"1 12 300 5\" timeout=3" >> $TMP
 n=`expr $n + 1`
 done
 echo "-" >> $TMP
@@ -227,7 +232,7 @@ P2=`expr $BASEPORT + $j`
 U2="ldap://${LOCALHOST}:$P2/"
 echo "olcSyncRepl: rid=00$j provider=$U2 binddn=\"cn=config\" bindmethod=simple" >> $TMP
 echo "  credentials=$CONFIGPW searchbase=\"cn=config\" type=refreshAndPersist" >> $TMP
-echo "  retry=\"3 10 300 5\" timeout=3" >> $TMP
+echo "  retry=\"1 12 300 5\" timeout=3" >> $TMP
 j=`expr $j + 1`
 done
 cat <<EOF >> $TMP
@@ -291,7 +296,7 @@ URI="ldap://${LOCALHOST}:$PORT/"
 
 echo "olcSyncRepl: rid=01$n provider=$URI binddn=\"$MANAGERDN\" bindmethod=simple" >> $TMP
 echo "  credentials=$PASSWD searchbase=\"$BASEDN\" $SYNCTYPE" >> $TMP
-echo "  retry=\"3 10 300 5\" timeout=3" >> $TMP
+echo "  retry=\"1 12 300 5\" timeout=3" >> $TMP
 n=`expr $n + 1`
 done
 
diff --git a/external/bsd/openldap/dist/tests/scripts/test053-syncprov-glue b/external/bsd/openldap/dist/tests/scripts/test053-syncprov-glue
--- a/external/bsd/openldap/dist/tests/scripts/test053-syncprov-glue
+++ b/external/bsd/openldap/dist/tests/scripts/test053-syncprov-glue
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2021 The OpenLDAP Foundation.
+## Copyright 1998-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -74,6 +74,11 @@ olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 
 EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 echo "Initializing provider2 configurations..."
 $SLAPADD -F $CFPRO2 -n 0 <<EOF
@@ -87,6 +92,11 @@ olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 
 EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 $SLAPADD -F $CFCONS -n 0 <<EOF
 dn: cn=config
@@ -98,6 +108,11 @@ objectClass: olcDatabaseConfig
 olcDatabase: {0}config
 olcRootPW:< file://$CONFIGPWF
 EOF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 echo "Starting provider slapd on TCP/IP port $PORT1..."
 cd $PRODDIR
diff --git a/external/bsd/openldap/dist/tests/scripts/test059-consumer-config b/external/bsd/openldap/dist/tests/scripts/test059-consumer-config
--- a/external/bsd/openldap/dist/tests/scripts/test059-consumer-config
+++ b/external/bsd/openldap/dist/tests/scripts/test059-consumer-config
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2021 The OpenLDAP Foundation.
+## Copyright 1998-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -57,6 +57,12 @@ esac
 echo "Starting provider slapd on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND < $DYNAMICCONF > $CONFLDIF
 $SLAPADD -F $CFPRO -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 $SLAPD -F $CFPRO -h $URI1 -d $LVL > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
@@ -182,6 +188,13 @@ fi
 
 echo "Starting consumer slapd on TCP/IP port $PORT2..."
 $SLAPADD -F $CFCON -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 $SLAPD -F $CFCON -h $URI2 -d $LVL > $LOG2 2>&1 &
 CONSUMERPID=$!
 if test $WAIT != 0 ; then
diff --git a/external/bsd/openldap/dist/tests/scripts/test062-config-delete b/external/bsd/openldap/dist/tests/scripts/test062-config-delete
--- a/external/bsd/openldap/dist/tests/scripts/test062-config-delete
+++ b/external/bsd/openldap/dist/tests/scripts/test062-config-delete
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2021 The OpenLDAP Foundation.
+## Copyright 1998-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -39,6 +39,12 @@ $SLAPPASSWD -g -n >$CONFIGPWF
 echo "Starting slapd on TCP/IP port $PORT1... $PWD"
 . $CONFFILTER $BACKEND < $DYNAMICCONF > $CONFLDIF
 $SLAPADD -F $CONFDIR -n 0 -l $CONFLDIF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 cd $TESTDIR
 $SLAPD -F ./slapd.d -h $URI1 -d $LVL > $LOG1 2>&1 &
 PID=$!
diff --git a/external/bsd/openldap/dist/tests/scripts/test070-delta-multiprovider-ldaps b/external/bsd/openldap/dist/tests/scripts/test070-delta-multiprovider-ldaps
--- a/external/bsd/openldap/dist/tests/scripts/test070-delta-multiprovider-ldaps
+++ b/external/bsd/openldap/dist/tests/scripts/test070-delta-multiprovider-ldaps
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2021 The OpenLDAP Foundation.
+## Copyright 1998-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -195,6 +195,12 @@ olcAccessLogSuccess: TRUE
 
 EOF
 $SLAPADD -F $CFDIR -n 0  -d-1< $TMP > $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
 PORT=`eval echo '$PORT'$n`
 echo "Starting server $n on TCP/IP port $PORT..."
 cd ${XDIR}${n}
diff --git a/external/bsd/openldap/dist/tests/scripts/test071-dirsync b/external/bsd/openldap/dist/tests/scripts/test071-dirsync
--- a/external/bsd/openldap/dist/tests/scripts/test071-dirsync
+++ b/external/bsd/openldap/dist/tests/scripts/test071-dirsync
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 1998-2021 The OpenLDAP Foundation.
+## Copyright 1998-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -88,6 +88,13 @@ objectclass: dcObject
 o: OpenLDAP Testing
 
 EOMODS
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 $SLAPD -f $CONF2 -h $URI2 -d $LVL > $LOG2 2>&1 &
 CONSUMERPID=$!
 if test $WAIT != 0 ; then
diff --git a/external/bsd/openldap/dist/tests/scripts/test083-argon2 b/external/bsd/openldap/dist/tests/scripts/test083-argon2
--- a/external/bsd/openldap/dist/tests/scripts/test083-argon2
+++ b/external/bsd/openldap/dist/tests/scripts/test083-argon2
@@ -2,7 +2,7 @@
 # $OpenLDAP$
 ## This work is part of OpenLDAP Software <http://www.openldap.org/>.
 ##
-## Copyright 2021 The OpenLDAP Foundation.
+## Copyright 2021-2024 The OpenLDAP Foundation.
 ## All rights reserved.
 ##
 ## Redistribution and use in source and binary forms, with or without
@@ -97,6 +97,11 @@ EOF
 fi
 
 $SLAPADD -F $CONFDIR -n 0 -l $TESTDIR/config.ldif
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
 
 echo "Starting slapd on TCP/IP port $PORT1..."
 $SLAPD -F $CONFDIR -h $URI1 -d $LVL > $LOG1 2>&1 &
