import the GCC 5.4 srcs from -current as gcc.old in preparation for GCC 6.

diff --git a/external/gpl3/gcc.old/dist/maintainer-scripts/update_web_docs_libstdcxx_svn b/external/gpl3/gcc.old/dist/maintainer-scripts/update_web_docs_libstdcxx_svn
--- a/external/gpl3/gcc.old/dist/maintainer-scripts/update_web_docs_libstdcxx_svn
+++ b/external/gpl3/gcc.old/dist/maintainer-scripts/update_web_docs_libstdcxx_svn
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 
 # "sh update_web_docs_libstdcxx.sh"
@@ -19,6 +19,7 @@ WWWDIR=/www/gcc/htdocs/onlinedocs/libstdc++
 ## No more changes should be needed.  Ha, right, whatever.
 #####################################################################
 
+FILTER="newer or same age version exists|0 blocks"
 
 PATH=/usr/local/bin:$PATH
 export SVNROOT
@@ -38,8 +39,12 @@ cd doc
 rm -f Makefile
 
 # copy the tree to the onlinedocs area, preserve directory structure
-#find . -depth -print | cpio -pdv $WWWDIR
-find . -depth -print | cpio -pd $WWWDIR > /dev/null 2>&1
+find . -depth -print | cpio -pd $WWWDIR 2>&1 | egrep -v "$FILTER"
+
+err=${PIPESTATUS[1]}
+if [ $err -gt 0 ]; then
+    printf "\nCopying failed with error code %d.\n" $err
+fi
 
 cd /
 /bin/rm -rf $WORKDIR
