sync with head.
for a reference, the tree before this commit was tagged
as yamt-pagecache-tag8.

this commit was splitted into small chunks to avoid
a limitation of cvs.  ("Protocol error: too many arguments")

diff --git a/usr.bin/vndcompress/Makefile b/usr.bin/vndcompress/Makefile
--- a/usr.bin/vndcompress/Makefile
+++ b/usr.bin/vndcompress/Makefile
@@ -1,8 +1,225 @@
-# $Id: Makefile,v 1.2 2009/04/14 22:15:28 lukem Exp $
-
 PROG=	vndcompress
-LINKS=   ${BINDIR}/vndcompress ${BINDIR}/vnduncompress
-MLINKS=  vndcompress.1 vnduncompress.1
+SRCS=	main.c offtab.c utils.c vndcompress.c vnduncompress.c
+
+LINKS=	${BINDIR}/vndcompress ${BINDIR}/vnduncompress
+MLINKS=	vndcompress.1 vnduncompress.1
+
+DPADD+=	${LIBZ}
 LDADD+=	-lz
 
+WARNS=	5
+
 .include <bsd.prog.mk>
+
+TESTFILES+=	oneblock
+XFAIL+=		oneblock.in-outx
+XFAIL+=		oneblock.cl2-cl2x
+oneblock.in:
+	head -c 512 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=	tenblock
+XFAIL+=		tenblock.in-outx
+XFAIL+=		tenblock.cl2-cl2x
+tenblock.in:
+	head -c 5120 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=	smallfile
+XFAIL+=		smallfile.in-outx
+XFAIL+=		smallfile.cl2-cl2x
+smallfile.in:
+	head -c 12345 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+CHECKS+=	check-pipe
+CLEANFILES+=	smallfile.cl2pipe
+check-pipe: .PHONY smallfile.cl2 smallfile.cl2pipe
+	cmp ${.ALLSRC}
+smallfile.cl2pipe: smallfile.in vndcompress
+	head -c 54321 < /usr/share/dict/words \
+	| ./vndcompress -l 12345 /dev/stdin ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=	onechunk
+onechunk.in:
+	head -c 65536 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=	tenchunk
+tenchunk.in:
+	head -c 655360 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=	extrablock
+XFAIL+=		extrablock.in-outx
+XFAIL+=		extrablock.cl2-cl2x
+extrablock.in:
+	head -c $$((65536 + 512)) < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=	medfile
+XFAIL+=		medfile.in-outx
+XFAIL+=		medfile.cl2-cl2x
+medfile.in:
+	head -c 123456 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=		onetinyblock
+BLOCKSIZE.onetinyblock=	512
+onetinyblock.in:
+	head -c 512 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=		tentinyblock
+BLOCKSIZE.tentinyblock=	512
+tentinyblock.in:
+	head -c 5120 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+CHECKS+=	check-pipe-restart
+CLEANFILES+=	piperestart.in piperestart.in.tmp
+CLEANFILES+=	piperestart.cl2 piperestart.cl2.tmp
+CLEANFILES+=	piperestart.cl2restart piperestart.cl2restart.tmp
+CLEANFILES+=	piperestart.cl2part piperestart.cl2part.tmp
+check-pipe-restart: .PHONY piperestart.cl2 piperestart.cl2restart
+	cmp ${.ALLSRC}
+piperestart.cl2restart: piperestart.cl2part vndcompress
+	cp piperestart.cl2part ${.TARGET}.tmp \
+	&& head -c 700000 < /usr/share/dict/words \
+	| ./vndcompress -l 655360 -k 1 -rR /dev/stdin ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+# The following rule uses ; and not && on purpose: vndcompress is
+# supposed to fail (and it is even OK to interrupt!) so we can restart
+# and fill in the rest.
+piperestart.cl2part: vndcompress
+	head -c 600000 < /usr/share/dict/words \
+	| ./vndcompress -l 655360 -k 1 /dev/stdin ${.TARGET}.tmp; \
+	mv -f ${.TARGET}.tmp ${.TARGET}
+piperestart.in:
+	head -c 655360 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+CHECKS+=	check-part
+CLEANFILES+=	part.orig part.cl2part part.cl2 part.out
+check-part: .PHONY part.orig part.out
+	cmp part.orig part.out
+part.cl2: part.orig part.cl2part vndcompress
+	cp part.cl2part ${.TARGET}.tmp \
+	&& ./vndcompress -b 512 -rR part.orig ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+part.cl2part: part.orig vndcompress
+	./vndcompress -b 512 -p 10 part.orig ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+part.orig:
+	head -c 12345 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+TESTFILES+=	smallwindow
+smallwindow.in:
+	head -c 655360 < /usr/share/dict/words > ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+smallwindow.cl2: smallwindow.in
+	./vndcompress -w 1 ${.IMPSRC} ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+smallwindow.out: smallwindow.cl2
+	./vndcompress -w 1 -d ${.IMPSRC} ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+CHECKS+=	check-pipewindow
+check-pipewindow: smallwindow.cl2
+	@echo '# expecting failure...'
+	if cat smallwindow.cl2 | ./vndcompress -w 1 -d /dev/stdin /dev/null; \
+	then \
+	  echo 'unexpected pass!' && exit 1; \
+	fi
+
+# The following two tests try to ensure a limited window size means
+# limited memory allocation.  They don't work very well.  The virtual
+# address space rlimit (ulimit -v, RLIMIT_AS) must cover the stack size
+# that is allocated automatically for the process, which varies from
+# machine architecture to machine architecture (the kernel's MAXSSIZ
+# parameter), as well as any shared libraries that get loaded in and
+# other auxiliary crud the loader or libc might allocate.
+#
+# In principle, the overhead from that and the program image should be
+# constant, and the only substantial memory allocation performed by
+# vndcompress should be w*8 bytes or (n/b)*8, where w is the window
+# size if specified, n is the size of the input, and b is the block
+# size.
+#
+# We could perhaps do an exponential growth and then binary search on
+# the virtual address space limit to determine the overhead, but that's
+# more trouble than I care to do in a makefile right now.  Currently
+# this is calibrated for NetBSD/amd64 6, where 128 MB of virtual
+# address space is allocated for the stack.  (Note `ulimit -v' takes a
+# number of kilobytes, not a number of bytes.)  Since this is not
+# reliable, however, these are commented out.
+
+#CHECKS+=	check-ulimit
+#check-ulimit:
+#	@echo '# expecting failure...'
+#	if head -c $$((64 * 1024 * 1024)) < /dev/zero \
+#	    | (ulimit -v $$((139 * 1024)) && \
+#	        ./vndcompress -w 0 -l 64m -b 512 /dev/stdin /dev/null); then \
+#	  echo 'unexpected pass!' && exit 1; \
+#	fi
+#
+#CHECKS+=	check-ulimit-window
+#check-ulimit-window:
+#	head -c $$((64 * 1024 * 1024)) < /dev/zero \
+#	| (ulimit -v $$((139 * 1024)) && \
+#	    ./vndcompress -w 8192 -l 64m -b 512 /dev/stdin /dev/null)
+
+TESTSUFFIXES+=	in cl2 cl2x out outx
+
+TESTFORMS+=	cl2 cl2x
+TESTFORMS+=	in out
+TESTFORMS+=	in outx
+
+.for testfile in ${TESTFILES}
+.  for suffix in ${TESTSUFFIXES}
+CLEANFILES+=	${testfile}.${suffix}
+CLEANFILES+=	${testfile}.${suffix}.tmp
+.  endfor
+.  for left right in ${TESTFORMS}
+CHECKS.${testfile}+=	check-${testfile}.${left}-${right}
+check-${testfile}.${left}-${right}: .PHONY \
+  ${testfile}.${left} ${testfile}.${right}
+.    if empty(XFAIL:M${testfile}.${left}-${right})
+	cmp ${testfile}.${left} ${testfile}.${right}
+.    else
+	@echo '# expecting failure...' \
+	&& echo 'cmp ${testfile}.${left} ${testfile}.${right}' \
+	&& if cmp ${testfile}.${left} ${testfile}.${right}; then \
+	  echo 'unexpected pass!' \
+	  && exit 1; \
+	fi
+.    endif
+.  endfor
+check-${testfile}: ${CHECKS.${testfile}}
+CHECKS+=	check-${testfile}
+.endfor
+
+check: .PHONY ${CHECKS}
+
+.SUFFIXES: .cl2 .cl2x .in .out .outx
+
+# XXX These tests should automatically try different window sizes, but
+# that is tricky to express in make.
+
+.in.cl2: vndcompress
+	./vndcompress ${.IMPSRC} ${.TARGET}.tmp ${BLOCKSIZE.${.PREFIX}} \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+.in.cl2x:
+	vndcompress ${.IMPSRC} ${.TARGET}.tmp ${BLOCKSIZE.${.PREFIX}} \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+.cl2.out: vndcompress
+	./vndcompress -d ${.IMPSRC} ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
+
+.cl2.outx:
+	vnduncompress ${.IMPSRC} ${.TARGET}.tmp \
+	&& mv -f ${.TARGET}.tmp ${.TARGET}
diff --git a/usr.sbin/postinstall/postinstall b/usr.sbin/postinstall/postinstall
--- a/usr.sbin/postinstall/postinstall
+++ b/usr.sbin/postinstall/postinstall
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: postinstall,v 1.126.2.2 2012/10/30 19:00:49 yamt Exp $
+# $NetBSD: postinstall,v 1.126.2.3 2014/05/22 11:43:08 yamt Exp $
 #
 # Copyright (c) 2002-2008 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -172,17 +172,18 @@ check_dir()
 	return 0
 }
 
-# check_ids op type file id [...]
+# check_ids op type file start id [...]
 #	Check if file of type "users" or "groups" contains the relevant IDs
 #	Returns 0 if ok, 1 otherwise.
 #	
 check_ids()
 {
-	[ $# -ge 4 ] || err 3 "USAGE: checks_ids op type file id [...]"
+	[ $# -ge 5 ] || err 3 "USAGE: checks_ids op type file start id [...]"
 	_op="$1"
 	_type="$2"
 	_file="$3"
-	shift 3
+	_start="$4"
+	shift 4
 	#_ids="$@"
 
 	if [ ! -f "${_file}" ]; then
@@ -197,24 +198,33 @@ check_ids()
 	if [ "${_op}" = "fix" ]; then
 		_notfixed="${NOT_FIXED}"
 	fi
-	_missing="$(${AWK} -F: '
+	_missing="$(${AWK} -v start=$_start -F: '
 		BEGIN {
-			for (x = 1; x < ARGC; x++)
-				idlist[ARGV[x]]++
+			for (x = 1; x < ARGC; x++) {
+				if (ARGV[x] == "SKIP")
+					continue;
+				idlist[ARGV[x]]++;
+				value[ARGV[x]] = start + x - 1;
+			}
 			ARGC=1
 		}
 		{
 			found[$1]++
+			number[$1] = $3
 		}
 		END {
 			for (id in idlist) {
-				if (! (id in found))
-					print id
+				if (!(id in found))
+					printf("%s (missing)\n", id)
+				else if (number[id] != value[id])
+					printf("%s (%d != %d)\n", id,
+					    number[id], value[id])
+				start++;
 			}
 		}
 	' "$@" < "${_file}")"	|| return 1
 	if [ -n "${_missing}" ]; then
-		msg "Missing ${_type}${_notfixed}:" $(echo ${_missing})
+		msg "Error ${_type}${_notfixed}:" $(echo ${_missing})
 		return 1
 	fi
 	return 0
@@ -752,7 +762,7 @@ do_defaults()
 
 	compare_dir "$op" "${SRC_DIR}/etc/defaults" "${DEST_DIR}/etc/defaults" \
 		444 \
-		daily.conf monthly.conf security.conf \
+		daily.conf monthly.conf pkgpath.conf security.conf \
 		weekly.conf ${extra_scripts}
 	failed=$(( ${failed} + $? ))
 
@@ -782,6 +792,30 @@ do_dhcpcd()
 	populate_dir "$op" true "${dir}" "${DEST_DIR}/etc" 644 dhcpcd.conf
 	failed=$(( ${failed} + $? ))
 
+	return ${failed}
+}
+
+#
+#	dhcpcdrundir
+#
+additem dhcpcdrundir "accientaly created /@RUNDIR@ does not exist"
+do_dhcpcdrundir()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_dhcpcdrundir fix|check"
+	op="$1"
+	failed=0
+
+	if [ -d /@RUNDIR@ ]; then
+		if [ "${op}" = "check" ]; then
+			msg "Remove eroneously created /@RUNDIR@"
+			failed=1
+		elif ! eval "rm -r /@RUNDIR@"; then
+			msg "Failed to remove /@RUNDIR@"
+			failed=1
+		else
+			msg "Removed eroneously created /@RUNDIR@"
+		fi
+	fi
 	return ${failed}
 }
 
@@ -818,16 +852,60 @@ do_fontconfig()
 	op="$1"
 	failed=0
 
-	if [ -f "${DEST_DIR}/etc/fonts/conf.d/10-unhinted.conf" -a \
-	     -f "${DEST_DIR}/etc/fonts/conf.d/10-autohint.conf" ]; then
-		failed=1
+	# First, check for updates we can handle.
+	if ! $SOURCEMODE; then
+		FONTCONFIG_DIR="${SRC_DIR}/etc/fonts/conf.avail" 
+	else
+		FONTCONFIG_DIR="${XSRC_DIR}/external/mit/fontconfig/dist/conf.d"
 	fi
 
-	if [ "$failed" = 1 ]; then
+	populate_dir "$op" false "${FONTCONFIG_DIR}" "${DEST_DIR}/etc/fonts/conf.avail" 444 \
+		10-autohint.conf \
+		10-no-sub-pixel.conf \
+		10-scale-bitmap-fonts.conf \
+		10-sub-pixel-bgr.conf \
+		10-sub-pixel-rgb.conf \
+		10-sub-pixel-vbgr.conf \
+		10-sub-pixel-vrgb.conf \
+		10-unhinted.conf \
+		11-lcdfilter-default.conf \
+		11-lcdfilter-legacy.conf \
+		11-lcdfilter-light.conf \
+		20-unhint-small-vera.conf \
+		25-unhint-nonlatin.conf \
+		30-metric-aliases.conf \
+		30-urw-aliases.conf \
+		40-nonlatin.conf \
+		45-latin.conf \
+		49-sansserif.conf \
+		50-user.conf \
+		51-local.conf \
+		60-latin.conf \
+		65-fonts-persian.conf \
+		65-khmer.conf \
+		65-nonlatin.conf \
+		69-unifont.conf \
+		70-no-bitmaps.conf \
+		70-yes-bitmaps.conf \
+		80-delicious.conf \
+		90-synthetic.conf
+	failed=$(( ${failed} + $? ))
+		
+	# We can't modify conf.d easily; someone might have removed a file.
+
+	conf_d_failed=0
+	# Look for old files that need to be deleted.
+	if [ -f "${DEST_DIR}/etc/fonts/conf.d/10-unhinted.conf" -a \
+	     -f "${DEST_DIR}/etc/fonts/conf.d/10-autohint.conf" ]; then
+		conf_d_failed=1
+		failed=$(( ${failed} + 1 ))
+	fi
+
+	if [ "$conf_d_failed" = 1 ]; then
 		msg \
     "Broken fontconfig configuration found; please delete these files"
 		msg \
-    "in the ${DESTDIR}/etc/fonts/conf.d/ subdirectory:"
+    "in the ${DEST_DIR}/etc/fonts/conf.d/ subdirectory:"
 		msg \
     "   10-autohint.conf 10-no-sub-pixel.conf 10-sub-pixel-bgr.conf"
 		msg \
@@ -853,9 +931,9 @@ do_gid()
 {
 	[ -n "$1" ] || err 3 "USAGE: do_gid  fix|check"
 
-	check_ids "$1" groups "${DEST_DIR}/etc/group" \
-	    named ntpd sshd authpf _pflogd _rwhod _proxy _timedc \
-	    _sdpd _httpd _mdnsd _tests _tcpdump _tss
+	check_ids "$1" groups "${DEST_DIR}/etc/group" 14 \
+	    named ntpd sshd SKIP _pflogd _rwhod staff _proxy _timedc \
+	    _sdpd _httpd _mdnsd _tests _tcpdump _tss _gpio _rtadvd
 }
 
 #
@@ -998,7 +1076,7 @@ do_mtree()
 	if ! $SOURCEMODE; then
 		MTREE_DIR="${SRC_DIR}/etc/mtree"
 	else
-		${MAKE} -C "${SRC_DIR}/etc/mtree" emit_dist_file > \
+		${MAKE} -s -C "${SRC_DIR}/etc/mtree" emit_dist_file > \
 		    "${SCRATCHDIR}/NetBSD.dist"
 		MTREE_DIR="${SCRATCHDIR}"
 	fi
@@ -1150,7 +1228,7 @@ do_rc()
 		DAEMON DISKS LOGIN NETWORKING SERVERS \
 		accounting altqd amd apmd \
 		bluetooth bootconf.sh bootparams \
-		ccd cgd cleartmp cron \
+		ccd cgd cleartmp cron devpubd \
 		dhclient dhcpcd dhcpd dhcrelay dmesg downinterfaces envsys \
 		fsck fsck_root ftp_proxy ftpd \
 		gpio \
@@ -1158,16 +1236,16 @@ do_rc()
 		identd ifwatchd inetd ipfilter ipfs ipmon ipnat ipsec \
 		irdaattach iscsi_target isdnd isibootd \
 		kdc \
-		ldconfig ldpd local lpd lvm\
+		ldconfig ldpd local lpd lvm \
 		makemandb mdnsd mixerctl mopd motd mountall mountcritlocal \
 		mountcritremote mountd moused mrouted \
-		named ndbootd network newsyslog nfsd nfslocking npf \
-		ntpd ntpdate \
+		named ndbootd network newsyslog nfsd nfslocking npf ntpd \
+		ntpdate \
 		perusertmp pf pf_boot pflogd postfix powerd ppp pwcheck \
 		quota \
-		racoon rpcbind raidframe raidframeparity random_seed \
-		rarpd rbootd rndctl \
-		root route6d routed rtadvd rtclocaltime rtsold rwho \
+		racoon rpcbind raidframe raidframeparity random_seed rarpd \
+		rbootd rndctl root route6d routed rtadvd rtclocaltime \
+		rtsold rwho \
 		savecore screenblank securelevel sshd \
 		staticroute swap1 swap2 sysctl sysdb syslogd \
 		timed tpctl ttys \
@@ -1484,7 +1562,7 @@ ${pcpath} was a directory, should be a file.
 		_notfixed="${NOT_FIXED}"
 	fi
 
-	if [ ! -d "${DESTDIR}${pcpath}" ]; then
+	if [ ! -d "${DEST_DIR}${pcpath}" ]; then
 		return 0
 	fi
 
@@ -1500,7 +1578,7 @@ ${pcpath} was a directory, should be a file.
 
 	# If the directory was removed above, then try to replace it with
 	# a file.
-	if [ -d "${DESTDIR}${pcpath}" ]; then
+	if [ -d "${DEST_DIR}${pcpath}" ]; then
 		msg "${filemsg}${_notfixed}"
 		failed=$(( ${failed} + 1 ))
 	else
@@ -1529,9 +1607,9 @@ do_uid()
 {
 	[ -n "$1" ] || err 3 "USAGE: do_uid  fix|check"
 
-	check_ids "$1" users "${DEST_DIR}/etc/master.passwd" \
-	    named ntpd postfix sshd _pflogd _rwhod _proxy _timedc \
-	    _sdpd _httpd _mdnsd _tests _tcpdump _tss
+	check_ids "$1" users "${DEST_DIR}/etc/master.passwd" 12 \
+	    postfix SKIP named ntpd sshd SKIP _pflogd _rwhod SKIP _proxy \
+	    _timedc _sdpd _httpd _mdnsd _tests _tcpdump _tss SKIP _rtadvd
 }
 
 
@@ -1591,7 +1669,7 @@ do_atf()
 		failed=1
 	fi
 	if find_file_in_dirlist atf-run.hooks "atf-run.hooks" \
-	    "${SRC_DIR}/external/bsd/atf/dist/atf-run/sample" \
+	    "${SRC_DIR}/external/bsd/atf/dist/tools/sample" \
 	    "${SRC_DIR}/etc/atf"; then
 			# ${dir} is set by find_file_in_dirlist()
 		populate_dir "${op}" true "${dir}" "${DEST_DIR}/etc/atf" 644 \
@@ -1695,34 +1773,6 @@ do_catpages()
 	return $failed
 }
 
-#
-#	obsolete
-#	(this item is last to allow other items to move obsolete files)
-#
-additem obsolete "remove obsolete file sets and minor libraries"
-do_obsolete()
-{
-	[ -n "$1" ] || err 3 "USAGE: do_obsolete  fix|check"
-	op="$1"
-	failed=0
-
-	sort -ru "${DEST_DIR}"/var/db/obsolete/* | obsolete_paths "${op}"
-	failed=$(( ${failed} + $? ))
-
-	(
-		obsolete_libs /lib
-		obsolete_libs /usr/lib
-		obsolete_libs /usr/lib/i18n
-		obsolete_libs /usr/X11R6/lib
-		obsolete_libs /usr/X11R7/lib
-		[ "$MACHINE" = "amd64" ] && obsolete_libs /usr/lib/i386
-		[ "$MACHINE" = "sparc64" ] && obsolete_libs /usr/lib/sparc
-	) | obsolete_paths "${op}"
-	failed=$(( ${failed} + $? ))
-
-	return ${failed}
-}
-
 
 #
 #	ptyfsoldnodes
@@ -1738,6 +1788,11 @@ do_ptyfsoldnodes()
 	if ! ${GREP} -E "^ptyfs" "${DEST_DIR}/etc/fstab" > /dev/null; then
 		msg "ptyfs is not in use"
 		return 0
+	fi
+
+	if [ ! -e "${DEST_DIR}/dev/pts" ]; then
+		msg "ptyfs is not properly configured: missing /dev/pts"
+		return 1
 	fi
 
 	# Find the device major numbers for the pty master and slave
@@ -1810,6 +1865,64 @@ do_ptyfsoldnodes()
 
 
 #
+#	varshm
+#
+additem varshm "check for a tmpfs mounted on /var/shm"
+do_varshm()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_varshm  fix|check"
+	op="$1"
+	failed=0
+
+	[ -f "${DEST_DIR}/etc/fstab" ] || return 0
+	if ${GREP} -w "/var/shm" "${DEST_DIR}/etc/fstab" >/dev/null 2>&1;
+	then
+		failed=0;
+	else
+		if [ "${op}" = "check" ]; then
+			failed=1
+			msg "No /var/shm mount found in ${DEST_DIR}/etc/fstab"
+		elif [ "${op}" = "fix" ]; then
+			printf '\ntmpfs\t/var/shm\ttmpfs\trw,-m1777,-sram%%25\n' \
+				>> "${DEST_DIR}/etc/fstab"
+			msg "Added tmpfs with 25% ram limit as /var/shm"
+
+		fi
+	fi
+
+	return ${failed}
+}
+
+
+#
+#	obsolete
+#	(this item is last to allow other items to move obsolete files)
+#
+additem obsolete "remove obsolete file sets and minor libraries"
+do_obsolete()
+{
+	[ -n "$1" ] || err 3 "USAGE: do_obsolete  fix|check"
+	op="$1"
+	failed=0
+
+	sort -ru "${DEST_DIR}"/var/db/obsolete/* | obsolete_paths "${op}"
+	failed=$(( ${failed} + $? ))
+
+	(
+		obsolete_libs /lib
+		obsolete_libs /usr/lib
+		obsolete_libs /usr/lib/i18n
+		obsolete_libs /usr/X11R6/lib
+		obsolete_libs /usr/X11R7/lib
+		[ "$MACHINE" = "amd64" ] && obsolete_libs /usr/lib/i386
+		[ "$MACHINE" = "sparc64" ] && obsolete_libs /usr/lib/sparc
+	) | obsolete_paths "${op}"
+	failed=$(( ${failed} + $? ))
+
+	return ${failed}
+}
+
+#
 #	end of items
 #	------------
 #
@@ -1818,7 +1931,7 @@ do_ptyfsoldnodes()
 usage()
 {
 	cat 1>&2 << _USAGE_
-Usage: ${PROGNAME} [-s srcdir] [-d destdir] [-m mach] [-a arch] op [item [...]]
+Usage: ${PROGNAME} [-s srcdir] [-x xsrcdir] [-d destdir] [-m mach] [-a arch] op [item [...]]
 	Perform post-installation checks and/or fixes on a system's
 	configuration files.
 	If no items are provided, a default set of checks or fixes is applied.
@@ -1833,7 +1946,10 @@ Usage: ${PROGNAME} [-s srcdir] [-d destdir] [-m mach] [-a arch] op [item [...]]
                           multiple such files;
 			* A temporary directory in which one or both of
 			  "etc.tgz" and "xetc.tgz" have been extracted.
-							[${SRC_DIR:-/}]
+							[${SRC_DIR:-/usr/src}]
+	-x xsrcdir      Location of the X11 source files.  This must be
+			a directory that contains a NetBSD xsrc tree.
+							[${XSRC_DIR:-/usr/src/../xsrc}]
 	-d destdir	Destination directory to check. [${DEST_DIR:-/}]
 	-m mach		MACHINE.			[${MACHINE}]
 	-a arch		MACHINE_ARCH.			[${MACHINE_ARCH}]
@@ -1876,12 +1992,13 @@ main()
 	TGZLIST=		# quoted list list of tgz files
 	SRC_ARGLIST=		# quoted list of one or more "-s" args
 	SRC_DIR="${SRC_ARG}"	# set default value for early usage()
+	XSRC_DIR="${SRC_ARG}/../xsrc"
 	N_SRC_ARGS=0		# number of "-s" args
 	TGZMODE=false		# true if "-s" specifies a tgz file
 	DIRMODE=false		# true if "-s" specified a directory
 	SOURCEMODE=false	# true if "-s" specified a source directory
 
-	while getopts s:d:m:a: ch; do
+	while getopts s:x:d:m:a: ch; do
 		case "${ch}" in
 		s)
 			qarg="$(shell_quote "${OPTARG}")"
@@ -1910,6 +2027,14 @@ main()
 				fi
 			else
 				err 2 "Invalid argument for -s option"
+			fi
+			;;
+		x)
+			if [ -d "${OPTARG}" ]; then
+				# arg refers to a directory.
+				XSRC_DIR="${OPTARG}"
+			else
+				err 2 "Not a directory for -x option"
 			fi
 			;;
 		d)
