Sync kqueue branch with -current.

diff --git a/sys/arch/mips/conf/Makefile.mips b/sys/arch/mips/conf/Makefile.mips
--- a/sys/arch/mips/conf/Makefile.mips
+++ b/sys/arch/mips/conf/Makefile.mips
@@ -1,4 +1,4 @@
-#	$NetBSD: Makefile.mips,v 1.14.2.1 2001/08/03 04:11:58 lukem Exp $
+#	$NetBSD: Makefile.mips,v 1.14.2.2 2002/01/10 19:45:57 thorpej Exp $
 
 # Makefile for NetBSD
 #
@@ -11,19 +11,20 @@
 # Machine generic makefile changes should be made in
 #	/sys/arch/mips/conf/Makefile.mips
 # after which config should be rerun for all machines of that type.
+#
+# To specify debugging, add the config line: makeoptions DEBUG="-g"
+# A better way is to specify -g only for a few files.
+#
+#	makeoptions DEBUGLIST="uvm* trap if_*"
 
+USETOOLS?=	no
+NEED_OWN_INSTALL_TARGET?=no
 .include <bsd.own.mk>
-
-# DEBUG is set to -g if debugging.
-# PROF is set to -pg if profiling.
 
 AR?=		${CROSSDIR}ar
 AS?=		${CROSSDIR}as
 CC?=		${CROSSDIR}cc
-CPP?=		cpp
 LD?=		${CROSSDIR}ld
-LORDER?=	lorder
-MKDEP?=		mkdep
 NM?=		${CROSSDIR}nm
 RANLIB?=	${CROSSDIR}ranlib
 SIZE?=		${CROSSDIR}size
@@ -31,209 +32,104 @@ STRIP?=		${CROSSDIR}strip
 TSORT?=		${CROSSDIR}tsort -q
 OBJCOPY?=	${CROSSDIR}objcopy
 
-DEFCOPTS?=	-O2
-COPTS?=		${DEFCOPTS}
-
-DEFGP?=		-G 0
-TEXTADDR?=	${DEFTEXTADDR}
-
-# source tree is located via $S relative to the compilation directory
-.ifndef S
-S=	../../../..
-.endif
-THISMIPS=	$S/arch/${TARGET_MACHINE}
-MIPS=		$S/arch/mips
-
-HAVE_EGCS!=	${CC} --version | egrep "^(2\.[89]|egcs)" ; echo
-INCLUDES=	-I. -I$S/arch -I$S -nostdinc
-CPPFLAGS=	${INCLUDES} ${IDENT} ${PARAM} -D_KERNEL -D_KERNEL_OPT -D${TARGET_MACHINE}
-CWARNFLAGS?=	-Wall -Werror -Wstrict-prototypes -Wmissing-prototypes \
-		-Wpointer-arith
-# XXX Delete -Wuninitialized for now, since the compiler doesn't
-# XXX always get it right.  --thorpej
-CWARNFLAGS+=	-Wno-uninitialized
-.if (${HAVE_EGCS} != "")
-CWARNFLAGS+=	-Wno-main
-.endif
-GP?=		${DEFGP}
-CFLAGS=		${DEBUG} ${COPTS} ${CWARNFLAGS} ${GP} \
-		-mno-abicalls -mno-half-pic
-AFLAGS=		-x assembler-with-cpp -traditional-cpp -D_LOCORE
-LINKFLAGS+=	-Ttext ${TEXTADDR} -e start ${GP}
-.if (${ENDIAN} == "-EB")
-LINKFLAGS+=	-T ${MIPS}/conf/kern.ldscript.be
-CFLAGS+=	-EB
-AFLAGS+=	-EB
-LD+=		-EB
+##
+## (1) port identification
+##
+.if ${MACHINE_ARCH} == "mipsel"
+ENDIAN=-EL
+.elif ${MACHINE_ARCH} == "mipseb"
+ENDIAN=-EB
 .else
-LINKFLAGS+=	-T ${MIPS}/conf/kern.ldscript.le
-CFLAGS+=	-EL
-AFLAGS+=	-EL
-LD+=		-EL
+.BEGIN:
+	@echo "MACHINE_ARCH ${MACHINE_ARCH} is invalid"
+	@false
 .endif
+.ifndef S
+S=		../../../..
+.endif
+THISMIPS=	$S/arch/${MACHINE}
+MIPS=		$S/arch/mips
+GENASSYM=	${MIPS}/mips/genassym.cf
+.-include "${THISMIPS}/conf/Makefile.${MACHINE}.inc"
+
+##
+## (2) compile settings
+##
+CPPFLAGS+=	-D${MACHINE}
+DEFGP?=		-G 0
+GP?=		${DEFGP}
+CFLAGS+=	${ENDIAN} ${GP} -mno-abicalls -mno-half-pic
+AFLAGS+=	${ENDIAN} -x assembler-with-cpp -traditional-cpp
+
+##
+## (3) libkern and compat
+##
+
+##
+## (4) local objects, compile rules, and dependencies
+##
+MD_OBJS=	locore.o locore_machdep.o
+MD_CFILES=
+MD_SFILES=	${MIPS}/mips/locore.S ${THISMIPS}/${MACHINE}/locore_machdep.S	
+
+locore.o: ${MIPS}/mips/locore.S assym.h
+	${NORMAL_S}
+
+locore_machdep.o: ${THISMIPS}/${MACHINE}/locore_machdep.S assym.h
+	${NORMAL_S}
+
+.if !empty(IDENT:M-DMIPS1)
+MD_OBJS+=	locore_mips1.o
+MD_SFILES+=	${MIPS}/mips/locore_mips1.S
+locore_mips1.o: ${MIPS}/mips/locore_mips1.S assym.h
+	${NORMAL_S}
+.endif
+
+.if !empty(IDENT:M-DMIPS3)
+MD_OBJS+=	locore_mips3.o
+MD_SFILES+=	${MIPS}/mips/locore_mips3.S
+locore_mips3.o: ${MIPS}/mips/locore_mips3.S assym.h
+	${NORMAL_S}
+.endif
+
+.if !empty(IDENT:M-DMIPS3_5900)
+MD_OBJS+=	locore_r5900.o
+MD_SFILES+=	${MIPS}/mips/r5900/locore_r5900.S
+locore_r5900.o: ${MIPS}/mips/r5900/locore_r5900.S assym.h
+	${NORMAL_S}
+
+MD_OBJS+=	r5900_machdep.o
+MD_CFILES+=	${MIPS}/mips/r5900/r5900_machdep.c
+r5900_machdep.o: ${MIPS}/mips/r5900/r5900_machdep.c
+	${NORMAL_C}
+.endif
+
+.if empty(IDENT:M-DNOFPU)
+MD_OBJS+=	fp.o
+MD_SFILES+=	${MIPS}/mips/fp.S
+fp.o: ${MIPS}/mips/fp.S assym.h
+	${NORMAL_S}
+.endif
+
+##
+## (5) link settings
+##
+TEXTADDR?=	${DEFTEXTADDR}
+KERNLDSCRIPT?=	${MIPS}/conf/kern.ldscript
+# some mips ports specify a "magic" format
+LINKFORMAT+=	-T ${KERNLDSCRIPT}
+EXTRA_LINKFLAGS=	${ENDIAN} ${GP}
+.if (${ENDIAN} == "-EB")
+EXTRA_LINKFLAGS+=	--oformat elf32-bigmips
+.else
+EXTRA_LINKFLAGS+=	--oformat elf32-littlemips
+.endif
+LINKFLAGS_NORMAL=	-x
 STRIPFLAGS=	-g -X -x
 
-.if exists(${THISMIPS}/conf/Makefile.${TARGET_MACHINE}.inc)
-.include "${THISMIPS}/conf/Makefile.${TARGET_MACHINE}.inc"
-.endif
-
-%INCLUDES
-
-### find out what to use for libkern
-.include "$S/lib/libkern/Makefile.inc"
-.ifndef PROF
-LIBKERN=	${KERNLIB}
-.else
-LIBKERN=	${KERNLIB_PROF}
-.endif
-
-### find out what to use for libcompat
-.include "$S/compat/common/Makefile.inc"
-.ifndef PROF
-LIBCOMPAT=	${COMPATLIB}
-.else
-LIBCOMPAT=	${COMPATLIB_PROF}
-.endif
-
-# compile rules: rules are named ${TYPE}_${SUFFIX} where TYPE is NORMAL or
-# HOSTED}, and SUFFIX is the file suffix, capitalized (e.g. C for a .c file).
-
-NORMAL_C=	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} -c $<
-NOPROF_C=	${CC} ${CFLAGS} ${CPPFLAGS} -c $<
-NORMAL_S=	${CC} ${AFLAGS} ${CPPFLAGS} -c $<
-
-%OBJS
-
-%CFILES
-
-%SFILES
-
-# load lines for config "xxx" will be emitted as:
-# xxx: ${SYSTEM_DEP} swapxxx.o
-#	${SYSTEM_LD_HEAD}
-#	${SYSTEM_LD} swapxxx.o
-#	${SYSTEM_LD_TAIL}
-SYSTEM_OBJ=	locore.o locore_machdep.o
-.if !empty(IDENT:M-DMIPS1)
-SYSTEM_OBJ+=	locore_mips1.o
-.endif
-.if !empty(IDENT:M-DMIPS3)
-SYSTEM_OBJ+=	locore_mips3.o
-.endif
-.if empty(IDENT:M-DNOFPU)
-SYSTEM_OBJ+=	fp.o
-.endif
-SYSTEM_OBJ+=	param.o ioconf.o ${OBJS} ${LIBKERN} ${LIBCOMPAT}
-SYSTEM_DEP=	Makefile ${SYSTEM_OBJ}
-SYSTEM_LD_HEAD?=@rm -f $@
-SYSTEM_LD?=	@echo ${LD} ${LINKFLAGS} -o $@ '$${SYSTEM_OBJ}' vers.o ; \
-		${LD} ${LINKFLAGS} -o $@ ${SYSTEM_OBJ} vers.o
-SYSTEM_LD_TAIL?= \
-		@${SIZE} $@; chmod 755 $@
-
-DEBUG?=
-.if ${DEBUG} == "-g"
-LINKFLAGS+=	-X
-.ifdef DEBUG_SYSTEM_LD_TAIL
-SYSTEM_LD_TAIL+=${DEBUG_SYSTEM_LD_TAIL}
-.else
-SYSTEM_LD_TAIL+=; \
-		echo mv -f $@ $@.gdb; mv -f $@ $@.gdb; \
-		echo ${STRIP} ${STRIPFLAGS} -o $@ $@.gdb; \
-		${STRIP} ${STRIPFLAGS} -o $@ $@.gdb
-.endif
-.else
-LINKFLAGS+=	-x
-.endif
-
-.ifdef POST_STRIP_SYSTEM_LD_TAIL
-SYSTEM_LD_TAIL+=${POST_STRIP_SYSTEM_LD_TAIL}
-.endif
-
-%LOAD
-
-assym.h: $S/kern/genassym.sh ${MIPS}/mips/genassym.cf
-	sh $S/kern/genassym.sh ${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} \
-	  < ${MIPS}/mips/genassym.cf > assym.h.tmp && \
-	mv -f assym.h.tmp assym.h
-
-
-param.c: $S/conf/param.c
-	rm -f param.c
-	cp $S/conf/param.c .
-
-param.o: param.c Makefile
-	${NORMAL_C}
-
-ioconf.o: ioconf.c
-	${NORMAL_C}
-
-newvers: ${SYSTEM_DEP} ${SYSTEM_SWAP_DEP}
-	sh $S/conf/newvers.sh
-	${CC} ${CFLAGS} ${CPPFLAGS} ${PROF} -c vers.c
-
-__CLEANKERNEL: .USE
-	@echo "${.TARGET}ing the kernel objects"
-	rm -f eddep *netbsd netbsd.ecoff netbsd.gdb tags *.[io] \
-	  [a-z]*.s [Ee]rrs linterrs makelinks assym.h.tmp assym.h
-
-__CLEANDEPEND: .USE
-	rm -f .depend
-
-clean: __CLEANKERNEL
-
-cleandir distclean: __CLEANKERNEL __CLEANDEPEND
-
-lint:
-	@lint -hbxncez -Dvolatile= ${CPPFLAGS} -UKGDB \
-	  ${MIPS}/mips/Locore.c ${CFILES} \
-	  ioconf.c param.c | \
-	  grep -v 'static function .* unused'
-
-tags:
-	@echo "see $S/kern/Makefile for tags"
-
-links:
-	egrep '#if' ${CFILES} | sed -f $S/conf/defines | \
-	  sed -e 's/:.*//' -e 's/\.c/.o/' | sort -u > dontlink
-	echo ${CFILES} | tr -s ' ' '\12' | sed 's/\.c/.o/' | \
-	  sort -u | comm -23 - dontlink | \
-	  sed 's,../.*/\(.*.o\),rm -f \1; ln -s ../GENERIC/\1 \1,' > makelinks
-	sh makelinks && rm -f dontlink
-
-.if !empty(IDENT:M-DMIPS1)
-SFILES+=${MIPS}/mips/locore_mips1.S
-.endif
-.if !empty(IDENT:M-DMIPS3)
-SFILES+=${MIPS}/mips/locore_mips3.S
-.endif
-.if empty(IDENT:M-DNOFPU)
-SFILES+=${MIPS}/mips/fp.S
-.endif
-SFILES+=${MIPS}/mips/locore.S \
-	${THISMIPS}/${TARGET_MACHINE}/locore_machdep.S
-SRCS=	param.c ioconf.c ${CFILES} ${SFILES}
-
-depend: .depend
-.depend: ${SRCS} assym.h param.c
-	${MKDEP} -a ${CFLAGS} ${CPPFLAGS} param.c ioconf.c ${CFILES}
-	${MKDEP} -a ${AFLAGS} ${CPPFLAGS} ${SFILES}
-	sh $S/kern/genassym.sh ${MKDEP} -f assym.dep ${CFLAGS} \
-	  ${CPPFLAGS} < ${MIPS}/mips/genassym.cf
-	@sed -e 's/.*\.o:.*\.c /assym.h: /' < assym.dep >> .depend
-	@rm -f assym.dep
-
-dependall: depend all
-
-
-# depend on root or device configuration
-autoconf.o conf.o: Makefile
-
-# depend on network or filesystem configuration
-uipc_proto.o vfs_conf.o: Makefile
-
-# depend on maxusers
-machdep.o: Makefile
+##
+## (6) port specific target dependencies
+##
 
 # depend on CPU configuration
 machdep.o mainbus.o trap.o: Makefile
@@ -241,33 +137,26 @@ machdep.o mainbus.o trap.o: Makefile
 # depend on System V IPC/shmem options
 mips_machdep.o pmap.o: Makefile
 
-locore.o: ${MIPS}/mips/locore.S assym.h
-	${NORMAL_S}
+##
+## (7) misc settings
+##
 
-locore_mips1.o: ${MIPS}/mips/locore_mips1.S assym.h
-	${NORMAL_S}
+##
+## (8) config(8) generated machinery
+##
+%INCLUDES
 
-locore_mips3.o: ${MIPS}/mips/locore_mips3.S assym.h
-	${NORMAL_S}
+%OBJS
 
-.if empty(IDENT:M-DNOFPU)
-fp.o: ${MIPS}/mips/fp.S assym.h
-	${NORMAL_S}
-.endif
+%CFILES
 
-locore_machdep.o: ${THISMIPS}/${TARGET_MACHINE}/locore_machdep.S assym.h
-	${NORMAL_S}
+%SFILES
 
-# The install target can be redefined by putting a
-# install-kernel-${MACHINE_NAME} target into /etc/mk.conf
-MACHINE_NAME!=  uname -n
-install: install-kernel-${MACHINE_NAME}
-.if !target(install-kernel-${MACHINE_NAME}})
-install-kernel-${MACHINE_NAME}:
-	rm -f /onetbsd
-	ln /netbsd /onetbsd
-	cp netbsd /nnetbsd
-	mv /nnetbsd /netbsd
-.endif
+%LOAD
 
 %RULES
+
+##
+## (9) port independent kernel machinery
+##
+.include "$S/conf/Makefile.kern.inc"
