In both postinstall and etcupdate, in modes where the -s argument refers to tgz files or to a directory in which tgz files have already been extracted, make it an error for the files that should have come from etc.tgz to be missing.  This is intended to prevent users from accidentally deleting necessary files when they run "postinstall -s xetc.tgz fix".
Use the absence of .../etc/mtree/set.etc in the extracted directory
as a test for the error case.

diff --git a/usr.sbin/etcupdate/etcupdate b/usr.sbin/etcupdate/etcupdate
--- a/usr.sbin/etcupdate/etcupdate
+++ b/usr.sbin/etcupdate/etcupdate
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: etcupdate,v 1.46 2008/09/14 14:22:45 apb Exp $
+# $NetBSD: etcupdate,v 1.47 2008/10/04 08:07:38 apb Exp $
 #
 # Copyright (c) 2001-2008 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -571,6 +571,10 @@ if ! ${CONTINUE}; then
 			eval "${MAKE_ENV} make distribution"
 		fi
 		[ $? -ne 0 ] && exit 1
+	fi
+	if ! [ -f "${TEMPROOT}/etc/mtree/set.etc" ]; then
+		echo "*** ERROR: Files from the etc.tgz set are missing"
+		exit 1
 	fi
 	if [ ! -f "${TEMPROOT}/dev/MAKEDEV" ]; then
 		echo ""
diff --git a/usr.sbin/postinstall/postinstall b/usr.sbin/postinstall/postinstall
--- a/usr.sbin/postinstall/postinstall
+++ b/usr.sbin/postinstall/postinstall
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: postinstall,v 1.70 2008/09/21 06:20:07 junyoung Exp $
+# $NetBSD: postinstall,v 1.71 2008/10/04 08:07:38 apb Exp $
 #
 # Copyright (c) 2002-2008 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -1312,6 +1312,7 @@ main()
 	N_SRC_ARGS=0		# number of "-s" args
 	TGZMODE=false		# true if "-s" specifies a tgz file
 	DIRMODE=false		# true if "-s" specified a directory
+	SOURCEMODE=false	# true if "-s" specified a source directory
 
 	while getopts s:d:m:a: ch; do
 		case "${ch}" in
@@ -1331,8 +1332,15 @@ main()
 				# human-readable messages.
 				SRC_ARG="${TGZLIST}"
 			elif [ -d "${OPTARG}" ]; then
+				# arg refers to a directory.
+				# It might be a source directory, or a
+				# directory where the sets have already
+				# been extracted.
 				DIRMODE=true
 				SRC_ARG="${OPTARG}"
+				if [ -f "${OPTARG}/etc/Makefile" ]; then
+					SOURCEMODE=true
+				fi
 			elif [ -f "${OPTARG%%:*}" -a -f "${OPTARG##*:}" \
 			       -a ! -f "${OPTARG}" ]
 			then
@@ -1405,6 +1413,9 @@ EOF
 	[ -d "${DEST_DIR}" ]	|| err 2 "${DEST_DIR} is not a directory"
 	[ -n "${MACHINE}" ]	|| err 2 "\${MACHINE} is not defined"
 	[ -n "${MACHINE_ARCH}" ] || err 2 "\${MACHINE_ARCH} is not defined"
+	if ! $SOURCEMODE && ! [ -f "${SRC_DIR}/etc/mtree/set.etc" ]; then
+		err 2 "Files from the etc.tgz set are missing"
+	fi
 
 		# If directories are /, clear them, so various messages
 		# don't have leading "//".   However, this requires
