Pull up following revision(s) (requested by martti in ticket #1630): 	usr.sbin/etcupdate/etcupdate: revision 1.29 - 1.30 Use "stty size" to acquire screen width reliably. The fields of the first line of "stty -a" is not fixed. Fix PR bin/32343. Clean ${SRCDIR}/etc when done. Patch provided by rudolf. http://mail-index.netbsd.org/tech-toolchain/2007/01/11/0001.html

diff --git a/usr.sbin/etcupdate/etcupdate b/usr.sbin/etcupdate/etcupdate
--- a/usr.sbin/etcupdate/etcupdate
+++ b/usr.sbin/etcupdate/etcupdate
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: etcupdate,v 1.21.6.7 2006/03/01 04:01:16 riz Exp $
+# $NetBSD: etcupdate,v 1.21.6.7.2.1 2007/01/12 22:56:16 bouyer Exp $
 #
 # Copyright (c) 2001 The NetBSD Foundation, Inc.
 # All rights reserved.
@@ -54,7 +54,7 @@ PATH="/sbin:/usr/sbin:/bin:/usr/bin:${PATH}"
 # Default settings
 TEMPROOT="${TEMPROOT:=/tmp/temproot}"
 PAGER="${PAGER:=/usr/bin/more}"
-SWIDTH=`stty -a | awk '/columns/{w=$6}END{if(w==0){w=80}print w}'`
+SWIDTH=`stty size | awk '{w=$2}END{if(w==0){w=80}print w}'`
 WIDTH="${WIDTH:=${SWIDTH}}"
 DIFF_COMMAND="diff -u"
 VERBOSE=false
@@ -356,6 +356,23 @@ EOF
 	rm -f "._etcupdate_${TEMPROOT}${1}"
 }
 
+# Set the environment for make.
+set_makeenv() {
+	#
+	# INSTALL_DONE=1 prevents installation of unwanted
+	# files (things that are not part of the etc set).
+	# BUILD=1 allows building of files that are wanted.
+	#
+	MAKE_ENV=" 			\
+		DESTDIR=${TEMPROOT}	\
+		MAKE=make		\
+		MTREE=mtree		\
+		TOOL_MTREE=mtree	\
+		INSTALL_DONE=1		\
+		BUILD=1			\
+		USETOOLS=never"
+}
+
 #
 # main()
 #
@@ -535,19 +552,7 @@ if ! ${CONTINUE}; then
 			echo "*** ERROR: Unable to find ${SRCDIR}/etc/Makefile"
 			exit 1
 		fi
-		# Set the environment for make.
-		#
-		# INSTALL_DONE=1 prevents installation of unwanted
-		# files (things that are not part of the etc set).
-		# BUILD=1 allows building of files that are wanted.
-		MAKE_ENV=" 			\
-			DESTDIR=${TEMPROOT}	\
-			MAKE=make		\
-			MTREE=mtree		\
-			TOOL_MTREE=mtree	\
-			INSTALL_DONE=1		\
-			BUILD=1			\
-			USETOOLS=never"
+		set_makeenv
 		echo "*** Populating ${TEMPROOT} from ${SRCDIR}"
 		cd ${SRCDIR}/etc
 		if ! ${VERBOSE}; then
@@ -612,6 +617,18 @@ if yesno "Remove ${TEMPROOT}"; then
 	rm -rf "${TEMPROOT}"
 else
 	echo "*** Keeping ${TEMPROOT}"
+fi
+
+# Clean up after "make distribution"
+if ! ${BINARYMODE}; then
+	echo "*** Cleaning up in ${SRCDIR}/etc"
+	set_makeenv
+	cd ${SRCDIR}/etc
+	if ! ${VERBOSE}; then
+		eval ${MAKE_ENV} make clean > /dev/null
+	else
+		eval ${MAKE_ENV} make clean
+	fi
 fi
 
 # Do some post-installation tasks
