sync with head.
for a reference, the tree before this commit was tagged
as yamt-pagecache-tag8.

this commit was splitted into small chunks to avoid
a limitation of cvs.  ("Protocol error: too many arguments")

diff --git a/external/ibm-public/postfix/dist/conf/postfix-script b/external/ibm-public/postfix/dist/conf/postfix-script
--- a/external/ibm-public/postfix/dist/conf/postfix-script
+++ b/external/ibm-public/postfix/dist/conf/postfix-script
@@ -1,5 +1,5 @@
 #!/bin/sh
-#	$NetBSD: postfix-script,v 1.1.1.2 2010/06/17 18:06:08 tron Exp $
+#	$NetBSD: postfix-script,v 1.1.1.2.6.1 2014/05/22 14:08:01 yamt Exp $
 #
 
 #++
@@ -126,7 +126,11 @@ start)
 		$daemon_directory/postfix-script check-warn
 	fi
 	$INFO starting the Postfix mail system
-	$daemon_directory/master &
+	# NOTE: wait in foreground process to get the initialization status.
+	$daemon_directory/master -w || {
+	    $FATAL "mail system startup failed"
+	    exit 1
+	}
 	;;
 
 drain)
