Minor cleanup and tweaks, be consistent with the other system admin scripts.

diff --git a/share/sushi/system/sysctl/script b/share/sushi/system/sysctl/script
--- a/share/sushi/system/sysctl/script
+++ b/share/sushi/system/sysctl/script
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: script,v 1.2 2004/03/09 21:36:37 garbled Exp $
+# $NetBSD: script,v 1.3 2005/01/18 18:12:55 peter Exp $
 
 BACKUPDIR="/var/sushi"
 CONFFILE="/etc/sysctl.conf"
@@ -18,15 +18,19 @@ if [ "$3" = "boot" -o "$3" = "both" ]; then
 		chmod 700 $BACKUPDIR
 	fi
 
-	# backup
+	# create a backup
 	cp -p $CONFFILE $BACKUP
+	if [ $? -ne 0 ]; then
+		echo "Can't create a backup"
+		exit 1
+	fi
 
 	# temporary file
 	cp -p $BACKUP $BACKUP.new
 
 	line=`grep -n $1 $BACKUP | cut -f1 -d:`
-	# if no line, add new entry, otherwise edit the entry.
-	if [ -z $line ]; then
+	# if no such line, add a new entry, otherwise edit the entry.
+	if [ -z "$line" ]; then
 		echo "$1=$2" >> $BACKUP.new
 	else
 		sed "${line}s/.*/$1=$2/" < $BACKUP > $BACKUP.new
@@ -39,6 +43,8 @@ if [ "$3" = "boot" -o "$3" = "both" ]; then
 		echo "Successfully wrote a new $CONFFILE"
 		echo ""
 		cat $CONFFILE
+	else
+		echo "Failed to write a new $CONFFILE"
 	fi
 
 	rm -f $BACKUP.new $BACKUP.old
diff --git a/share/sushi/system/weeklyconf/script b/share/sushi/system/weeklyconf/script
--- a/share/sushi/system/weeklyconf/script
+++ b/share/sushi/system/weeklyconf/script
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: script,v 1.2 2004/03/09 21:36:37 garbled Exp $
+# $NetBSD: script,v 1.3 2005/01/18 18:12:56 peter Exp $
 
 BACKUPDIR="/var/sushi"
 CONFFILE="/etc/weekly.conf"
@@ -13,8 +13,12 @@ if [ ! -d $BACKUPDIR ]; then
 	chmod 700 $BACKUPDIR
 fi
 
-# backup
+# create a backup
 cp -p $CONFFILE $BACKUP
+if [ $? -ne 0 ]; then
+	echo "Can't create a backup"
+	exit 1
+fi
 
 # temporary files
 cp -p $BACKUP $BACKUP.new
@@ -30,8 +34,8 @@ do
 	old=`eval echo \\$${i}`
 	if [ "$new" != "$old" ]; then
 		line=`grep -n $i $BACKUP | cut -f1 -d:`
-		# if no line, add new entry, otherwise edit the entry.
-		if [ -z $line ]; then
+		# if no such line, add a new entry, otherwise edit the entry.
+		if [ -z "$line" ]; then
 			if [ "$new" = "YES" -o "$new" = "NO" ]; then
 				echo "$i=$new" >> $BACKUP.new
 			else
@@ -57,7 +61,7 @@ if [ $? -eq 0 ]; then
 	echo ""
 	cat $CONFFILE
 else
-	echo "Failed"
+	echo "Failed to write a new $CONFFILE"
 fi
 
 rm -f $BACKUP.new $BACKUP.old
