Add support for CDBUILDEXTRA which acts like CDEXTRA to add extra items to the CD-ROM image. Make CDEXTRA and CDBUILDEXTRA be able to contain lists of files and directories which are added in turn. Add support for CDEXTRA_SKIP which contains a list of fnmatch(3) items to skip during the copy. This is _very_ useful for skipping CVS dirs for example. CDBUILDEXTRA and CDEXTRA_SKIP are to be used in Makefiles creating the images, CDEXTRA remains to be used from build.sh. Update documentation and build.sh help text to show that -C can be used to specify a list of files and directories rather than just a single dir.

diff --git a/distrib/common/Makefile.bootcd b/distrib/common/Makefile.bootcd
--- a/distrib/common/Makefile.bootcd
+++ b/distrib/common/Makefile.bootcd
@@ -1,4 +1,4 @@
-#	$NetBSD: Makefile.bootcd,v 1.12 2007/11/20 16:12:50 sborrill Exp $
+#	$NetBSD: Makefile.bootcd,v 1.13 2007/11/23 16:19:28 sborrill Exp $
 #
 # Makefile snipped to create a CD/DVD ISO
 #
@@ -15,7 +15,12 @@
 #	CDRELEASE	Set to 'true' to include $RELEASEDIR/$MACHINE on the CD
 #	CDRELEASE_NOISOS Excludes installation/cdrom directory if set
 #	CDSOURCE	Set to 'true' to include $RELEASEDIR/source on the CD
-#	CDEXTRA		Set to a directory containing extra stuff to put on CD
+#	CDEXTRA		Set to a list of files or directories containing extra
+#			stuff to put on CD (set by build.sh -C flag)
+#	CDBUILDEXTRA	Set to a list of files or directories containing extra
+#			stuff to put on CD (use in Makefiles)
+#	CDEXTRA_SKIP	A list of file exclusion paths to exclude when copying
+#			directories of extra stuff in CDEXTRA AND CDBUILDEXTRA
 #	BOOT		Defaults to $DESTDIR/usr/mdec/boot
 #	BOOTXX_CD9660	Defaults to $DESTDIR/usr/mdec/bootxx_cd9660
 #	CDBOOTOPTIONS	Options for installboot, eg -o console=com0,speed=9600
@@ -136,19 +141,35 @@ copy-releasedir:
 			. $$release_destdir; 				\
 		cd $$curdir;						\
 	fi
-	if [ "X${CDEXTRA}" != "X" ]; then 				\
-		if [ ! -d ${CDEXTRA} ]; then	 			\
-			echo "Missing ${CDEXTRA}, aborting"; 		\
-			exit 1; 					\
-		fi; 							\
+	if [ "X${CDEXTRA}${CDBUILDEXTRA}" != "X" ]; then		\
 		curdir=$$(pwd);						\
-		release_destdir=$$(pwd)/cdrom;		 		\
-		cd ${CDEXTRA};		 				\
-		echo Copying $$(pwd) to $$release_destdir ...;		\
-		${TOOL_PAX} 						\
-			-rw -pe -v 					\
-			. $$release_destdir; 				\
-		cd $$curdir;						\
+		skipflag="";						\
+		if [ "X${CDEXTRA_SKIP}" != "X" ]; then			\
+			rm -f cdskip;					\
+			for skip in ${CDEXTRA_SKIP};			\
+			do						\
+				echo $${skip} >> cdskip;		\
+			done;						\
+			skipflag="-X $${curdir}/cdskip";		\
+		fi;							\
+		for cde in ${CDEXTRA} ${CDBUILDEXTRA};			\
+		do							\
+			release_destdir=$${curdir}/cdrom;		\
+			if [ -f $${cde} ]; then				\
+				echo Copying $${cde} to $$release_destdir ...;	\
+				${CP} $${cde} $${release_destdir};	\
+			elif [ -d $${cde} ]; then			\
+				cd $${cde};				\
+				echo Copying $$(pwd) to $$release_destdir ...;	\
+				${TOOL_MTREE} -c $${skipflag} |		\
+					${TOOL_PAX} -rw -pe -v -M	\
+					$$release_destdir; 		\
+			else						\
+				echo "Missing $${cde}, aborting"; 	\
+				exit 1; 				\
+			fi; 						\
+			cd $$curdir;					\
+		done;							\
 	fi
 
 image:
