sync with HEAD

diff --git a/distrib/common/Makefile.bootcd b/distrib/common/Makefile.bootcd
--- a/distrib/common/Makefile.bootcd
+++ b/distrib/common/Makefile.bootcd
@@ -1,4 +1,4 @@
-#	$NetBSD: Makefile.bootcd,v 1.9 2007/04/11 16:21:40 christos Exp $
+#	$NetBSD: Makefile.bootcd,v 1.9.4.1 2007/11/06 23:09:47 matt Exp $
 #
 # Makefile snipped to create a CD/DVD ISO
 #
@@ -15,6 +15,7 @@
 #	CDRELEASE	Set to 'true' to include $RELEASEDIR/$MACHINE on the CD
 #	CDRELEASE_NOISOS Excludes installation/cdrom directory if set
 #	CDSOURCE	Set to 'true' to include $RELEASEDIR/source on the CD
+#	CDEXTRA		Set to a directory containing extra stuff to put on CD
 #	BOOT		Defaults to $DESTDIR/usr/mdec/boot
 #	BOOTXX_CD9660	Defaults to $DESTDIR/usr/mdec/bootxx_cd9660
 #	CDBOOTOPTIONS	Options for installboot, eg -o console=com0,speed=9600
@@ -109,6 +110,7 @@ copy-releasedir:
 			exit 1; 					\
 		fi; 							\
 		${MKDIR} cdrom/${MACHINE}; 				\
+		curdir=$$(pwd);						\
 		release_destdir=$$(pwd)/cdrom/${MACHINE}; 		\
 		cd ${RELEASEDIR}/${MACHINE}; 				\
 		echo Copying $$(pwd) to $$release_destdir ...; 		\
@@ -116,6 +118,7 @@ copy-releasedir:
 			-rw -pe -v 					\
 			${CDRELEASE_EXCLUDE}				\
 			. $$release_destdir; 				\
+		cd $$curdir;						\
 	fi
 	if ${CDSOURCE}; then 						\
 		if [ ! -d ${RELEASEDIR}/source ]; then	 		\
@@ -123,12 +126,28 @@ copy-releasedir:
 			exit 1; 					\
 		fi; 							\
 		${MKDIR} cdrom/source; 					\
+		curdir=$$(pwd);						\
 		release_destdir=$$(pwd)/cdrom/source;	 		\
 		cd ${RELEASEDIR}/source; 				\
 		echo Copying $$(pwd) to $$release_destdir ...;		\
 		${TOOL_PAX} 						\
 			-rw -pe -v 					\
 			. $$release_destdir; 				\
+		cd $$curdir;						\
+	fi
+	if [ "X${CDEXTRA}" != "X" ]; then 				\
+		if [ ! -d ${CDEXTRA} ]; then	 			\
+			echo "Missing ${CDEXTRA}, aborting"; 		\
+			exit 1; 					\
+		fi; 							\
+		curdir=$$(pwd);						\
+		release_destdir=$$(pwd)/cdrom;		 		\
+		cd ${CDEXTRA};		 				\
+		echo Copying $$(pwd) to $$release_destdir ...;		\
+		${TOOL_PAX} 						\
+			-rw -pe -v 					\
+			. $$release_destdir; 				\
+		cd $$curdir;						\
 	fi
 
 image:
