Pull up following revision(s) (requested by jnemeth in ticket #864): 	distrib/common/Makefile.bootcd: revision 1.9 	distrib/common/Makefile.bootcd: revision 1.10 	distrib/common/Makefile.bootcd: revision 1.11 	doc/BUILDING.mdoc: revision 1.51 	doc/BUILDING.mdoc: revision 1.52 	doc/BUILDING.mdoc: revision 1.53 	build.sh: revision 1.172 	build.sh: revision 1.173 	build.sh: revision 1.174 	build.sh: revision 1.175 	BUILDING: revision 1.64 	BUILDING: revision 1.65 	BUILDING: revision 1.66 	share/man/man7/release.7: revision 1.23 	share/man/man7/release.7: revision 1.24 	Makefile: revision 1.248
Add an iso-dir=directory option.  When combined with iso-image or
iso-image-source, it will cause directory to be added to the CD-ROM image.

Convert build.sh iso-dir=directory option to -C cddir as per jmmv@ on
source-changes.

diff --git a/distrib/common/Makefile.bootcd b/distrib/common/Makefile.bootcd
--- a/distrib/common/Makefile.bootcd
+++ b/distrib/common/Makefile.bootcd
@@ -1,4 +1,4 @@
-#	$NetBSD: Makefile.bootcd,v 1.5.2.2 2007/03/09 07:03:02 riz Exp $
+#	$NetBSD: Makefile.bootcd,v 1.5.2.3 2007/09/29 11:10:55 xtraeme Exp $
 #
 # Makefile snipped to create a CD/DVD ISO
 #
@@ -14,6 +14,8 @@
 # Optional variables:
 #	CDRELEASE	Set to 'true' to include $RELEASEDIR/$MACHINE on the CD
 #	CDRELEASE_NOISOS Excludes installation/cdrom directory if set
+#	CDSOURCE	Set to 'true' to include $RELEASEDIR/source on the CD
+#	CDEXTRA		Set to a directory containing extra stuff to put on CD
 #	BOOT		Defaults to $DESTDIR/usr/mdec/boot
 #	BOOTXX_CD9660	Defaults to $DESTDIR/usr/mdec/bootxx_cd9660
 #	CDBOOTOPTIONS	Options for installboot, eg -o console=com0,speed=9600
@@ -30,6 +32,7 @@
 BOOT?=		${DESTDIR}/usr/mdec/boot
 BOOTXX_CD9660?=	${DESTDIR}/usr/mdec/bootxx_cd9660
 CDRELEASE?=	false
+CDSOURCE?=	false
 .if ${CDRELEASE} == false
 CDROMS_RELEASEDIR?=	${MACHINE}/installation/cdrom
 .else
@@ -101,19 +104,50 @@ prepare:
 #
 copy-releasedir:
 	${RM} -f ${RELEASEDIR}/${CDROMS_RELEASEDIR}/${CDBASE}.iso
-	if ${CDRELEASE} ; then 						\
+	if ${CDRELEASE}; then 						\
 		if [ ! -d ${RELEASEDIR}/${MACHINE} ]; then 		\
-			echo "No releasedir ${RELEASEDIR}/${MACHINE}, aborting" ; \
-			exit 1 ; 					\
-		fi ; 							\
-		${MKDIR} cdrom/${MACHINE} ; 				\
-		release_destdir=`pwd`/cdrom/${MACHINE} ; 		\
-		cd ${RELEASEDIR}/${MACHINE} ; 				\
-		echo Copying `pwd` to $$release_destdir ... ; 		\
+			echo "Missing ${RELEASEDIR}/${MACHINE}, aborting"; \
+			exit 1; 					\
+		fi; 							\
+		${MKDIR} cdrom/${MACHINE}; 				\
+		curdir=$$(pwd);						\
+		release_destdir=$$(pwd)/cdrom/${MACHINE}; 		\
+		cd ${RELEASEDIR}/${MACHINE}; 				\
+		echo Copying $$(pwd) to $$release_destdir ...; 		\
 		${TOOL_PAX} 						\
 			-rw -pe -v 					\
 			${CDRELEASE_EXCLUDE}				\
-			. $$release_destdir ; 				\
+			. $$release_destdir; 				\
+		cd $$curdir;						\
+	fi
+	if ${CDSOURCE}; then 						\
+		if [ ! -d ${RELEASEDIR}/source ]; then	 		\
+			echo "Missing ${RELEASEDIR}/source, aborting"; 	\
+			exit 1; 					\
+		fi; 							\
+		${MKDIR} cdrom/source; 					\
+		curdir=$$(pwd);						\
+		release_destdir=$$(pwd)/cdrom/source;	 		\
+		cd ${RELEASEDIR}/source; 				\
+		echo Copying $$(pwd) to $$release_destdir ...;		\
+		${TOOL_PAX} 						\
+			-rw -pe -v 					\
+			. $$release_destdir; 				\
+		cd $$curdir;						\
+	fi
+	if [ "X${CDEXTRA}" != "X" ]; then 				\
+		if [ ! -d ${CDEXTRA} ]; then	 			\
+			echo "Missing ${CDEXTRA}, aborting"; 		\
+			exit 1; 					\
+		fi; 							\
+		curdir=$$(pwd);						\
+		release_destdir=$$(pwd)/cdrom;		 		\
+		cd ${CDEXTRA};		 				\
+		echo Copying $$(pwd) to $$release_destdir ...;		\
+		${TOOL_PAX} 						\
+			-rw -pe -v 					\
+			. $$release_destdir; 				\
+		cd $$curdir;						\
 	fi
 
 image:
