add CDEXTRA for specifying a directory of extra stuff to put on a CD

diff --git a/distrib/common/Makefile.bootcd b/distrib/common/Makefile.bootcd
--- a/distrib/common/Makefile.bootcd
+++ b/distrib/common/Makefile.bootcd
@@ -1,4 +1,4 @@
-#	$NetBSD: Makefile.bootcd,v 1.10 2007/08/30 04:27:04 jnemeth Exp $
+#	$NetBSD: Makefile.bootcd,v 1.11 2007/08/31 14:20:29 jnemeth Exp $
 #
 # Makefile snipped to create a CD/DVD ISO
 #
@@ -15,6 +15,7 @@
 #	CDRELEASE	Set to 'true' to include $RELEASEDIR/$MACHINE on the CD
 #	CDRELEASE_NOISOS Excludes installation/cdrom directory if set
 #	CDSOURCE	Set to 'true' to include $RELEASEDIR/source on the CD
+#	CDEXTRA		Set to a directory containing extra stuff to put on CD
 #	BOOT		Defaults to $DESTDIR/usr/mdec/boot
 #	BOOTXX_CD9660	Defaults to $DESTDIR/usr/mdec/bootxx_cd9660
 #	CDBOOTOPTIONS	Options for installboot, eg -o console=com0,speed=9600
@@ -128,6 +129,20 @@ copy-releasedir:
 		curdir=$$(pwd);						\
 		release_destdir=$$(pwd)/cdrom/source;	 		\
 		cd ${RELEASEDIR}/source; 				\
+		echo Copying $$(pwd) to $$release_destdir ...;		\
+		${TOOL_PAX} 						\
+			-rw -pe -v 					\
+			. $$release_destdir; 				\
+		cd $$curdir;						\
+	fi
+	if [ "X${CDEXTRA}" != "X" ]; then 				\
+		if [ ! -d ${CDEXTRA} ]; then	 			\
+			echo "Missing ${CDEXTRA}, aborting"; 		\
+			exit 1; 					\
+		fi; 							\
+		curdir=$$(pwd);						\
+		release_destdir=$$(pwd)/cdrom;		 		\
+		cd ${CDEXTRA};		 				\
 		echo Copying $$(pwd) to $$release_destdir ...;		\
 		${TOOL_PAX} 						\
 			-rw -pe -v 					\
