Import dhcpcd-6.0.0 with the following changes:  * DHCPv6 support  * wpa_supplicant hook script  * route IPv4 addresses to 127.0.0.1 for machine centric traffic  * DHCPv6 Prefix Delegation support  * DHCPv6 FQDN support  * Control existing IPv4 routes  * less spamy to syslog by default  * IPv6 protocols now wait for a valid LL address before starting  * IPv6 DAD support now listens to kernel for more accurate timings  * IPv4 code split out more cleanly so dhcpcd can be compiled for    IPv4, IPv6 or IPv4 AND IPv6  * MTU is no longer requested by default  * a DUID is now generated in /etc/dhcpcd.duid and this is used as a    client ID for DHCPv4 and DHCPv6    This does mean that you may get new DHCPv4 addresses
Many bugs have also been fixed along the way and this release addresses
the following PR's

PR bin/47364
PR bin/47502
PR bin/47666
PR bin/47699
PR bin/47775
PR bin/47776

diff --git a/external/bsd/dhcpcd/dist/dhcpcd-hooks/30-hostname b/external/bsd/dhcpcd/dist/dhcpcd-hooks/30-hostname
--- a/external/bsd/dhcpcd/dist/dhcpcd-hooks/30-hostname
+++ b/external/bsd/dhcpcd/dist/dhcpcd-hooks/30-hostname
@@ -1,3 +1,5 @@
+# $NetBSD: 30-hostname,v 1.1.1.8 2013/06/21 19:33:08 roy Exp $
+
 # Set the hostname from DHCP data if required
 
 # Some systems don't have hostname(1)
@@ -6,17 +8,32 @@ _hostname()
 	local name=
 
 	if [ -z "$1" ]; then
-		if [ -r /proc/sys/kernel/hostname ]; then
-			read name </proc/sys/kernel/hostname && echo "$name"
-		else
+		if type hostname >/dev/null 2>&1; then
 			hostname
+		elif [ -r /proc/sys/kernel/hostname ]; then
+			read name </proc/sys/kernel/hostname && echo "$name"
+		elif sysctl kern.hostname >/dev/null 2>&1; then
+			sysctl -n kern.hostname
+		elif sysctl kernel.hostname >/dev/null 2>&1; then
+			sysctl -n kernel.hostname
+		else
+			return 1
 		fi
 		return $?
 	fi
 
-	if [ -w /proc/sys/kernel/hostname ]; then
+	# Always prefer hostname(1) if we have it
+	if type hostname >/dev/null 2>&1; then
+		hostname "$1"
+	elif [ -w /proc/sys/kernel/hostname ]; then
 		echo "$1" >/proc/sys/kernel/hostname
+	elif sysctl kern.hostname >/dev/null 2>&1; then
+		sysctl -w "kern.hostname=$1"
+	elif sysctl kernel.hostname >/dev/null 2>&1; then
+		sysctl -w "kernel.hostname=$1"
 	else
+		# We know this will fail, but it will now fail
+		# with an error to stdout
 		hostname "$1"
 	fi
 }
@@ -50,14 +67,26 @@ try_hostname()
 
 set_hostname()
 {
-	if need_hostname; then
-		if [ -n "$new_host_name" ]; then
+
+	need_hostname || return
+
+	if [ -n "$new_fqdn_name" ]; then
+		try_hostname "$new_fqdn_name"
+	elif [ -n "$new_host_name" ]; then
+		if [ -n "$new_domain_name" ]; then
+			try_hostname "$new_host_name.$new_domain_name"
+		else
 			try_hostname "$new_host_name"
-		elif [ -n "$new_fqdn_name" ]; then
-			try_hostname "$new_fqdn_name"
 		fi
 	fi
 }
+
+# For ease of use, map DHCP6 names onto our DHCP4 names
+case "$reason" in
+BOUND6|RENEW6|REBIND6|REBOOT6|INFORM6)
+	new_fqdn_name="$new_dhcp6_fqdn"
+	;;
+esac
 
 if $if_up; then
 	set_hostname
