Update to dhcpcd-9.4.1 with the following changes:
 * BSD: Find the correct interface for tunnelled routes
 * OpenBSD: Fix uniqueness of routes for matching priorities
 * Linux: Support more platforms for seccomp (thanks to Fabrice Fontaine)
 * eloop: Process all waiting fd's as they come in
 * control: Unlink sockets when not in privsep
 * privsep: Renamed Master to Manager
 * privsep: Renamed Privilged Actioneer to Privileged Proxy
 * privsep: Fix getting interface VLANID on BSD
 * privsep: Enforce proper alignment of serialized struct cmsghdr
 * IPv4LL: Don't remove statically assigned addresses
 * routes: Fix route comparision for network prefixes with different masks
 * DHCP6: Only send FQDN for SOLICIT, REQUEST, RENEW, or REBIND messages
 * DHCP6: Don't spam the log when a RA repeatedly triggers an INFORM
 * DHCP: Fix infinite INFORM messages

diff --git a/external/bsd/dhcpcd/dist/hooks/30-hostname b/external/bsd/dhcpcd/dist/hooks/30-hostname
--- a/external/bsd/dhcpcd/dist/hooks/30-hostname
+++ b/external/bsd/dhcpcd/dist/hooks/30-hostname
@@ -17,16 +17,16 @@
 
 # If we used to set the hostname, but relinquish control of it, we should
 # reset to the default value.
-: ${hostname_default=localhost}
+: ${hostname_default=}
 
 # Some systems don't have hostname(1)
 _hostname()
 {
 	if [ -z "${1+x}" ]; then
-		if type hostname >/dev/null 2>&1; then
-			hostname
-		elif [ -r /proc/sys/kernel/hostname ]; then
+		if [ -r /proc/sys/kernel/hostname ]; then
 			read name </proc/sys/kernel/hostname && echo "$name"
+		elif type hostname >/dev/null 2>/dev/null; then
+			hostname
 		elif sysctl kern.hostname >/dev/null 2>&1; then
 			sysctl -n kern.hostname
 		elif sysctl kernel.hostname >/dev/null 2>&1; then
@@ -37,47 +37,38 @@ _hostname()
 		return $?
 	fi
 
-	# Always prefer hostname(1) if we have it
-	if type hostname >/dev/null 2>&1; then
-		hostname "$1"
-	elif [ -w /proc/sys/kernel/hostname ]; then
+	if [ -w /proc/sys/kernel/hostname ]; then
 		echo "$1" >/proc/sys/kernel/hostname
+	elif [ -n "$1" ] && type hostname >/dev/null 2>&1; then
+		hostname "$1"
 	elif sysctl kern.hostname >/dev/null 2>&1; then
-		sysctl -w "kern.hostname=$1"
+		sysctl -w "kern.hostname=$1" >/dev/null
 	elif sysctl kernel.hostname >/dev/null 2>&1; then
-		sysctl -w "kernel.hostname=$1"
+		sysctl -w "kernel.hostname=$1" >/dev/null
 	else
-		# We know this will fail, but it will now fail
-		# with an error to stdout
+		# May fail to set a blank hostname
 		hostname "$1"
 	fi
 }
 
-set_hostname_vars()
+is_default_hostname()
 {
-	hfqdn=false
-	hshort=false
-	case "$hostname_fqdn" in
-	[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|1)	hfqdn=true;;
-	""|[Ss][Ee][Rr][Vv][Ee][Rr])		;;
-	*)					hshort=true;;
+	case "$1" in
+	""|"$hostname_default"|localhost|localhost.localdomain)
+		return 0;;
 	esac
+	return 1
 }
 
 need_hostname()
 {
 	# Always load the hostname variable for future use
 	hostname="$(_hostname)"
-	case "$hostname" in
-	""|"(none)"|localhost|localhost.localdomain|"$hostname_default")
-		return 0;;
-	esac
+	is_default_hostname "$hostname" && return 0
 
 	case "$force_hostname" in
 	[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|1) return 0;;
 	esac
-
-	set_hostname_vars
 
 	if [ -n "$old_fqdn" ]; then
 		if ${hfqdn} || ! ${hshort}; then
@@ -119,9 +110,15 @@ try_hostname()
 
 set_hostname()
 {
-	need_hostname || return
+	hfqdn=false
+	hshort=false
+	case "$hostname_fqdn" in
+	[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|1)	hfqdn=true;;
+	""|[Ss][Ee][Rr][Vv][Ee][Rr])		;;
+	*)					hshort=true;;
+	esac
 
-	set_hostname_vars
+	need_hostname || return
 
 	if [ -n "$new_fqdn" ]; then
 		if ${hfqdn} || ! ${hshort}; then
@@ -143,7 +140,7 @@ set_hostname()
 		else
 			try_hostname "$new_host_name"
 		fi
-	elif [ -n "${hostname_default+x}" ]; then
+	elif ! is_default_hostname "$hostname"; then
 		try_hostname "$hostname_default"
 	fi
 }
@@ -156,6 +153,6 @@ BOUND6|RENEW6|REBIND6|REBOOT6|INFORM6)
 	;;
 esac
 
-if $if_up; then
+if $if_configured && $if_up && [ "$reason" != ROUTERADVERT ]; then
 	set_hostname
 fi
