Minor cleanup and tweaks, be consistent with the other system admin scripts.

diff --git a/share/sushi/system/inetdconf/script b/share/sushi/system/inetdconf/script
--- a/share/sushi/system/inetdconf/script
+++ b/share/sushi/system/inetdconf/script
@@ -1,8 +1,8 @@
 #!/bin/sh
-# $NetBSD: script,v 1.3 2004/03/09 21:36:37 garbled Exp $
+# $NetBSD: script,v 1.4 2005/01/18 18:12:55 peter Exp $
 
 BIGLIST=`grep script /usr/share/sushi/system/inetdconf/form | \
-cut -f2,3 -d, | awk '{print $1}'`
+    cut -f2,3 -d, | awk '{print $1}'`
 
 BACKUPDIR="/var/sushi"
 INETDCONF="/etc/inetd.conf"
@@ -14,8 +14,12 @@ if [ ! -d $BACKUPDIR ]; then
 	chmod 700 $BACKUPDIR
 fi
 
-# backup
+# create a backup
 cp -p $INETDCONF $BACKUP
+if [ $? -ne 0 ]; then
+	echo "Can't create a backup"
+	exit 1
+fi
 
 # temporary files
 cp -p $BACKUP $BACKUP.new
@@ -73,7 +77,7 @@ cp -p $BACKUP.new $INETDCONF
 if [ $? -eq 0 ]; then
 	echo "Successfully wrote a new $INETDCONF"
 else
-	echo "Failed"
+	echo "Failed to write a new $CONFFILE"
 fi
 
 rm -f $BACKUP.new $BACKUP.old
diff --git a/share/sushi/system/mailerconf/script b/share/sushi/system/mailerconf/script
--- a/share/sushi/system/mailerconf/script
+++ b/share/sushi/system/mailerconf/script
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: script,v 1.2 2004/03/09 21:36:37 garbled Exp $
+# $NetBSD: script,v 1.3 2005/01/18 18:12:55 peter Exp $
 
 BACKUPDIR="/var/sushi"
 MAILERCONF="/etc/mailer.conf"
@@ -11,8 +11,12 @@ if [ ! -d $BACKUPDIR ]; then
 	chmod 700 $BACKUPDIR
 fi
 
-# backup
+# create a backup
 cp -p $MAILERCONF $BACKUP
+if [ $? -ne 0 ]; then
+	echo "Can't create a backup"
+	exit 1
+fi
 
 if [ "$1" = "sendmail" ]; then
 	sendmail=0
@@ -25,7 +29,7 @@ if [ "$1" = "sendmail" ]; then
 	fi
 
 	if [ $sendmail -eq 1 ]; then
-		echo "Sendmail is already your default mailer"
+		echo "Sendmail is already your default mailer."
 		exit 0
 	fi
 	echo "sendmail		/usr/libexec/sendmail/sendmail" >$MAILERCONF
@@ -51,7 +55,7 @@ if [ "$1" = "postfix" ]; then
 	fi
 
 	if [ $postfix -eq 1 ]; then
-		echo "Postfix is already your default mailer"
+		echo "Postfix is already your default mailer."
 		exit 0
 	fi
 	echo "sendmail		/usr/libexec/postfix/sendmail" >$MAILERCONF
@@ -70,7 +74,7 @@ if [ "$1" = "exim" ]; then
 	cp $LOCALBASE/etc/exim/mailer.conf.exim $MAILERCONF
 	chown root:wheel $MAILERCONF
 	chmod 644 $MAILERCONF
-	echo "$PKGNM has now been made your default mailer"
+	echo "$PKGNM has now been made your default mailer."
 	exit 0
 fi
 
@@ -80,7 +84,7 @@ if [ "$1" = "postfix-current" ]; then
 	cp $LOCALBASE/etc/mailer.conf.postfix $MAILERCONF
 	chown root:wheel $MAILERCONF
 	chmod 644 $MAILERCONF
-	echo "$PKGNM has now been made your default mailer"
+	echo "$PKGNM has now been made your default mailer."
 	exit 0
 fi
 
@@ -90,6 +94,6 @@ if [ "$1" = "sendmail88" ]; then
 	cp $LOCALBASE/etc/mailer.conf.sendmail $MAILERCONF
 	chown root:wheel $MAILERCONF
 	chmod 644 $MAILERCONF
-	echo "$PKGNM has now been made your default mailer"
+	echo "$PKGNM has now been made your default mailer."
 	exit 0
 fi
diff --git a/share/sushi/system/sshdconf/script b/share/sushi/system/sshdconf/script
--- a/share/sushi/system/sshdconf/script
+++ b/share/sushi/system/sshdconf/script
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: script,v 1.2 2004/03/09 21:36:37 garbled Exp $
+# $NetBSD: script,v 1.3 2005/01/18 18:12:55 peter Exp $
 
 BACKUPDIR="/var/sushi"
 CONFFILE="/etc/ssh/sshd_config"
@@ -13,8 +13,12 @@ if [ ! -d $BACKUPDIR ]; then
         chmod 700 $BACKUPDIR
 fi
 
-# backup
+# create a backup
 cp -p $CONFFILE $BACKUP
+if [ $? -ne 0 ]; then
+	echo "Can't create a backup"
+	exit 1
+fi
 
 if [ "$1" = "yes" ]; then
 	RESTART=yes
diff --git a/share/sushi/system/usermgmtconf/script b/share/sushi/system/usermgmtconf/script
--- a/share/sushi/system/usermgmtconf/script
+++ b/share/sushi/system/usermgmtconf/script
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $NetBSD: script,v 1.2 2004/03/09 21:36:37 garbled Exp $
+# $NetBSD: script,v 1.3 2005/01/18 18:12:56 peter Exp $
 
 BACKUPDIR="/var/sushi"
 CONFFILE="/etc/usermgmt.conf"
@@ -19,8 +19,12 @@ if [ ! -f $CONFFILE ]; then
 	chmod 644 $CONFFILE
 fi
 
-# backup
+# create a backup
 cp -p $CONFFILE $BACKUP
+if [ $? -ne 0 ]; then
+	echo "Can't create a backup"
+	exit 1
+fi
 
 BIGLIST="group class base_dir skel_dir shell inactive expire preserve \
 password range"
@@ -48,7 +52,7 @@ if [ $? -eq 0 ]; then
 	echo ""
 	cat $CONFFILE
 else
-	echo "Failed"
+	echo "Failed to write a new $CONFFILE"
 fi
 
 rm -f $BACKUP.new
