merge dhcp-3.0.3

diff --git a/dist/dhcp/client/scripts/freebsd b/dist/dhcp/client/scripts/freebsd
--- a/dist/dhcp/client/scripts/freebsd
+++ b/dist/dhcp/client/scripts/freebsd
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: freebsd,v 1.3 2003/02/18 17:08:40 drochner Exp $
+# $Id: freebsd,v 1.4 2005/08/11 17:13:21 drochner Exp $
 #
 # $FreeBSD$
 
@@ -13,13 +13,24 @@ fi
 make_resolv_conf() {
   if [ x"$new_domain_name_servers" != x ]; then
     if [ "x$new_domain_name" != x ]; then
-      echo search $new_domain_name >/etc/resolv.conf
+      ( echo search $new_domain_name >/etc/resolv.conf )
+      exit_status=$?
     else
-      rm /etc/resolv.conf
+      if [ -e /etc/resolv.conf ] ; then
+	( rm /etc/resolv.conf )
+	exit_status=$?
+      else
+	( touch /etc/resolv.conf )
+	exit_status=$?
+      fi
     fi
-    for nameserver in $new_domain_name_servers; do
-      echo nameserver $nameserver >>/etc/resolv.conf
-    done
+    if [ $exit_status -ne 0 ]; then
+      $LOGGER "WARNING: Unable to update resolv.conf: Error $exit_status"
+    else
+      for nameserver in $new_domain_name_servers; do
+	( echo nameserver $nameserver >>/etc/resolv.conf )
+      done
+    fi
   fi
 }
 
