Pull up following revision(s) (requested by kre in ticket #1324): 	distrib/sets/lists/base/mi: 1.1125, 1.1128, 1.1132, 1.1137, 1.1139, 1.1140 	external/public-domain/tz/dist/CONTRIBUTING: up to 1.1.1.3 	external/public-domain/tz/dist/LICENSE: up to 1.1.1.2 	external/public-domain/tz/dist/Makefile: up to 1.1.1.16 	external/public-domain/tz/dist/NEWS: up to 1.1.1.16 	external/public-domain/tz/dist/README: up to 1.1.1.5 	external/public-domain/tz/dist/TZDATA_VERSION: up to 1.6 	external/public-domain/tz/dist/Theory: up to 1.1.1.9 	external/public-domain/tz/dist/africa: up to 1.1.1.9 	external/public-domain/tz/dist/antarctica: up to 1.1.1.7 	external/public-domain/tz/dist/asia: up to 1.1.1.15 	external/public-domain/tz/dist/australasia: up to 1.1.1.10 	external/public-domain/tz/dist/backward: up to 1.1.1.6 	external/public-domain/tz/dist/backzone: up to 1.1.1.10 	external/public-domain/tz/dist/etcetera: up to 1.1.1.2 	external/public-domain/tz/dist/europe: up to 1.1.1.16 	external/public-domain/tz/dist/factory: up to 1.1.1.2 	external/public-domain/tz/dist/iso3166.tab: up to 1.1.1.4 	external/public-domain/tz/dist/leap-seconds.list: up to 1.1.1.6 	external/public-domain/tz/dist/leapseconds: up to 1.1.1.7 	external/public-domain/tz/dist/northamerica: up to 1.1.1.14 	external/public-domain/tz/dist/southamerica: up to 1.1.1.10 	external/public-domain/tz/dist/version: up to 1.1.1.3 	external/public-domain/tz/dist/zone.tab: up to 1.1.1.10 	external/public-domain/tz/dist/zone1970.tab: up to 1.1.1.12 	external/public-domain/tz/share/zoneinfo/Makefile: up to 1.3 	external/public-domain/tz/tzdata2netbsd: up to 1.11 Update tzdata to 2016j.

diff --git a/external/public-domain/tz/tzdata2netbsd b/external/public-domain/tz/tzdata2netbsd
--- a/external/public-domain/tz/tzdata2netbsd
+++ b/external/public-domain/tz/tzdata2netbsd
@@ -1,20 +1,22 @@
-# $NetBSD: tzdata2netbsd,v 1.2.4.3 2016/04/11 09:59:00 snj Exp $
+# $NetBSD: tzdata2netbsd,v 1.2.4.4 2016/12/13 07:29:24 snj Exp $
 
 # For use by NetBSD developers when updating to new versions of tzdata.
 #
 # 0. Be in an up-to-date checkout of src/external/public-domain/tz
 #    from NetBSD-current.
 # 1. Edit OLDVER and NEWVER below.
-# 2. Run this script.  You will be prompted for confirmation before
+# 2. Make sure that you have Paul Eggert's 4K RSA public key in your
+#    keyring (62AA7E34, eggert@cs.ucla.edu)
+# 3. Run this script.  You will be prompted for confirmation before
 #    anything major (such as a cvs operation).
-# 3. If something fails, abort the script and fix it.
-# 4. Re-run this script until you are happy.  It's designed to
+# 4. If something fails, abort the script and fix it.
+# 5. Re-run this script until you are happy.  It's designed to
 #    be re-run over and over, and later runs will try not to
 #    redo non-trivial work done by earlier runs.
 #
 
-OLDVER=2015f
-NEWVER=2016b
+OLDVER=2016h
+NEWVER=2016i
 
 # Uppercase variants of OLDVER and NEWVER
 OLDVER_UC="$( echo "${OLDVER}" | tr '[a-z]' '[A-Z]' )"
@@ -48,6 +50,8 @@ IMPORTDONEFILE="${WORKDIR}/import.done"
 MERGSMSGFILE="${WORKDIR}/merge.msg"
 MERGEDONEFILE="${WORKDIR}/merge.done"
 COMMITMERGEDONEFILE="${WORKDIR}/commitmerge.done"
+
+EDITOR=${EDITOR:-vi}
 
 DOIT()
 {
@@ -149,14 +153,13 @@ checksig()
 	# The output should contain lines that match all the following regexps
 	#
 	while read line; do
-		if ! grep -q -e "^${line}\$" "${PGPVERIFYLOG}"; then
+		if ! grep -E -q -e "^${line}\$" "${PGPVERIFYLOG}"; then
 			echo >&2 "Failed to verify signature: ${line}"
 			return 1
 		fi
 	done <<'EOF'
-gpg: Signature made .* using RSA key ID 62AA7E34
+gpg: Signature made .* using RSA key ID (62AA7E34|44AD418C)
 gpg: Good signature from "Paul Eggert <eggert@cs.ucla.edu>"
-Primary key fingerprint: 7E37 92A9 D8AC F7D6 33BC  1588 ED97 E90E 62AA 7E34
 gpg exit status 0
 EOF
 }
@@ -190,6 +193,7 @@ trimnews()
 		// { if (inrange) print; }
 		' \
 		<"${NEWSFILE}" >"${NEWSTRIMFILE}"
+	echo "tzdata-${NEWVER}" > ${TZDISTDIR}/TZDATA_VERSION
 }
 
 # Create IMPORTMSGFILE from NEWSTRIMFILE, by ignoring some sections,
@@ -266,7 +270,7 @@ editimportmsg()
 	fi
 	# Pass both IMPORTMSGFILE and NEWSFILE to the editor, so that the
 	# user can easily consult NEWSFILE while editing IMPORTMSGFILE.
-	vi "${IMPORTMSGFILE}" "${NEWSFILE}"
+	${EDITOR} "${IMPORTMSGFILE}" "${NEWSFILE}"
 }
 
 cvsimport()
@@ -347,7 +351,7 @@ extra()
 Also do the following:
  * Edit src/doc/3RDPARTY
  * Edit src/doc/CHANGES
- * Edit src/distrib/sets/base/mi if the set of installed files has changed.
+ * Edit src/distrib/sets/lists/base/mi if the set of installed files altered.
  * Submit pullup requests for all active release branches.
  * rm -rf ${WORKDIR}
 EOF
