Pull up following revision(s) (requested by jun in ticket #955): 	doc/3RDPARTY: patch 	external/public-domain/tz/dist/Makefile: up to 1.1.1.9 	external/public-domain/tz/dist/NEWS: up to 1.1.1.9 	external/public-domain/tz/dist/Theory: up to 1.1.1.4 	external/public-domain/tz/dist/africa: up to 1.1.1.6 	external/public-domain/tz/dist/antarctica: up to 1.1.1.4 	external/public-domain/tz/dist/asia: up to 1.1.1.8 	external/public-domain/tz/dist/backward: up to 1.1.1.4 	external/public-domain/tz/dist/backzone: up to 1.1.1.7 	external/public-domain/tz/dist/checktab.awk: up to 1.1.1.7 	external/public-domain/tz/dist/europe: up to 1.1.1.9 	external/public-domain/tz/dist/iso3166.tab: up to 1.1.1.2 	external/public-domain/tz/dist/leap-seconds.list: up to 1.1.1.4 	external/public-domain/tz/dist/leapseconds: up to 1.1.1.5 	external/public-domain/tz/dist/northamerica: up to 1.1.1.9 	external/public-domain/tz/dist/southamerica: up to 1.1.1.7 	external/public-domain/tz/dist/zone.tab: up to 1.1.1.5 	external/public-domain/tz/dist/zone1970.tab: up to 1.1.1.7 	external/public-domain/tz/tzdata2netbsd: up to 1.7 Update tzdata to 2015f.

diff --git a/external/public-domain/tz/tzdata2netbsd b/external/public-domain/tz/tzdata2netbsd
--- a/external/public-domain/tz/tzdata2netbsd
+++ b/external/public-domain/tz/tzdata2netbsd
@@ -1,20 +1,20 @@
-# $NetBSD: tzdata2netbsd,v 1.2.4.1 2014/09/21 18:50:41 snj Exp $
+# $NetBSD: tzdata2netbsd,v 1.2.4.2 2015/09/10 03:00:37 snj Exp $
 
 # For use by NetBSD developers when updating to new versions of tzdata.
 #
 # 0. Be in an up-to-date checkout of src/external/public-domain/tz
 #    from NetBSD-current.
 # 1. Edit OLDVER and NEWVER below.
-# 3. Run this script.  You will be prompted for confirmation before
+# 2. Run this script.  You will be prompted for confirmation before
 #    anything major (such as a cvs operation).
-# 4. If something fails, abort the script and fix it.
-# 5. Re-run this script until you are happy.  It's designed to
+# 3. If something fails, abort the script and fix it.
+# 4. Re-run this script until you are happy.  It's designed to
 #    be re-run over and over, and later runs will try not to
 #    redo non-trivial work done by earlier runs.
 #
 
-OLDVER=2014f
-NEWVER=2014g
+OLDVER=2015e
+NEWVER=2015f
 
 # Uppercase variants of OLDVER and NEWVER
 OLDVER_UC="$( echo "${OLDVER}" | tr '[a-z]' '[A-Z]' )"
@@ -40,11 +40,14 @@ EXTRACTDIR="${WORKDIR}/extract"
 # Files in the work directory
 DISTFILE="${WORKDIR}/${DISTURL##*/}"
 SIGFILE="${DISTFILE}.sig"
+PGPVERIFYLOG="${WORKDIR}/pgpverify.log"
 NEWSFILE="${WORKDIR}/NEWS"
 NEWSTRIMFILE="${WORKDIR}/NEWS.trimmed"
 IMPORTMSGFILE="${WORKDIR}/import.msg"
+IMPORTDONEFILE="${WORKDIR}/import.done"
 MERGSMSGFILE="${WORKDIR}/merge.msg"
-PGPVERIFYLOG="${WORKDIR}/pgpverify.log"
+MERGEDONEFILE="${WORKDIR}/merge.done"
+COMMITMERGEDONEFILE="${WORKDIR}/commitmerge.done"
 
 DOIT()
 {
@@ -216,7 +219,7 @@ EOF
 			goodsection = 0;
 			havesentence = 0;
 			print "Import tzdata"newver" from "disturl;
-			print "and NEWS file from "newsurl;
+			#print "and NEWS file from "newsurl;
 		}
 		/^Release/ {
 			# "Release <version> - <date>"
@@ -229,7 +232,7 @@ EOF
 		/^$/ { blankline = 1; havesentence = 0; }
 		/^  Changes affecting/ { goodsection = 0; }
 		/^  Changes affecting.*time/ { goodsection = 1; }
-		/^  Changes affecting.*data format/ { goodsection = 1; }
+		/^  Changes affecting.*data/ { goodsection = 1; }
 		/^  Changes affecting.*documentation/ || \
 		/^  Changes affecting.*commentary/ {
 			t = gensub("^ *", "", 1, $0);
@@ -268,6 +271,12 @@ editimportmsg()
 
 cvsimport()
 {
+	if [ -e "${IMPORTDONEFILE}" ]; then
+		cat >&2 <<EOF
+The CVS import has already been performed.
+EOF
+		return 0
+	fi
 	if ! [ -s "${IMPORTMSGFILE}" ] \
 	|| grep -q '^EDIT' "${IMPORTMSGFILE}"
 	then
@@ -281,29 +290,38 @@ EOF
 	( cd "${EXTRACTDIR}" &&
 	  DOIT cvs -d "${CVSROOT}" import -m "$(cat "${IMPORTMSGFILE}")" \
 		"${REPODIR}" "${CVSBRANCHTAG}" "${CVSNEWTAG}"
-	)
+	) && touch "${IMPORTDONEFILE}"
 }
 
 cvsmerge()
-{(
+{
 
 	cd "${TZDISTDIR}" || exit 1
-	DOIT cvs -d "${CVSROOT}" update -j"${CVSOLDTAG}" -j"${CVSNEWTAG}"
-)}
+	if [ -e "${MERGEDONEFILE}" ]; then
+		cat >&2 <<EOF
+The CVS merge has already been performed.
+EOF
+		return 0
+	fi
+	DOIT cvs -d "${CVSROOT}" update -j"${CVSOLDTAG}" -j"${CVSNEWTAG}" \
+	&& touch "${MERGEDONEFILE}"
+}
 
 resolveconflicts()
 {
-	cat <<EOF
-Resolve conflicts resulting from the cvs merge.
-exit 0 when done.  exit 1 to abort.
+	cd "${TZDISTDIR}" || exit 1
+	if grep -l '^[<=>][<=>][<=>]' *
+	then
+		cat <<EOF
+There appear to be conflicts in the files listed above.
+Resolve conflicts, then re-run this script.
 EOF
-	nl='
-'
-	PS1="[inside ${0##*/}]${nl}${PS1}" sh -i
+		return 1
+	fi
 }
 
 cvscommitmerge()
-{(
+{
 	cd "${TZDISTDIR}" || exit 1
 	if grep -l '^[<=>][<=>][<=>]' *
 	then
@@ -313,8 +331,15 @@ Not performing cvs commit.
 EOF
 		return 1
 	fi
-	DOIT cvs -d "${CVSROOT}" commit -m "Merge tzdata${NEWVER}"
-)}
+	if [ -e "${COMMITMERGEDONEFILE}" ]; then
+		cat >&2 <<EOF
+The CVS commmit (of the merge result) has already been performed.
+EOF
+		return 0
+	fi
+	DOIT cvs -d "${CVSROOT}" commit -m "Merge tzdata${NEWVER}" \
+	&& touch "${COMMITMERGEDONEFILE}"
+}
 
 extra()
 {
